### ISSUE TITLE
Foundation style: bright text on bright background

### ISSUE THREAD

**Issue by idleberg** [isagalaev/highlight.js#1002]
@mojavelinux Please have a look at `foundation.css`, some text is unreadable

Screenshot from the CoffeeScript example:

![screen shot 2015-11-26 at 17 36 59](https://cloud.githubusercontent.com/assets/1504938/11427597/6f842368-9464-11e5-8e34-357b4903b980.png)

**Comment by isagalaev** [comment]
It's fixed in master with the merge of a big style refactoring that happened lately. Have a look here: https://highlightjs.org/static/tmp/demo/ (it's a demo snapshot from yesterday).

**Comment by idleberg** [comment]
Great!
