### ISSUE TITLE
Java method not recognized if return type has more than one generic type

### ISSUE THREAD

**Issue by mvh77** [isagalaev/highlight.js#1010]
Hi,

So this is highlighted properly:
```java
Option<Integer> parseAge(String input) {
    ...
}
```
but this is not, seems to be because of the second type parameter:
```java
Either<String, Integer> parseAge(String input) {
    ...
}
```
using 8.9.1

**Comment by isagalaev** [comment]
Good catch, thanks! Fixed.

**Comment by mvh77** [comment]
Sorry, I should have reported this at the same time, but still doesn't work for nested types, like:
```java
Or<String, One<String>> parseName(String input) {
    ...
}
```

**Comment by isagalaev** [comment]
Ah… This is something our parser cannot do right now, unfortunately. We rely on a regex to first roughly detect the whole function declaration line and only then parse it in earnest. But a regex can't handle nested things, obviously. We have plans for making the parser smarter to handle such cases (it's not the only one) but for now it'll have to remain as a known deficiency of highlight.js.
