### ISSUE TITLE
Missed className var in php brush

### ISSUE THREAD

**Issue by doiftrue** [isagalaev/highlight.js#1012]
it seems mised `className` var on this line: https://github.com/isagalaev/highlight.js/blob/master/src/languages/php.js#L10

variables not hightlited, i fix it by adding 

```
className: 'variable', begin: '\\$+[a-zA-Z_\x7f-\xff][a-zA-Z0-9_\x7f-\xff]*'
```

**Comment by isagalaev** [comment]
That's intentional. We stopped highlighting variables in PHP for consistency with other similar languages: Perl, Ruby, Python, JavaScript, Java — any language with a common imperative syntax. And the mode itself is still useful as it counts toward auto detection relevance.
