### ISSUE TITLE
typescript: Multiline comments are parsed incorrectly

### ISSUE THREAD

**Issue by elisee** [isagalaev/highlight.js#1016]
Hi! Thanks for a cool lib.

It seems multiline comments are parsed incorrectly in TypeScript mode. (This is not a new bug from 9.0.0, it already happened in 8.9.1 but I only just got around to reporting it)

For instance, the string `/********/` isn't understood as a comment.
See http://jsbin.com/nisiregiju/edit?html,output

A few things to note:

 * If one removes a single star, then it becomes a comment.
 * If one switches to the `javascript` mode, it becomes a comment too

Here are a couple more concrete examples that don't work either:

The header of `lib.d.ts` from TypeScript:

```
/*! *****************************************************************************
Copyright (c) Microsoft Corporation. All rights reserved. 
Licensed under the Apache License, Version 2.0 (the "License"); you may not use
this file except in compliance with the License. You may obtain a copy of the
License at http://www.apache.org/licenses/LICENSE-2.0  
 
THIS CODE IS PROVIDED ON AN *AS IS* BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION ANY IMPLIED
WARRANTIES OR CONDITIONS OF TITLE, FITNESS FOR A PARTICULAR PURPOSE, 
MERCHANTABLITY OR NON-INFRINGEMENT. 
 
See the Apache Version 2.0 License for specific language governing permissions
and limitations under the License.
***************************************************************************** */
```

The header from RNG.js:

```
/**
 * Seedable random number generator functions.
 * @version 1.0.0
 * @license Public Domain
 *
 * @example
 * var rng = new RNG('Example');
 * rng.random(40, 50);  // =>  42
 * rng.uniform();       // =>  0.7972798995050903
 * rng.normal();        // => -0.6698504543216376
 * rng.exponential();   // =>  1.0547367609131555
 * rng.poisson(4);      // =>  2
 * rng.gamma(4);        // =>  2.781724687386858
 */
```

Removing a single `'` from the above makes it parsed as a comment somehow.

**Comment by sourrust** [comment]
It looks like you are forgetting to include the typescript language definition since CDN versions don't include them in the default bundle. Add this after the script tag for `highlight.min.js` and it should work fine.

```html
<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.0.0/languages/typescript.min.js"></script>
```

And if you want to know which languages are in the current bundle it is `hljs.listLanguages()`.

**Comment by elisee** [comment]
Thanks, my bad!
