### ISSUE TITLE
[Testing] Please verify 8.4.0 and 9.0.0 Difference

### ISSUE THREAD

**Issue by oleersoy** [isagalaev/highlight.js#1017]
Hi,

This question is related to this issue https://github.com/isagalaev/highlight.js/issues/1014.  In gulp-highlight, the following test is now failing:

HIGHLIGHT TARGET:
``` html
<code>* { box-sizing: border-box }</code>
``` 

CURRENT HIGHLIGHT RESULT:
``` html
<code>* { <span class="hljs-attribute">box-sizing</span>: border-box }</code>
```

EXPECTED RESULT:
``` html
<code>* <span class="hljs-rules">{ <span class="hljs-rule"><span class="hljs-attribute">box-sizing</span>:<span class="hljs-value"> border-box </span></span></span>}</code>
```
Just curious as to whether the CURRENT HIGHLIGHT RESULT is right?

TIA,
Ole

**Comment by isagalaev** [comment]
Yes, the whole markup has been significantly reworked in this release (hence the major version change). The easy way around is probably to go back to 8.9.1 but the right way forward is simply update the tests with new markup.

I should also note that it's usually not a good idea to have tests for the code that one doesn't control anyway, so may be gulp-highlight shouldn't test the markup created by highlight.js in the first place.

**Comment by oleersoy** [comment]
Great points.  I'll pass the message on.  Thanks.

**Comment by Sannis** [comment]
> I should also note that it's usually not a good idea to have tests for the code that one doesn't control anyway
And also a good idea is to contribute tests to such dependencies.
