### ISSUE TITLE
Highlighting not displaying

### ISSUE THREAD

**Issue by paul-mesnilgrente** [isagalaev/highlight.js#1018]
Hello,

I'm currently working on a project with symfony and bootstrap. I still work locally on ubuntu with firefox.

I have included :

- ``<link rel="stylesheet" type="text/css" href="/css/blog_dark_4.css" />``
- ``highlight.js/src/highlight.js``
- ``<script>hljs.initHighlightingOnLoad();</script>``

The links are working (I verified by clicking on them in the source code)
the background is dark... but there is no highlighting. The blocks seems to be well detected because when I look the source by doing "examine element" with firefox, it writes ``class=php hljs``. But... no highlighting.

Have you got an idea ? Thank you very much for your work.

**Comment by isagalaev** [comment]
I could hazard a guess that you're using a custom style ('blog_dark_4.css' is not among those we bundle) which doesn't work with the markup changes we've [introduced in the 9.0.0 release][9]. You either use one of the bundled styles instead or rework your custom style according to [the style guide][s].

[9]: https://github.com/isagalaev/highlight.js/blob/master/CHANGES.md#version-900
[s]: http://highlightjs.readthedocs.org/en/latest/style-guide.html

**Comment by paul-mesnilgrente** [comment]
blog_dark_4.css is dark.css actually, the one in src/styles. It is the AsseticBundle which rename the file. And before to custom my style, I would like that the default one works... Another idea maybe ?

**Comment by sourrust** [comment]
Based on the path you are using for the highlight.js file, I'm assuming you using the library straight from the repository with no build step. As the "[getting the library][1]" section states, you need to either build highlight.js with our build script or use one of the several download option on [the website][2].

[1]: https://github.com/isagalaev/highlight.js#getting-the-library
[2]: https://highlightjs.org/download/

**Comment by paul-mesnilgrente** [comment]
ooohh ! sorry I didn't understand. I thought it was the same. It's working the built library. Thanks :)
