### ISSUE TITLE
Multiline comment not finished in a python code

### ISSUE THREAD

**Issue by bryant1410** [isagalaev/highlight.js#1021]
See this: https://github.com/nltk/nltk/blob/7a1aad38469797d543c0791095a54c184d5205c4/nltk/tokenize/__init__.py

The comment is finished with triple double-quote, but all the file is highlighted as a comment.

**Comment by isagalaev** [comment]
Seems to be working fine with the latest 9.0.0 release: http://jsfiddle.net/bvgt2spb/
Could you set up a page somewhere showing what's wrong?

**Comment by bryant1410** [comment]
What you show works fine!! But doesn't github itself use this library? Because it's highlighted in a wrong way in the link I passed.

**Comment by Sannis** [comment]
No, Github does not use this lib.
