### ISSUE TITLE
Objective-C has a hyphen, not a space

### ISSUE THREAD

**Issue by ZevEisenberg** [isagalaev/highlight.js#1025]
On https://highlightjs.org/static/demo/, there is a code sample for "Objective C". The correct spelling is "Objective-C", with a hyphen. I'd fix it myself, but I couldn't find the code for that page. Is it in this repo?

**Comment by Sannis** [comment]
This will be fixed on site with the next release, thanks!

**Comment by isagalaev** [comment]
@ZevEisenberg to answer your question, it's technically in the repo but it's generated by the build tool from a template, and the language name comes from the language metadata on top of the .js file.
