### ISSUE TITLE
highlightAuth gets stuck on specific string

### ISSUE THREAD

**Issue by gkoberger** [isagalaev/highlight.js#1026]
For some reason, the following will bring highlight.js to a grinding halt:

    var hjs = require('highlight.js');
    hjs.highlightAuto('--5cd3320a-5aac-4453-b3a4-cbb52a4cba5d')

It can't get past [this line](https://github.com/isagalaev/highlight.js/blob/master/src/highlight.js#L461):

    match = top.terminators.exec(value);

And the value for top.terminators here is:

    ///|/\*|@(import|media|charset|font-face|(-[a-z]+-)?keyframes|supports|document|namespace|page|viewport|host)\b|@[\w-]+\s*:|@[\w-]+|[\.#:&\[]|([\w-]+|@{[\w-]+})+[^;]*{|([\w-]+|@{[\w-]+})+|[=>'/<($"]/gim

It seems to be testing for LESS when it breaks. Other similar strings (such as, say, a truncated '--5cd3320a-5aac-4453') seem to work just fine. But if it starts with the above string, it freezes up completely and never gets past that line.

**Comment by isagalaev** [comment]
It was fixed almost exactly a year ago, you're most likely using an outdated version.

**Comment by gkoberger** [comment]
Thank you!
