### ISSUE TITLE
Stylus highlight fails if css syntax exists

### ISSUE THREAD

**Issue by puzrin** [isagalaev/highlight.js#1028]
Screenshot (hljs 9.0):

![hl_styl](https://cloud.githubusercontent.com/assets/319465/11872744/035c12d8-a4e8-11e5-9ea5-310c27ed8c2c.png)

`{}` & `;` break highlighting. Both are valid in stylus files.

That's regression in 9.0

**Comment by Sannis** [comment]
It is very strange because stylus have ignore for `{` and `}` from the beginning.

**Comment by Sannis** [comment]
In 8.9.0:
![screen shot 2016-01-06 at 17 45 38](https://cloud.githubusercontent.com/assets/77367/12145114/5b84e7f4-b49d-11e5-9dd3-afcaeb1bdedf.png)

WAT?
![screen shot 2016-01-06 at 17 46 34](https://cloud.githubusercontent.com/assets/77367/12145138/763aed6e-b49d-11e5-8081-9360323e7d66.png)

**Comment by Sannis** [comment]
Master:
![screen shot 2016-01-06 at 17 48 29](https://cloud.githubusercontent.com/assets/77367/12145168/b93e231a-b49d-11e5-8134-bcf0bdf05083.png)

![screen shot 2016-01-06 at 17 48 52](https://cloud.githubusercontent.com/assets/77367/12145179/c9ae9310-b49d-11e5-80b3-c9ff49586235.png)

**Comment by Sannis** [comment]
Works fine for me in master. Can you host any example of wrong highlighting?

**Comment by puzrin** [comment]
I have no more examples except from the first post. Found those by accident.

**Comment by puzrin** [comment]
Or do you mean you can not reproduce those?

**Comment by puzrin** [comment]
[example](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%60%60%60stylus%5Cn.hljs-chunk%5Cn%20%20color%20%23aaa%5Cn%60%60%60%5Cn%5Cn%60%60%60stylus%5Cn.hljs-chunk%5Cn%20%20color%20%23aaa%3B%5Cn%60%60%60%5Cn%5Cn%60%60%60stylus%5Cn.hljs-chunk%5Cn%20%20color%3A%20%23aaa%5Cn%60%60%60%5Cn%5Cn%60%60%60stylus%5Cn.hljs-chunk%20%7B%5Cn%20%20color%3A%20%23aaa%5Cn%7D%5Cn%60%60%60%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D)

Hm... that's strange, but i can't reproduce initially reported problem in browser. The only difference now is that content of { ... } is highlighted not as stylus.

**Comment by puzrin** [comment]
I updated demo to 9.1.0 and fixed some bugs. Report from the first message is actual.

[example](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%60%60%60stylus%5Cn.hljs-chunk%5Cn%20%20color%20%23aaa%5Cn%60%60%60%5Cn%5Cn%60%60%60stylus%5Cn.hljs-chunk%5Cn%20%20color%20%23aaa%3B%5Cn%60%60%60%5Cn%5Cn%60%60%60stylus%5Cn.hljs-chunk%5Cn%20%20color%3A%20%23aaa%5Cn%60%60%60%5Cn%5Cn%60%60%60stylus%5Cn.hljs-chunk%20%7B%5Cn%20%20color%3A%20%23aaa%5Cn%7D%5Cn%60%60%60%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D)

Highlighter call code is [here](https://github.com/markdown-it/markdown-it/blob/master/support/demo_template/index.js#L24-L46), seems correct.

**Comment by isagalaev** [comment]
Ah… A live example makes it clear :-) 

The main problem is that it uses a CDN-hosted build of highlight.js that supports only a handful of languages and Stylus is not among them. You could either [download a custom version][d] that does include Stylus or add `<script src="<cdn-path>/languages/stylus.min.js"></script>` after the main script.

There's also another minor problem, only tangentially related to the main issue: the language specified in markdown fenced code blocks doesn't show up in the generated HTML markup (it's simply `<code>..</code>`, no classes). But it shouldn't affect this particular case as I believe language detection would work here.

**Comment by puzrin** [comment]
@isagalaev i've already [included stylus rule](https://github.com/markdown-it/markdown-it/blob/master/support/demo_template/index.jade#L18), you can check in demo source.

Also, as you can see from source, i check language explicitely and don't use autodetect at all. https://github.com/markdown-it/markdown-it/blob/master/support/demo_template/index.js#L30

So, i think demo is correct, and it highlight language specified by user if available. If not - it fallbacks to plain code block.

**Comment by puzrin** [comment]
Updated demo again:

- More languages (except very rare & fat).
- Debug info: language class + console messages.
- Special `auto` name to guess language.

I think now it's ok for any checks.

**Comment by isagalaev** [comment]
Sorry, I've got a completely wrong idea about how your demo works… I thought it was being called on the browser side using the stock browser build. I've also misunderstood what @Sannis was talking about.

Anyway. Stylus indeed lists `{`, `}` and `;` as illegal characters (and always had)[1][]. It only affect the auto-detecting case, where you're guaranteed to never get "stylus" if the source has these characters at top level. However if you explicitly specify the language, it'll work and those symbols will be ignored. Presence or absence of css.js should not have any effect on this.

But since those symbols are legal in Stylus, I'll remove them from illegals.

[1]: https://github.com/isagalaev/highlight.js/blob/master/src/languages/stylus.js#L334

**Comment by puzrin** [comment]
> However if you explicitly specify the language, it'll work and those symbols will be ignored.

May be i don't understand something, but example above shows that explicit language doesn't work too with `{`, `;`, `}`.

**Comment by isagalaev** [comment]
Oh, I see that you call `hljs.highlight()` a bit differently from what I expected. A third parameter to the function — `ignore_illegals` — actually controls this behavior. Since you omit it, it doesn't evaluate to a truthy value, illegals are respected and highlighting stops on those symbols. Highlight.js itself always passes `true` explicitly when on a specified language path.

But that's beside the point anyway, we just have to fix stylus.js to not break on correct Stylus code.

**Comment by puzrin** [comment]
Thanks a lot for the tip! Updated demo with that flag. Now mush better.

**Comment by isagalaev** [comment]
Okay, should work now with auto-detection too.

@puzrin thanks for the assistance in the bug hunt!
