### ISSUE TITLE
Highlightjs could do a better job for patches

### ISSUE THREAD

**Issue by yurivict** [isagalaev/highlight.js#1029]
Please look at this patch in Phabricator: https://reviews.freebsd.org/differential/diff/11400/?revisionID=4603

It is .mk file, therefore all changed by patch areas are in 'make' syntax. Additionally, make's targets are in the 'shell' syntax.

Phabricator knows all this. And highlightjs only shows the added lines in green.

**Comment by Sannis** [comment]
Hightlight.js preserve custom markup, so this can be done by add-on that will wrap any changed line into span.

**Comment by isagalaev** [comment]
Yeah, this is way out of scope for a highlighter. The way it could work is by using highlight.js inside some dedicated diff viewer to highlight syntax but we're not going to become a diff viewer itself.
