### ISSUE TITLE
Document continuations usage

### ISSUE THREAD

**Issue by redixin** [isagalaev/highlight.js#1030]
Im trying to highlight code line by line using `continuation=true`:
```javascript
var data = [
    "# some comment",
    "def main(args):",
    "    pass"
];

for(var i=0; i<data.length; i++) {
    var data = hljs.highlight("python", data[i], true, true);
    console.log(data);
}
```
But got an error `TypeError: k is undefined`
Here is sample html page with script above: https://rally-ci.tk/stuff/gerrit/test.html
The same in Firefox-42.0 and Iceweasel-38.4.0

**Comment by Sannis** [comment]
First that I catch - you rewrites data variable with input inside loop.
Second - you should pass continuation data from first call to next ones.

**Comment by redixin** [comment]
It works in this way:
```javascript
var data = [
    "# some comment\n",
    "def main(args):\n",
    "    pass\n"
];
var stack = null;

for(var i=0; i<data.length; i++) {
    var retval = hljs.highlight("python", data[i], true, stack);
    stack = retval[3];
    console.log(retval);
}
```
Docs are okay.
