### ISSUE TITLE
Performance regression in 9.0.0

### ISSUE THREAD

**Issue by pkaminski** [isagalaev/highlight.js#1031]
I'm seeing seemingly arbitrary bad performance in version 9.0.0.  Here's one minimal test case I've isolated so far:  https://jsfiddle.net/h58e2kvq/2/.  This takes ~18 seconds to run on my machine, but if you replace `AbstractCmrDataProcessor` with `Bar` it's nearly instantaneous.

I'm not sure yet if the regression affects other constructs or languages as well.

**Comment by Sannis** [comment]
```java
public class DefaultDataDaoImpl {
  private List<AbstractCmrDataProcessor> cmrDataProcessors;
}
```

**Comment by Sannis** [comment]
@pkaminski thanks for reporting this!
