### ISSUE TITLE
Save user chosen bundles

### ISSUE THREAD

**Issue by cecekpawon** [isagalaev/highlight.js#1035]
Could you please add like little snippets below to official download page, to save user chosen bundles?

```js
var key = "hljsbundle", hljsbundle = JSON.parse(localStorage.getItem(key)) || {};
$("#download-form input[type='checkbox']").each(function(){
  var propname = $(this).prop("name");
  if (!hljsbundle.hasOwnProperty(propname)) {
    hljsbundle[propname] = $(this).prop("checked") ? 1 : 0;
  }
  $(this)
    .prop("checked", (hljsbundle[propname] === 1))
    .click(function(){
      hljsbundle[propname] = $(this).prop("checked") ? 1 : 0;
      localStorage.setItem(key, JSON.stringify(hljsbundle));
    });
});
```

**Comment by Sannis** [comment]
@isagalaev AFAIK this is in separate repository that only you have access to?

**Comment by isagalaev** [comment]
Just to clarify: it simply maintains the state of all the checkboxes between page loads, right?

**Comment by cecekpawon** [comment]
Yes @isagalaev, for [download page](https://highlightjs.org/download) only. I made [userscript](https://gist.github.com/cecekpawon/58ea11808f0c0b8ff160) for test. And sorry i dont know where to put this, hope this might be useful

**Comment by isagalaev** [comment]
Finally got to this issue. Fixed. Thanks for the script!
