### ISSUE TITLE
Block Title feature similar to Alex Grobatchev's syntaxhighligter

### ISSUE THREAD

**Issue by d-adamkiewicz** [isagalaev/highlight.js#1038]
Hi, I'm currently using highlight TiddlyWiki plugin, which is very good but I'm missing
this feature (or similar).

I need to assign title (some text to descibe) to a block of code and display it at top of the block.

Regards
Darek

**Comment by isagalaev** [comment]
Could you simply add anything at the top of a code block? I mean, how is this related to syntax highlighting?

**Comment by d-adamkiewicz** [comment]
Well, at first I thought to use /* */ metadata section in code block but I'm often dealing with json files, JSON format doesn't allow any comments section. So in my opinion it could help if I could pass and display some metadata outside actual code but attached to code block - this way I could easily reorganise code blocks on pages. If such thing doesn't exist nor it's easily implementable (+ I'm one and only who needs it) ... just forget about it.

**Comment by Sannis** [comment]
IMO this is better to do in that plugin. According to http://tiddlywiki.com/plugins/tiddlywiki/highlight/ it supports language as a parameter:

```
```javascript
(function(a,b){
    var result = a+b;
    return result;
})(10,20)
```

It should be simple to support something like this:
```
```javascript "Title"
(function(a,b){
    var result = a+b;
    return result;
})(10,20)
```

**Comment by isagalaev** [comment]
I still don't get it why any markup outside of the code block should be done by some special syntax when we have the whole of HTML (or markdown, or whatever) to do this. I mean, what's wrong with this:

```html
<p class="title">Example 1</p>
<pre><code>...</code></pre>
```

Or if you want to get fancy:

```html
<figure>
  <figcaption>Example 1</figcaption>
  <pre><code>...</code></pre>
</figure>
```

And if it's indeed happens in markdown and you don't want to use raw HTML for some reason, the best way to support this would be an extension to markdown, not to the highlighting plugin.

**Comment by isagalaev** [comment]
Closing as there's no clear reason to add the feature.
