### ISSUE TITLE
P: Build package on "postinstall"

### ISSUE THREAD

**Issue by tenbits** [isagalaev/highlight.js#1040]
Hallo Team,

I have created the `Highlight.js` wrapper [package](https://github.com/tenbits/highlight.js-postbuild) for [`npm`](https://www.npmjs.com/package/highlight.js-postbuild) and [`bower`](http://bower.io/search/?q=highlight.js-postbuild) which gets build with desired languages on `postinstall`

Features:
1. Standalone build script with no dependencies.
2. Application's `packages.json` or `bower.json` defines the required languages - [demo](https://github.com/atmajs/compo-highlight.js/tree/master/examples)

What do you think about this? It would be nice to get merged the `postinstall` flow into the main `highlight.js` package. Otherwise, if you want, I can add you to the repository and package maintainers.

Cheers, Alex

**Comment by isagalaev** [comment]
Hi! Sorry for delayed response. 

We try to keep any packaging-related code in highlight.js to a minimum as there are too many solutions out there right now, and this is not something we'd like to get busy with. We encourage third-party maintainers to create and maintain their own downstream packages.
