### ISSUE TITLE
TypeScript breaks on decorators

### ISSUE THREAD

**Issue by harangue** [isagalaev/highlight.js#1042]
```typescript
import {Component, View, bootstrap, NgFor, NgIf} from 'angular2/angular2';
...
@View({
  template: `
    <p>My name: {{ myName }}</p>
    <p>Friends:</p>
    <ul>
      <li *ng-for="#name of names">
        {{ name }}
      </li>
    </ul>
    <p *ng-if="names.length > 3">You have many friends!</p>
  `,
  directives: [NgFor, NgIf]
})
class DisplayComponent {
  ...
}
class FriendsService {
  names: Array<string>;
  constructor() {
    this.names = ["Aarav", "Martín", "Shannon"];
  }
}
```
I'm attempting to highlight this snippet from the new Angular 2 documentation, where TypeScript highlighting is an option. Unfortunately the @ symbol which represents a decorator breaks the syntax highlighting.

**Comment by Sannis** [comment]
![screen shot 2016-01-06 at 16 28 40](https://cloud.githubusercontent.com/assets/77367/12143551/936aa18c-b492-11e5-87b1-7e225c91ff50.png)

It looks reasonable for me, except that we can brush decorators like other meta things.

**Comment by harangue** [comment]
My highlighting is completely broken until I remove the decorators for some reason. I'm running the latest version.

**Comment by isagalaev** [comment]
@harangue could you show an example where it doesn't work? Like @Sannis I can't reproduce the problem. I *suspect* though that it might be cause by mis-detection or even the absence of TypeScript definition in your copy of highlight.js, but I can't be sure.

**Comment by harangue** [comment]
@isagalaev As I said upgrading to the most recent version of highlight fixed it for me. :) (I was using Hexo, which uses an out of date version, though I wasn't aware of that when I posted this issue).

**Comment by isagalaev** [comment]
Ah, okay then!
