### ISSUE TITLE
Release 9.1

### ISSUE THREAD

**Issue by Sannis** [isagalaev/highlight.js#1043]

**Comment by Sannis** [comment]
Started: 2016-01-06 06:59:24
Finished: 2016-01-06 07:00:14
Status: succeess

**Comment by isagalaev** [comment]
@Sannis uhm… Great it worked but why a week early? I was about to squash some bugs before next Tuesday…

**Comment by Sannis** [comment]
It looks I've failed to count weeks when creating 9.1 milestone :-1:

**Comment by isagalaev** [comment]
I have a recurring event every 6 weeks in my calendar — very reliable :-) Next one is February 23.
