### ISSUE TITLE
Do live demo more interactive

### ISSUE THREAD

**Issue by puzrin** [isagalaev/highlight.js#1044]
It would be nice to allow user type own samples to highlight. That will help to test and report problems.

Something like this: [example](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%60%60%60stylus%5Cn.hljs-chunk%5Cn%20%20color%20%23aaa%5Cn%60%60%60%5Cn%5Cn%60%60%60stylus%5Cn.hljs-chunk%5Cn%20%20color%20%23aaa%3B%5Cn%60%60%60%5Cn%5Cn%60%60%60stylus%5Cn.hljs-chunk%5Cn%20%20color%3A%20%23aaa%5Cn%60%60%60%5Cn%5Cn%60%60%60stylus%5Cn.hljs-chunk%20%7B%5Cn%20%20color%3A%20%23aaa%5Cn%7D%5Cn%60%60%60%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D)

**Comment by isagalaev** [comment]
In open source suggesting a feature usually equals to volunteering to implement it. Are you? :-)

**Comment by puzrin** [comment]
Not sure that can switch my brain for this task from another projects, sorry.

**Comment by isagalaev** [comment]
That's where this adage comes from: everyone's time and attention is limited, so an idea without implementation is not even worth little, but many times it's a net negative for a project. So there's no point in having it as an open but in-actionable ticket.

**Comment by Sannis** [comment]
I will, but we need to open-source site builder code.

**Comment by isagalaev** [comment]
@Sannis the demo is generated by the build process, the site doesn't do anything to it.
