### ISSUE TITLE
css breaks on base64-encoded images in backgrounds

### ISSUE THREAD

**Issue by bcherny** [isagalaev/highlight.js#1048]
```text
```css
element {
	background-image: url(data:image/png;base64,TWFuIGlzIGIG5vdCBvbmx5=);
}
\```
```

the whole rule fails to highlight at all. the issue is the `;` in the `url()`.

this seems to be the problematic line, but i'm not sure how to make a non-intrusive fix- https://github.com/isagalaev/highlight.js/blob/caec50381bb833abdcb109396fc8843ec115a999/src/languages/css.js#L9

**Comment by isagalaev** [comment]
It can be fixed by defining a mode for functions beginning with `/\w+\(/` and ending with `\)` and putting withing a rule so it would eat everything between parens. If you'd like to try the fix — please do go ahead! Or some one of the core team will get to it eventually.

**Comment by bcherny** [comment]
i'll take a stab at it. the line i linked seems to say "an attribute ends with a ;". so even if i put a rule matching `url(...;...)` in that rule's contains clause, the parent will see a ";" and match the end of the line. should the `url()` rule go elsewhere?

**Comment by bcherny** [comment]
nevermind, got it! will put up a pr soon.

**Comment by isagalaev** [comment]
Yeah, "contains" is always matched before "end", that's how sub-modes take over lexing.

**Comment by bcherny** [comment]
done! https://github.com/isagalaev/highlight.js/pull/1049
