### ISSUE TITLE
Stop adding ="" to html attributes without values

### ISSUE THREAD

**Issue by chrisfay** [isagalaev/highlight.js#1058]
How do I configure so that this:

&lt;foo bar&gt;&lt;/foo&gt;

...doesn&apos;t become this after it&apos;s ran through highlightjs:

&lt;foo bar=&quot;&quot;&gt;&lt;/foo&gt;

**Comment by isagalaev** [comment]
There's no configuration option for that, it's a side effect of merging the markup produced by highlighting with the markup that's been in place before highlighting. But why is this a problem?

**Comment by chrisfay** [comment]
Well in this case, the attributes do not use values, simply existing instructs an Angular component to behave a certain way. In my documentation, where I'm using HighlightJS to explain the component API, the attributes have ="" appended and while it doesn't hurt anything for the user to include it, it's unnecessary and may potentially imply they need to add values. 

It would be great to support highlighting valueless attributes without appending ="".

**Comment by isagalaev** [comment]
Sorry, I still don't understand how exactly this problem manifests itself :-) Those attributes can only appear on the generated HTML markup, not on the code that's visible on the page. So if you have something like:

```html
<pre><code>
return <blink attr>true</blink>;
</code></pre>
```

it will become this:

```html
<pre><code>
<span class="hljs-keyword">return</span> <blink attr=""><span class="hljs-literal">true</span></blink>;
</code></pre>
```
Anything that shows up on the page should never be affected by highlight.js. Could you show what your *markup* looks like before and after highlighting? And how do you actually call hljs?

**Comment by chrisfay** [comment]
Sure, I'm using angular-highlightjs
<https://github.com/pc035860/angular-highlightjs>.

Source code passed to angular-highlightjs
[image: Screen Shot 2016-02-02 at 12.57.39 PM.png]
Rendered markup via highlightjs
[image: Screen Shot 2016-02-02 at 12.57.31 PM.png]
I'd like the output to remain <foo bar></foo>. Is this what you're asking
for?
Chris

On Tue, Feb 2, 2016 at 12:53 PM Ivan Sagalaev <notifications@github.com>
wrote:

> Sorry, I still don't understand how exactly this problem manifests itself
> :-) Those attributes can only appear on the generated HTML markup, not on
> the code that's visible on the page. So if you have something like:
>
> <pre><code>
> return <blink attr>true</blink>;
> </code></pre>
>
> it will become this:
>
> <pre><code>
> <span class="hljs-keyword">return</span> <blink attr=""><span class="hljs-literal">true</span></blink>;
> </code></pre>
>
> Anything that shows up on the page should never be affected by
> highlight.js. Could you show what your *markup* looks like before and
> after highlighting? And how do you actually call hljs?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/isagalaev/highlight.js/issues/1058#issuecomment-178786505>
> .
>
-- 
Chris Fay
http://www.chrisfay.net
chrislfay@gmail.com

**Comment by isagalaev** [comment]
It may be that the problem is specific to angular-highlightjs. If you were using plain highlight.js in HTML then you'd have to escape your HTML to have it displayed (and highlighted) literally:

```html
<pre><code>&lt;foo bar&gt;&lt;/foo&gt;</code></pre>
```

Otherwise HTML would treat that "foo" as an actual tag. It looks like Angular does this escaping for you and I suspect that it may be where those spurious `=""` get introduced. I suggest asking maintainers of angular-highlightjs, they should have a better idea about this.

**Comment by chrisfay** [comment]
That makes sense. I'll reach out there, ty!
