### ISSUE TITLE
Erlang syntax highlight

### ISSUE THREAD

**Issue by jonasrichard** [isagalaev/highlight.js#1059]
Line comment doesn't seem to be handled properly. It regards the next lines as comments. Sometimes it doesn't work for a new comment.

http://www.jonasrichard.com/2016/01/templating-with-erlydtl-1.html

<img width="544" alt="screen shot 2016-01-24 at 18 16 33" src="https://cloud.githubusercontent.com/assets/783173/12537726/9895cee2-c2c6-11e5-9772-2c06054842f3.png">

**Comment by isagalaev** [comment]
You're using the CDN hosted version of highlight.js which only contains a limited set of languages, and Erlang is not one of them. So what you're seeing is the result of highlighting with a different language (Ruby in this case).

To include Erlang on your page either add a separate language module (`<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.1.0/languages/erlang.min.js"></script>`) or [download a custom package] with all the languages you need.

Then it should look like this: 
![screenshot from 2016-01-24 16 02 51](https://cloud.githubusercontent.com/assets/99931/12539994/fc6dd9fe-c2b3-11e5-87f6-e08258d8ce43.png)


[1]: https://highlightjs.org/download/

**Comment by isagalaev** [comment]
By the way, the Atelier-* family of styles uses only very slightly lighter color for comments for some reason.
