### ISSUE TITLE
p keyword in SQL

### ISSUE THREAD

**Issue by jseminck** [isagalaev/highlight.js#1063]
I recently upgraded highlight.js version from 8.4 to latest version and noticed one small regression between our highlighting: the stand-alone letter p is now recognised as a key word. For example in the following query:

`SELECT p FROM pets p`

I went through the changelog and saw that it was added in version 8.7, probably under one of the following changes:

* Oracle keywords added to SQL language definition by Vadimtro
* Postgres keywords added to SQL language definition by Benjamin Auder

Not sure if " p " is actually a keyword or if it's a bug...

**Comment by isagalaev** [comment]
Hm… That sure looks strange. Along with things like `acc acce accep accept` and some other one-letter keywords. @Vadimtro could I bother you to shed some light on it? It was added in c915a19a.

**Comment by Sannis** [comment]
Thanks my fault in review :-( I think we can simply remove all one-char keywords from that list and moderate all other short keywords.

**Comment by isagalaev** [comment]
@Sannis can you take this on then?

**Comment by Sannis** [comment]
@isagalaev sure.
