### ISSUE TITLE
`<` sign rendered as beginning of new HTML element

### ISSUE THREAD

**Issue by kawa-marcin** [isagalaev/highlight.js#1066]
I've been looking online and checked the documentation, but I found nothing on this issue.

It might be no issue though. I'm placing the C++ code inside the 
```
<pre>
    <code>
        #include <stdio.h>
    </code>
</pre>
```

And in the HTML it's rendered as
```
#include
```
and when inspect the code it looks like the new HTML element is created
```
<span class="hljs-meta">
    #
    <span class="hljs-meta-keyword">include</span>
</span>
<stdio.h></stdio.h>
```

Am I doing something wrong? Any help would be appreciated.
Thanks

Browser: Chrome Version 47.0.2526.73 (64-bit)

**Comment by isagalaev** [comment]
You need to escape `<` and `>` as `&lt;` and `&gt;` if you want them displayed literally. It's how HTML works, otherwise those are treated as regular tags.

**Comment by kawa-marcin** [comment]
Omg, that was stupid. Thanks for help.

**Comment by Guang1234567** [comment]
@isagalaev 

How about  add the feature like syntaxhighlighter?

```

Are you expecting

Map<String, String> v = new HashMap<String, String>();
but getting?

Map<string, string=""> v = new HashMap<string, string="">();
</string,></string,>
If the answer is yes, please don't file another html escape bug, read on.

If you are using <pre /> tags, unfortunately you have to replace all < characters with &lt;, otherwise browsers think you have unclosed HTML tags.

Your actual HTML code should be:

<pre class="brush: java">
Map&lt;String, String> v = new HashMap&lt;String, String>();
</pre>
or use the <script /> tag instead:

<script type="text/syntaxhighlighter" class="brush: java"><![CDATA[
Map<String, String> v = new HashMap<String, String>();
]]></script>
Please see Usage for more details on the subject.

```

**Comment by josx** [comment]
We pass over the same problem. But let me explain the user point of view:

- What i need to do? I want to hihgligth C++ code 
- Highlight.js detect text as C++ code ( what i am sending is C++ code)
- So I am expecting the C++ code highlighted

So I think in this use of cases We need to replace < and > with the html entities. 

What do you think? 
Is it worth it to do a PR with this feature?

**Comment by isagalaev** [comment]
This has nothing to do with the language. If you don't escape `<` and `>` the browser *doesn't treat them as part of your text*, it treats them as tags. And it happens before highlight.js even gets to work on it.

**Comment by josx** [comment]
Clearly I understand how to escape chars to html entities, but from my perspective if highlight.js forces to use <pre> tags in browser, it need to support out of the box this feature.

**Comment by isagalaev** [comment]
`<pre>` in HTML doesn't mean that text inside it will be auto escaped. This is in fact a common misconception. If highlight.js were to suddenly interpret tags inside `<pre>` literally, it would be a) quite surprising to people who do know how it works and b) would prevent people from having custom markup inside it. For example, right now you can do something like:

```html
<pre>
...
<span style="background: red"></span>
</pre>
```

That wouldn't be possible if we would autoescape it.

Also, you're supposed to pre-escape any text you want to put inside HTML anyway for security purposes. It would be really cumbersome to force people who do it do something like `if (it's a "pre" tag && highlight.js is active) { unescape text back }`.
