### ISSUE TITLE
Highlight keys in JSON with separate class

### ISSUE THREAD

**Issue by willium** [isagalaev/highlight.js#1074]
The pygments syntax highlighter gives a class to JSON keys so that different styling can be given to them. This can be seen with github itself. We're using highlight.js in tandem with pygments and would like to match the styles (only with JSON in our case). Therefore, getting a different class for the keys than the values in JSON with strings specifically.

Here's what it looks like in pygments
![image](https://cloud.githubusercontent.com/assets/356976/12790991/d8f27cc0-ca59-11e5-95f5-26256c3030e9.jpeg)

And here's highlight.js
![image](https://cloud.githubusercontent.com/assets/356976/12790996/de7e96ec-ca59-11e5-88d6-3356dde27f0d.jpeg)

**Comment by isagalaev** [comment]
JSON keys actually do have their own class, `.hljs-attr`, and can be styled separately from strings. Are you referring to a specific style from highlight.js package?

On a separate note, in many cases highlight.js styling can't be made to match another highlighter *exactly*. We lean toward less colorful highlighting than most other tools.

**Comment by willium** [comment]
You're right I guess it wasn't correct for our implementation. Is there any reason .hljs-attr doesn't include the surrounding quotation marks? It's a bit odd to color them for the values and not the keys, no?

**Comment by isagalaev** [comment]
No real reason, really. Probably because at first they didn't have their own markup at all, and nobody complained :-) I think changing it to be consistent with strings actually makes sense, I'll do it.

**Comment by willium** [comment]
Great! Thanks :)

**Comment by davis** [comment]
my keys are hljs-string instead of hljs-attr. what am i doing wrong? (using gitbook)

**Comment by isagalaev** [comment]
I would say it's an old version but in fact the keys in JSON never had "string" for class name. Probably gitbook does some modifications to it?

**Comment by davis** [comment]
@SamyPesse any idea if gitbook is using the latest highlight.js?
