### ISSUE TITLE
Reference lib/index.js file in package.json does not exist

### ISSUE THREAD

**Issue by tkrugg** [isagalaev/highlight.js#1077]
https://github.com/isagalaev/highlight.js/blob/master/package.json#L23

**Comment by isagalaev** [comment]
This file is generated during the [build process][] required to actually use the library. And this package.json serves as a template to generate a real one.

[build process]: http://highlightjs.readthedocs.org/en/latest/building-testing.html

**Comment by tkrugg** [comment]
so there is no way of using highlightjs on the server with a single `npm install`? do you need to build your own commonjs module and install it from your hard drive?
