### ISSUE TITLE
Scheme lambda function highlighting is incorrect

### ISSUE THREAD

**Issue by mkeeter** [isagalaev/highlight.js#1078]
In the snippet
```
(lambda (x y z) (+ y z))
```
`x` is highlighted as if it were a function call (instead of just an argument).

I can work around this by adding spaces around arguments, i.e.
```
(lambda ( x y z ) (+ x y))
```
but it would be nice if this were handled correctly.

**Comment by isagalaev** [comment]
Huh, good to know… Are there any other context beside `(lambda` where this is the case?

**Comment by mkeeter** [comment]
From a little more experimentation, the same mistake happens with quoted strings:
`'(1 2 3)` will highlight `1` in a different color from `2` and `3`

**Comment by isagalaev** [comment]
Thanks for spotting this too. We do handle quoting in generic Lisp syntax but not in Scheme for some reason.

**Comment by isagalaev** [comment]
Looks fixed?
![screenshot from 2016-02-16 13-07-19](https://cloud.githubusercontent.com/assets/99931/13091080/419fd5b6-d4ae-11e5-8976-cb7808643887.png)

**Comment by mkeeter** [comment]
Nice, thanks for the quick fix!

**Comment by isagalaev** [comment]
btw, we're going to release the new version in a week on February 23
