### ISSUE TITLE
useBR option doesn't work as expected

### ISSUE THREAD

**Issue by Alexhha** [isagalaev/highlight.js#1079]
Hello,

I have integrated highlight.js into dokuwiki and I can't use **pre** container.

``` html
<head>
<link rel="stylesheet" href="/lib/tpl/default/css/rainbow.css">
<script type="text/javascript" charset="utf-8" src="/lib/tpl/default/highlight.pack.js"></script>
<script>
   hljs.configure({useBR: true});
   $(document).ready(function() { $('div.hl_js').each(function(i, block) { hljs.highlightBlock(block); }); });
</script>
</head>
```

``` html
<div class="hl_js bash">
#!/bin/sh

clear_error_msg() {
        [ -z "$CONFTEST_OUTFILE" ] || rm -f "$CONFTEST_OUTFILE"
        CONFTEST_OUTFILE=
        APACHE2_INIT_MESSAGE=
}
</div>
```

With such settings I get the following [result](https://s3.amazonaws.com/scrstorage/44v8o5219i097v00.png)

If I remove `hljs.configure({useBR: true});` the result would be [something like that](https://s3.amazonaws.com/scrstorage/450462402h73m1.png)

Did I miss something?

Thanks in advance

**Comment by isagalaev** [comment]
You have to actually use `<br>` tags in your markup. The `useBR` option tells highlight.js to keep those in the output, not generate them.

**Comment by isagalaev** [comment]
To give you more context, this option was primarily intended to make highlight.js work with old forum software that displayed code with both `<br>`s and literal `\n`s intermixed. So we just try to keep the code formatted in the same way as it would be formatted by a browser without highlighting.

**Comment by Alexhha** [comment]
Oh, I got it. Sorry for disturbing
