### ISSUE TITLE
CSS hljs-attributte not updated

### ISSUE THREAD

**Issue by fcova** [isagalaev/highlight.js#1080]
I discovered that in the new version the css class for attributes changed from hljs-attribute to  hljs-attr, but   the css files still have the class hljs-attribute and don't have the new one. ( for example tomorrow.css)

**Comment by isagalaev** [comment]
Actually, 'attr' hasn't replaced 'attribute', they are both there with slightly different semantics. Quoting from the [class reference][]:

> **attr**: name of an attribute with no language defined semantics (keys in JSON, setting names in .ini), also sub-attribute within another highlighted object, like XML tag
> **attribute**: name of an attribute followed by a structured value part, like CSS properties

Many themes make a choice not to highlight "attr", which is okay. But "attribute" is important and as far as I know is defined everywhere (including tomorrow.css).

[class reference]: http://highlightjs.readthedocs.org/en/latest/css-classes-reference.html
