### ISSUE TITLE
Embedded javascript in HTML—language identification error

### ISSUE THREAD

**Issue by nicolasartman** [isagalaev/highlight.js#1082]
I did a search through the issues and looked for reporting guidelines but couldn't find anything, so apologies upfront of this is missing anything or has an obvious fix!

The following code block (with language html passed in) incorrectly identifies the embedded script block as actionscript rather than javascript (both ECMAScripts though, so I can see why). Per the HTML5 spec, any script tag lacking a `type` attribute should be considered Javascript, I think.

```html
<!-- index.html -->
<html>
  <head>
    <!-- Do _not_  rely on this URL in production. Use only during development.  -->
    <script src="//netflix.github.io/falcor/build/falcor.browser.js"></script>
    <script>
      var model = new falcor.Model({source: new falcor.HttpDataSource('/model.json') });

      // retrieve the "greeting" key from the root of the Virtual JSON resource
      model.
        get("greeting").
        then(function(response) {
          document.write(response.json.greeting);
        });
    </script>
  </head>
  <body>
  </body>
</html>
```

thanks!

**Comment by isagalaev** [comment]
Hi! Thanks for reporting that.

Incidentally, it has nothing to do with the script tag attributes or HTML spec: highlight.js doesn't work on that level. What's happening here is a heuristic mis-detection of the embedded script language. I'll see what we can do about it.

**Comment by isagalaev** [comment]
I've been able to fix this particular case. Note though that heuristics is inherently unreliable, and to explicitly set the language of a fragment you can constrain automatic detection to a particular set of languages:

```js
hljs.config({languages: ['xml', 'javascript']});
```

This works for the whole page, not the block.

**Comment by nicolasartman** [comment]
thank you!

Does that just set the _autodetection_ language? would it be possible to set that right before calling `.highlight` on a block of code, then _unset_ it right after?

I'm fine forcing js to be the only language embeddable in html snippets, but I'm making a tool that will be used across arbitrary tech stacks so I may need to highlight just about any given language.

**Comment by isagalaev** [comment]
Yes, setting/resetting the config would work (`hljs.config({languages: undefined})` to reset), though it feels a bit clanky. However, since you're making a general reusable tool you're ultimately at the mercy of quality of highlight.js detection anyway, and it will fail from time to time. Which may defeat the point of caring specifically about the HTML/JavaScript combination. But you're a better judge here.

**Comment by nicolasartman** [comment]
Awesome, thank you!

I think the chance users will want to embed coffeescript or actionscript in html examples is near 0, and I'll make a flag for it to disable the workaround if need be I think. That said, I'll wait a bit first and maybe the improved heuristics will make this a non issue.

**Comment by isagalaev** [comment]
Well, ActionScript have been added there in response to a real use case, you never know :-)

**Comment by nicolasartman** [comment]
you are absolutely right! Before yesterday, I didn't even know you _could_ embed actionscript in html :)
