### ISSUE TITLE
Windows batch scripts are mistaken for Perl scripts

### ISSUE THREAD

**Issue by dertuxmalwieder** [isagalaev/highlight.js#1084]
Highlight.js 9.1.0 insists that my [Vim build script](https://tuxproject.de/projects/vim/_compile.bat.php) needs to be highlighted as `perl`. Interestingly, using `<code class="dos">` makes it end up as `<code class="dos hljs perl">` instead.

**Comment by isagalaev** [comment]
You're using the CDN hosted version which only contains a handful of common languages and doesn't include dos.js. You can either [download a custom package][1] or add another `<script>` with a link to `<cdn path>/languages/dos.min.js`.

[1]: https://highlightjs.org/download/

**Comment by dertuxmalwieder** [comment]
Ouch! Thank you, that worked...

Is there a list of what you consider "common languages" available anywhere?

**Comment by isagalaev** [comment]
Those in the "Common" section at https://highlightjs.org/download/

**Comment by dertuxmalwieder** [comment]
Thanks.
