### ISSUE TITLE
Not sure if issue but, decimal number is detected as "hljs-selector-class"

### ISSUE THREAD

**Issue by iXshad0w** [isagalaev/highlight.js#1087]
Again i'm not sure if this is a bug but decimal numbers are detected as a class selector. I've noticed this in some Less css code 
`isnumber(7.4)`
The .4 gets a class "hljs-selector-class", i also noticed that it got detected as scss and when i manually changed this to less the problem got solved.
-> auto detect (scss) https://ss.retronix.nl/p/i/924.png
-> with less class https://ss.retronix.nl/p/i/923.png

**Comment by isagalaev** [comment]
Thanks for reporting this. Language mis-detection is still considered a bug, but not all of those are fixable because of the nature of heuristics. Sometimes setting a language is the solution :-) We'll look into this one anyway.

**Comment by iXshad0w** [comment]
I can imagine also due that less and scss are very similar :frowning:

**Comment by isagalaev** [comment]
That in itself shouldn't be a problem: they would just produce similar look. It's usually a matter of defining a rule preventing a certain token from appearing in a wrong context.

**Comment by iXshad0w** [comment]
You're the expert here ^_^ not gonna argue against that haha

**Comment by isagalaev** [comment]
Okay… Looks like the code on your screenshot is definitely not Less, and it's correctly not detected as such.

Something like this does work correctly, so there's probably no bug with numbers/classes:

```less
.selector {
  attr: isnumber(7.8%); // false
}
```

**Comment by iXshad0w** [comment]
i see, but still weird that this gets detected as scss then. 
[This post](http://dev.retronix.nl/post/2)
The first codeblock, i edited the source so it will autodetect.

**Comment by isagalaev** [comment]
In the absence of a strong signal heuristics will pick up eventually anything marginally higher than the rest, that's just how it works.

Anyway, based on the example in your post I've [fixed a few real bugs][1] with Less and now it successfully highlights (and detects) everything **up to the first `isnumber()`**. As I've mentioned, simply having `isnumber(...)` on its own (not inside selectors/rules) makes it invalid Less. 

[1]: 54e535d

**Comment by isagalaev** [comment]
So, I would suggest either splitting the example in two so those functions wouldn't spoil the valid Less above or wrapping them in some bogus rules to satisfy the parser. Does that work for you?

**Comment by iXshad0w** [comment]
I see, but splitting it will be inconvenient though, and i understand what u explained. so i will just add the class myself then that's not a problem i'd guess.

**Comment by isagalaev** [comment]
Yeah, it should probably look fine…
