### ISSUE TITLE
Highlight for html wrapper

### ISSUE THREAD

**Issue by dokxpi** [isagalaev/highlight.js#1088]
Inside highlight the container by 
`<!--highlight.js--><pre><code class="html"> ... </code></pre> `
placing the following code
```
<html>
<head>
<title>HTML структура документа</title>
</head>
<body>
<h3>Мой первый заголовок</h3>
<p>Мой первый параграф</p>
<p>Мой второй параграф</p>
</body>
</html> 

```
The output here get such a cake: http://dokxpi.github.io/knowhow/highlight/
What am I doing wrong? (sorry for my english)

**Comment by isagalaev** [comment]
Hi! You should escape `<` and `>` with `&lt;` and `&gt;` to make your HTML displayed literally. Otherwise they're just tags, and placing them inside `<code>` doesn't change that. It's how HTML works and highlighting has nothing to do with it actually.

P.S. Ваш английский вполне ясен :-)

**Comment by dokxpi** [comment]
@isagalaev Oh you are my hands, pens.

Isn't there any way to simplify this is not an easy process?
Can online-generator (in google not found) or a magic editor that would automatically/on the fly framed by the tags"<" " > " &lt; and &gt;?

P.S. Ну-ну.  Я бы предпочел "русский". :-)

**Comment by dokxpi** [comment]
Сan someone come in handy

Encode and decode a piece of text to its HTML equivalent
[HTML Entities Encoder / Decoder ](http://www.web2generators.com/html-based-tools/online-html-entities-encoder-and-decoder)

**Comment by isagalaev** [comment]
Highlight.js не делает автоматического экранирования, потому что это в большинстве случае делает тулза, которая генерирует HTML (markdown или какой-нибудь WYSIWYG-редактор). Написание HTML вручную встречается редко.

Кроме того, иногда внутри кода дейтсвительно используется реальная HTML-разметка: подсветить строку кода, сделать ссылку и т.п. Поэтому мы сохраняем и интегрируем 
то разметку вместе со своей.
