### ISSUE TITLE
If expression with less than (<) sign breaks kotlin highlighting

### ISSUE THREAD

**Issue by imagency** [isagalaev/highlight.js#1089]
I tested kotlin highlighting and found out that it stumbles upon "less than" sign (<) inside if() expression and wakes up only when meets another if() expression with "more than" sign (>).
Attaching screenshot.
<img width="357" alt="kotlin" src="https://cloud.githubusercontent.com/assets/11294532/13252679/c3a67ce4-da40-11e5-9942-e63e8152d0d3.png">

**Comment by isagalaev** [comment]
The screenshot alone doesn't tell us anything. Ideally, we'd need a live page showing this happening. Alternatively, please check those:
- The highlight.js package you're using does indeed contain Kotlin
- The language is either set explicitly or is correctly detected by checking the class of the DOM node containing the code

**Comment by imagency** [comment]
I used both ways to provide highlight.js with information about code language(explicitly and automatically detected). Both had this problem. Here is the link to look this behavior:
http://imbloger.ru/ru/article/330/test

**Comment by isagalaev** [comment]
Found the bug, fixed. Thanks for reporting that!

P.S. And please, please don't use screenshots to report bugs, they're totally uninformative :-)
