### ISSUE TITLE
Ruby: consider allowing `true` and `false` to be styled differently from `return`

### ISSUE THREAD

**Issue by monfresh** [isagalaev/highlight.js#1093]
In Ruby, it is common to see lines that contain `return true` or `return false`, such as:
```ruby
return false if location.mail_address.blank?
```
Notice how GitHub's syntax highlighting correctly styles `false` separately from `return`, whereas highlight.js treats them as the same type of keyword.

**Comment by isagalaev** [comment]
Thanks for catching this! This is one area where we have to be more consistent throughout.

**Comment by monfresh** [comment]
Thanks for the fast response and fix! Any idea when a new release will be posted?

**Comment by isagalaev** [comment]
Next one is planned on April 5 (we just had one released last Tuesday).
