### ISSUE TITLE
Bower support

### ISSUE THREAD

**Issue by jeremykentbgross** [isagalaev/highlight.js#1100]
It would be nice if there was a bower install for this project.  Ideally the bower install would already have normal and compressed/minified builds for the browser pre-built and included.

Just in case you are not familiar, bower is like npm but for browser side only packages: http://bower.io/

**Comment by Sannis** [comment]
This is a frequent request. Please see this [explanation why we don't do it within our own source][1]. And feel free to use a [Bower build of highlight.js from another repository][2].

[1]: https://github.com/isagalaev/highlight.js/issues/182#issuecomment-29251147
[2]: https://github.com/components/highlightjs

**Comment by Oxicode** [comment]
+1
