### ISSUE TITLE
Port `=>` functions from CoffeeScript to JavaScript

### ISSUE THREAD

**Issue by isagalaev** [isagalaev/highlight.js#1101]

**Comment by paulcpederson** [comment]
@isagalaev any progress on this? I poked around trying to figure out how to add this, but I'm not having any luck.

**Comment by isagalaev** [comment]
@paulcpederson I looked into it today, and there's enough differences for it to be more sensible to re-implement this in JavaScript, rather than just copy it over from CoffeeScript. Which I'll probably do shortly. However I should note that there's not much to gain from it in terms of highlighting: at the most there'll be a `<span class="params"></span>` around the argument list.

**Comment by paulcpederson** [comment]
thanks so much for looking into it, I really appreciate it 🌠
