### ISSUE TITLE
C highlighting error

### ISSUE THREAD

**Issue by leesei** [isagalaev/highlight.js#1104]
This is a Node.js app that illustrate the issue:

```js
var hljs = require('highlight.js');

var cppCodes = [
`
typedef long long ll;
ll ans = (sum(bit0, b) + b*sum(bit1, b)) - (sum(bit0, a-1) + (a-1)*sum(bit1, a-1));
`,
`
typedef long long ll;
ll ans = (sum(bit0, b) + b*sum(bit1, b));
`,
`
typedef long long ll;
ll ans = sum(bit0, b) + b*sum(bit1, b);
`
];

cppCodes.forEach((code) => {
  var result = hljs.highlight('cpp', code);
  console.log('=======================');
  console.log(result.value);
  console.log('=======================\n');
});
```

The first two code segments were not highlighted, only the third code segment is highlighted.

**Comment by isagalaev** [comment]
The actual problem is us wrongly recognizing `b*sum(bit1, b) ... ` as a function definition. Highlighting is suppressed in the first two fragments because of unbalanced parentheses which we try to parse as "parameters" (and `hljs.highlight()` is called without `ignore_illegals`) but it's only a consequence.

Thanks for reporting this!

**Comment by leesei** [comment]
Thanks for your prompt investigation.

**Comment by just-boris** [comment]
Got the same problem. My code is:
```cpp
a*pow((float) b, c)
```
Here is a [REPL](https://tonicdev.com/56d5c18e4b05fd0c00e89d94/56ea6fa8b8ed5112001121c0) where you can instantly check this out.

If I remove `a` or `(float)` casting, it will be ok. But all together doesn't work.

**Comment by just-boris** [comment]
rolled back to `8.7` and it worked.

**Comment by isagalaev** [comment]
I think I've fixed it. BTW, our next release is scheduled on coming Tuesday April 5.

**Comment by netcan** [comment]
`Status n(p.s, 0, p.g+1, H(p.s, e), id++, p.cid);` were not highlight.

**Comment by isagalaev** [comment]
> `Status n(p.s, 0, p.g+1, H(p.s, e), id++, p.cid);`

This one is most probably a duplicate of #1114. This will have to wait for a new parser :-)
