### ISSUE TITLE
"Show Language" label

### ISSUE THREAD

**Issue by kevinkucharczyk** [isagalaev/highlight.js#1108]
Would it be possible to add a label to the code sections, showing the reader what the language of the code is?

Basically, it would be great to have something like Prism's Show Language plugin for highlight.js: http://prismjs.com/plugins/show-language/

**Comment by isagalaev** [comment]
It's already possible in the same way it's done in that Prism plugin. All you have to do is run over all the highlighted fragments after highlighting happens:

```js
hljs.initHighlightingOnLoad();
addEventListener('load', function() {
  var blocks = document.querySelectorAll('pre code.hljs');
  Array.prototype.forEach.call(blocks, function(block) {
    var language = block.result.language;
  });
})
```
A few caveats to note:

- `result.language` is a lowercase code word, not a human readable title, so as with that Prism plugin, you'll have to define a mapping for those `{'javascript': 'JavaScript', 'cs': 'C#', ... }`
- Relying on language detection might bite you in a way that even if highlighting itself looks correct, the detected language might be different from the expected one (`let x = "something";` are equally highlighted as JavaScript and Rust, for example).

**Comment by isagalaev** [comment]
I'll go ahead and close it as it seems to be answered. Do feel free to re-open if you think we could/should do something to make such a solution easier.

**Comment by elgs** [comment]
```html
<div class="codeBlock javascript">
  <span class="label">Javascript</span>
  <pre><code class="javascript">
  class extends LWElement {
    name = 'Leanweb';
  }
  </code></pre>
</div>
```

```scss
.codeBlock {
  position: relative;
  .label {
    position: absolute;
    color: lightgray;
    right: 4px;
    top: 4px;
    font-size: 11px;
  }
}
```
![image](https://user-images.githubusercontent.com/55955/78357815-f40f9f80-7566-11ea-96c8-b461a54ae235.png)

**Comment by yyyc514** [comment]
That would be another way to get it done. :-)  I think the point here is how you'd do it programaticaly.

**Comment by elgs** [comment]
I was not able to get the label shown using the code in this thread. It would be great if you can show some working examples.

**Comment by yyyc514** [comment]
I see it in your snap, what is the issue you're having exactly?

**Comment by elgs** [comment]
I want to show the little language label on the top right corner. But I was not able find a working example. Google for highlight.js language label brought me here. @isagalaev in this thread mentioned it's done, and he showed some code snippet, but I was not able to get the label shown using his code.

**Comment by yyyc514** [comment]
Because his code is an example:

```js
hljs.initHighlightingOnLoad();
addEventListener('load', function() {
  var blocks = document.querySelectorAll('pre code.hljs');
  Array.prototype.forEach.call(blocks, function(block) {
    var language = block.result.language;
    // you need to use the DOM here to manipulate your HTML to add the label dynamically
  });
})
```

**Comment by elgs** [comment]
Oh, I see. Thanks for the explanation. I was hoping as a user, we could do something like this:
```javascript
hljs.highlightBlock(block, {showLanguageLabel: true});
```

**Comment by yyyc514** [comment]
I see no need for this to be a feature of the core library when it's easy to achieve with 5-10 lines of Javascript code outside the library, or even as a plugin.  This would great content for `plugin-recipes.rst` documentation though.  This is the kind of thing would be trivial to do with a plugin.

If you make a working https://jsfiddle.net/ for me I might be able to go provide you a working example.  It'd be great if you wanted to contribute that back to the documentation I mentioned earlier.

**Comment by yyyc514** [comment]
```js
addEventListener('load', function() {
  var blocks = document.querySelectorAll('pre code.hljs');
  Array.prototype.forEach.call(blocks, function(block) {
    var language = block.result.language;
    block.insertAdjacentHTML("afterbegin",`<label>${language}</label>`)
  });
})
```

Just one way.

**Comment by elgs** [comment]
https://jsfiddle.net/a79spbd0/

Thanks for the code example. It works!

**Comment by crpietschmann** [comment]
Here's a highlight.js plugin I wrote to do this for my own needs: https://github.com/crpietschmann/hljslanguagedisplayplugin
Feel free to use it. :)

**Comment by vUdav** [comment]
I use this method

```javascript
hljs.addPlugin({
  'after:highlightElement': ({ el, result }) => {
    const languageName = result._top.name;

    let languageDiv = Object.assign(document.createElement('div'), {
      className: 'hljs-language',
      innerText: languageName,
    });

    if (!el.parentElement.querySelector('.hljs-language')) {
      el.parentElement.insertBefore(languageDiv, el);
    }
  },
});
```
