### ISSUE TITLE
Can't add 'hljs' class to newly DOM after DOMContentLoaded

### ISSUE THREAD

**Issue by zywcode** [isagalaev/highlight.js#1110]
If DOM is created  after DOMContentLoaded, then it doesn't have a class called 'hljs'.

**Comment by isagalaev** [comment]
Your statement accurately describes reality but I have no idea how is it related to how highlight.js works. Could you describe what you want to happen?

**Comment by zywcode** [comment]
My English is not very good，express may not accurate, please forgive me.
I used angular.js, marked.js, angular-marked.js,highlight.js.
```
//ArticleDetailCtrl
angular.module("myApp").controller("ArticleDetailCtrl", ["$scope", "$stateParams",
    function ($scope, $stateParams) {
        //$scope.article = {
        //    title: "JavaScript代码规范与约束",
        //    username: "Woody",
        //    avatar: "https://dn-coding-net-avatar.qbox.me/1e784f4e-c5e5-402e-8828-a51f89d0d053.jpg?imageMogr2/thumbnail/80",
        //    createTime: new Date(),
        //    view: 892,
        //    like: 30,
        //    comment: 25,
        //    category: "JavaScript",
        //    content: "# marked test\n```js\n console.log('hello');\n```"
        //};
        (function () {
            $http.get("/api/blog/" + $stateParams.id).success(function (res) {
                $scope.article = res.data;
            }).error(function (error) {
                console.log(error);
            });
        })();
    }]);
<!--html snippet-->
<div class="article-detail-index article-item">
    <h4>{{article.title}}</h4>
    <div marked="article.content"></div>
</div>
```
My markdown data from ajax request, then marked.js render it. So the 'pre.code' dom dose not exists when initHighlighting method is invoked. So it didn't add hljs class on the dom.I want that lately 'pre.code' also has hljs class.That's all.

**Comment by Sannis** [comment]
To highlight such data you should use custom code, see https://github.com/isagalaev/highlight.js#custom-initialization. I hope Angular is good enough and have any callback that will be executed after template rendering.
