### ISSUE TITLE
Kotlin: keywords are old

### ISSUE THREAD

**Issue by temp-impl** [isagalaev/highlight.js#1113]
I read [kotlin.js](https://github.com/isagalaev/highlight.js/blob/5e9fa0a28d5904504bba185e22ce704d216f8096/src/languages/kotlin.js), I found that KEYWORDS are not enough and include deleted one.
(Kotlin had a lot of destructive changes.)

Now, Kotlin released 1.0.0, and JetBrains won't make more destructive changes, I think...

Missing keywords:
- interface
- annotation
- data
- abstract
- sealed
- internal
- infix
- operator
- out
- by
- constructor
- super
- this
- noinline
- crossinline
- dynamic - for Kotlin javascript

Deleted keywords:
- trait - changed to interface
- volatile, transient, native - changed to annotations (@Volatile, @Transient, @Native)
- default - changed to companion

I have just started Kotlin, so keywords may be not enough.

Thanks for adding "vararg"

**Comment by isagalaev** [comment]
Could you make a pull request with those changes? And may be update the demo snippet in test/detect/kotlin/default.txt if it doesn't look like up-to-date Kotlin?
