### ISSUE TITLE
\\1 Gives a wrong output

### ISSUE THREAD

**Issue by tomasibarrab** [isagalaev/highlight.js#1116]
I was making a syntax and when you use "\\\1" it gives you "\\`" in the output, but the bug is only with 1, with other numbers works great.

**Comment by tomasibarrab** [comment]
@isagalaev  can we check this please?

**Comment by isagalaev** [comment]
Could you be more specific, please? I've no idea what you're talking about :-)

**Comment by tomasibarrab** [comment]
When you use "\\1" in every language you get "\`" instead of "\\1", but when you use "\\2" or other number it gives you exactly that.

**Comment by isagalaev** [comment]
Use where? Are we talking about language definitions or highlighted snippets or something else?

**Comment by isagalaev** [comment]
In other words, tell me what exactly to do to reproduce it.

**Comment by tomasibarrab** [comment]
``` ruby 
puts \\1
puts \\2
```

Use this and see the output.

**Comment by tomasibarrab** [comment]
[quote]
```ruby
puts \\1
puts \\2
puts \\3
```
[/quote]

Use this and see the output.

**Comment by isagalaev** [comment]
Works for me, no backticks: https://jsfiddle.net/zock61nm/
Could you reproduce it in the jsfiddle or set up your own page somewhere showing the problem?

Which version of highlight.js are you using by the way?

**Comment by tomasibarrab** [comment]
The issue is in this repository, they´re using the version 9.2.0 actually, i think it's the latest.

https://meta.discourse.org/t/1-in-code-block-fails/39956

**Comment by isagalaev** [comment]
Well, looks like your assumption about it being a bug in highlight.js didn't prove to be correct (as show in the jsfiddle above, and can also be easily tested with highlight.js locally.) My bet would be that it *might* be cause by the markdown processor they use in Discourse. (But please do test it before filing a bug against the markdown library!)
