### ISSUE TITLE
C#: invalid highlighting of array variables

### ISSUE THREAD

**Issue by miere43** [isagalaev/highlight.js#1121]
This code doesn't render correctly:
```c#
int[] Test(string a);
```
This one produces this markup:
```html
<span class="hljs-keyword">int</span>[] Test(<span class="hljs-keyword">string</span> a);
```
I guess it should be this instead:
```html
<span class="hljs-function"><span class="hljs-keyword">int[]</span> <span class="hljs-title">Test</span>(<span class="hljs-params"><span class="hljs-keyword">string</span> a</span>)</span>;
```

More code samples that are incorrect:
```c#
int[] Test();
int[] somevar = new int[] { 0 };
```
```html
<span class="hljs-keyword">int</span>[] Test();
<span class="hljs-keyword">int</span>[] somevar = <span class="hljs-keyword">new</span> <span class="hljs-keyword">int</span>[] { <span class="hljs-number">0</span> };
```
This is from highlight.js developer tool:

![chrome_2016-03-21_13-44-08](https://cloud.githubusercontent.com/assets/3995549/13916357/30aadcc4-ef6b-11e5-8442-2b0546365c9e.png)

I would like to fix this myself, but I'm too scared of these parsing trees you guys have there.

Edit: broken here too
```c#
int[] Select(int[] options, string title, bool selectMany);
```

**Comment by isagalaev** [comment]
Should work now, thanks for reporting it!
