### ISSUE TITLE
No highlight on Vim script

### ISSUE THREAD

**Issue by rhysd** [isagalaev/highlight.js#1122]
### Repro

- Code

```javascript
var hljs = require('highlight.js');

var code =
`
let found = 0
for a in args
    if filereadable(a)
        found = 1
    endif
endfor
if !found
    echoerr 'No file included!'
endif
let conf = {'command': 'redpen'}
let redpen_conf = unite#sources#redpen#detect_config(expand('%:p'))
if redpen_conf !=# ''
    let conf.cmdopt = '-c ' . redpen_conf . ' 2>/dev/null'
endif
call quickrun#run(conf)
`;

var result = hljs.highlight('vim', code);
console.log(result.value);
```

- Output

```

let found = 0
for a in args
    if filereadable(a)
        found = 1
    endif
endfor
if !found
    echoerr 'No file included!'
endif
let conf = {'command': 'redpen'}
let redpen_conf = unite#sources#redpen#detect_config(expand('%:p'))
if redpen_conf !=# ''
    let conf.cmdopt = '-c ' . redpen_conf . ' 2&gt;/dev/null'
endif
call quickrun#run(conf)

```

Nothing looks highlighted :cry:

### Environment

- Highlight.js 9.2.0
- OS X 10.11.4
- Node.js 5.6.0

**Comment by isagalaev** [comment]
Thanks for reporting that. Looks like an incorrect illegal character somewhere, which we'll fix. As a temporary workaround call `hljs.highlight('vim', code, true)`: the `true` in the third argument will force it to ignore definitions of illegal characters and highlight anyway.

**Comment by rhysd** [comment]
@isagalaev 

Thank you such a quick response :relaxed: I'll use the workaround for now!

**Comment by isagalaev** [comment]
I'm not normally that quick, I just happen to have a weirdly upset schedule this week :-)

Actually, it'd be handy if you could help with this ticket, if you're feeling up for it. We use "illegal characters" to inform language detection heuristic about something that should never appear in a correct code. For Vim up to this point we had `{` and `:` as illegal, and your snippet has both of them, so we should lose those. Question is, can you think of a character or a sequence of character that could never appear in a Vim code (outside of strings and comments)?

**Comment by rhysd** [comment]
@isagalaev 

I sent a pull request.  Please see #1125.

**Comment by isagalaev** [comment]
As you can see, your pull request breaks the tests. It's because without illegals Vim definition becomes to eager and invades on other languages (C++ in this case), that's why I asked if you could come up with some other illegals :-)

**Comment by rhysd** [comment]
I'm not familiar with language definitions and internals of highlight.js, but I think `;` is available for illegal character in Vim script because it doesn't appear in Vim script syntax.

I fixed #1125.

**Comment by rhysd** [comment]
And added a test to ensure this issue was fixed.

**Comment by isagalaev** [comment]
Oh, `;` is indeed a very strong signal, it'll rule out a lot of C-like languages from being treated as Vim.

The markup test on Vim itself that you've added is not really necessary (and adds to maintenance burden), as it doesn't test any specific language feature of Vim. I understand what you've been trying to do with it and it should be a detection test instead, not a markup one (I can explain it in more details if you like!). The easiest way to do it would be to add a line containing `{` and `:` into the existing Vim detection snippet at test/detect/vim/default.txt. Could you do that so I could make a clean merge?

**Comment by rhysd** [comment]
> The markup test on Vim itself that you've added is not really necessary

Ah, I'm sorry.  I misunderstood the markup tests.

> The easiest way to do it would be to add a line containing { and : into the existing Vim detection snippet at test/detect/vim/default.txt. Could you do that so I could make a clean merge?

OK, I'll do that.

**Comment by rhysd** [comment]
I fixed again :smile:

**Comment by isagalaev** [comment]
Merged. Thanks a lot! I also just pushed one more fix to a different language (Gauss) that was causing mis-detection of your particular snippet. Pretty good improvement overall :-)
