### ISSUE TITLE
SQL: "id" and "name"

### ISSUE THREAD

**Issue by jseminck** [isagalaev/highlight.js#1123]
Hello,

Since 8.7.0 a lot of new keywords were added to highlight.js SQL highlighting. We are using this extensively and saw some regression issues after upgrading from 8.6.0: 

"id" and "name" for one are now recognised as keywords. I am not sure IF they are really keywords in any SQL software, but it causes regression issues in queries like:

**select**
   pets.**id**
   pets.**name**
   pets.other_columns
**from**
   pets

In this query, both "id" and "name" are incorrectly highlighted. The columns "id" and "name" are columns which are often used.

I think these words can remain keywords (if they really are) but there could be some extra logic to not mark columns as keywords? Not sure what is the best approach.

Also... there are too many keywords added since 8.7.0, I already raised an issue before about single letters (e.g. "a" 'b" "c" etc...). I think the list of words needs to be checked thoroughly.

**Comment by isagalaev** [comment]
I think we could make anything surrounded with dots to not be recognized as keywords. As for the list of words itself, we just need a volunteer who would agree on checking it. Would you be up for it?

**Comment by jseminck** [comment]
I could have a look at the list but I am afraid I do not have sufficient experience with various SQL server softwares (f.e. I don't use Oracle at all). I'll test the fix but it does sound like a good idea.

Thanks for the quick response!
