### ISSUE TITLE
Support "console" syntax

### ISSUE THREAD

**Issue by MoOx** [isagalaev/highlight.js#1126]
GitHub support a "console" keyword that reflect console commands/output.
It almost like shell (bash) but not really.

See this discussion https://github.com/MoOx/statinamic/pull/338

**Comment by isagalaev** [comment]
It's certainly nice to have, as bash is not adequate for this, but it'd take a volunteer to actually write a syntax definition. It's usually best when someone with a concrete usecase does this as they know exactly how the end result should look like. Would you be up for it?

**Comment by Lance0312** [comment]
Pygments has something called session lexers, such as bash session, tcsh session, powershell session, and etc. Might be helpful?
https://bitbucket.org/birkenfeld/pygments-main/src/859b2bce647cd212e39cd63f83f93f4083b232b2/pygments/lexers/shell.py?at=default&fileviewer=file-view-default#shell.py-172

**Comment by isagalaev** [comment]
Looks like @Sannis volunteered :-)

**Comment by isagalaev** [comment]
I suggest we don't nominate any milestone to this issue until it's actually started being implemented :-)

**Comment by XadillaX** [comment]
I need this too!

**Comment by MakeNowJust** [comment]
Wow, I just implemented `console` (also `shell-session`) in #1444. (even I hadn't known this issue 😄

**Comment by src386** [comment]
Is it still experimental ? `shell-session` does not seems to work with 9.9.0 (cdn).
Can't wait to use it :)

**Comment by MakeNowJust** [comment]
I think this issue can be closed because #1444 is merged.

**Comment by isagalaev** [comment]
Indeed. Thanks, @MakeNowJust!
