### ISSUE TITLE
code: ECONNRESET

### ISSUE THREAD

**Issue by Litaya** [isagalaev/highlight.js#1127]
It happened when I upload my article written offline  with several images.  MacOS.
![image](https://cloud.githubusercontent.com/assets/7345208/13945080/9479d446-f045-11e5-8f21-f36859149b5e.png)

**Comment by isagalaev** [comment]
How is this related to highlight.js?

**Comment by Litaya** [comment]
I'm so sorry about my useless question. It's a mistake. I'm so so so sorry...

**Comment by isagalaev** [comment]
Don't worry, it happens :-)
