### ISSUE TITLE
No result when calling initHighlighting.

### ISSUE THREAD

**Issue by Loceka** [isagalaev/highlight.js#1128]
Hello,

I ran into an issue when calling `hljs.initHighlighting();` : it did nothing at all.
With little debugging the cause is easy to find. The **querySelector** method is incorrectly used : `var e=document.querySelectorAll("pre code")` instead of `var e=document.querySelectorAll("pre, code")` (note the comma).

I don't know if it is related but I downloaded a "Custom package" by choosing *bash, css, html, xml, java, javascript, json, perl* and *sql*.

Just for the record, both your code and your packaging is amazing and easily customizable, thanks a lot for that!

**Comment by Sannis** [comment]
Can you please post HTML example? `"pre code"` works fine for me if I use markup from documentation:

```html
<pre><code class="javascript">
var e=document.querySelectorAll("pre code");
</code></pre>
```

**Comment by isagalaev** [comment]
`pre, code` finds both `<pre>..</pre>` and `<code>..</code>` tags, while `pre code` finds a combination of `<pre><code>..</code></pre>`. We're intentionally only looking for those combinations, we don't want to highlight non-code `<pre>` and sole inline `<code>` by default.

**Comment by isagalaev** [comment]
> I ran into an issue when calling `hljs.initHighlighting();` : it did nothing at all.

I'm only guessing here, but if you're calling it before the body of the page it won't work because there's nothing to highlight yet. That's why we recommend using `hljs.initHighlightingOnLoad()` which assigns highlighting to an event happening after all the page's content is loaded.

**Comment by Loceka** [comment]
My bad then.

I do use **<pre>** tags only in my HTML code and thought hljs should work both on **<pre>** and **<code>** tags, not on the combination of the two.

Not a bug at all then, sorry for misunderstanding the behaviour.

**Comment by isagalaev** [comment]
It's alright. You just need a short custom initialization code for your case querying only for `document.querySelectorAll('pre')`.
