### ISSUE TITLE
Docker/Dockerfile syntax not working

### ISSUE THREAD

**Issue by paolomainardi** [isagalaev/highlight.js#1134]
Test case: https://jsfiddle.net/3zwgob79/2/

As you can see using "language-docker" or "language-dockerfile" the code gets no highlighting, instead trying to use just "docker" or "dockerfile" the syntax used is "sql".

What am i doing wrong ? 

Thanks!

**Comment by sourrust** [comment]
The docker definition isn't included by default. You need to include that after the highlight.js file:

https://jsfiddle.net/3zwgob79/3/

**Comment by paolomainardi** [comment]
thanks a lot @sourrust !
Where can i find the automatic included syntaxes ?

**Comment by sourrust** [comment]
https://highlightjs.org/download/

Everything in the common section. They are also annotated in the language definitions in this repo but the site is the place that is conveniently listed out.

**Comment by paolomainardi** [comment]
thanks a lot again @sourrust
