### ISSUE TITLE
Request: BNF / EBNF

### ISSUE THREAD

**Issue by ronkorving** [isagalaev/highlight.js#1138]
Surprisingly missing from the list is [(Extended) Backus Naur Form](https://en.wikipedia.org/wiki/Extended_Backus%E2%80%93Naur_Form). Would be great to see support for that.

**Comment by isagalaev** [comment]
Yes, we do accept contributions: http://highlightjs.readthedocs.org/en/latest/language-requests.html

**Comment by Sannis** [comment]
@ronkorving can you please share some example of highlighting with us?
Are modes, strings and comments are enough for EBNF highlighting?

**Comment by ronkorving** [comment]
The link in my post takes you to the wiki page. While not a spec, it has plenty of examples and explanations. Now how it should be highlighted, good question. I don't think I've ever seen it yet myself.

**Comment by isagalaev** [comment]
@Sannis if you'd fancy doing it, reopen the ticket so it's not lost.

By the way, I'd say highlighting the left-hand side of a definition as "attribute" would make total sense.

**Comment by ronkorving** [comment]
Highlighting it as done on the wiki page itself would be a great start. And perhaps a great finish as well :) Maybe that's all that is needed.

**Comment by Sannis** [comment]
BNF looks simple t implement. EBNF is more difficult because there are no `<`, `>` and `::=` that can be used to boost relevance. Will start from BNF.

**Comment by ronkorving** [comment]
@Sannis Thanks, really appreciate it :)

**Comment by isagalaev** [comment]
The basic implementation is done, closing.

**Comment by ronkorving** [comment]
Awesome job :)
