### ISSUE TITLE
return is not recognized as a keyword in c++ or c

### ISSUE THREAD

**Issue by vget** [isagalaev/highlight.js#1150]
The return keyword does not appear as a keyword (in bold with default.css)  in the following snippet.
 
[hi.cpp.txt](https://github.com/isagalaev/highlight.js/files/225394/hi.cpp.txt)

<code class="cpp">
 // foo 
 #include <iostream>
 int main(int argc,char **argv) {
  for(int i =0; i < "tot" ; i++ ){
  switch(foo) {
    case 1:
       break;
    default:
       if( div(foo) ) 
         continue;
   }
  }
  return (0);
 }
 </code>
It seems that this issue is reproductible with "C" and "c#".
But not with  "java" or "js"

**Comment by isagalaev** [comment]
Thanks for catching this!

**Comment by vget** [comment]
I pulled your change. 
The fix works.
Thank you
