### ISSUE TITLE
Highlight bug on c++ when construct with param is a function call 

### ISSUE THREAD

**Issue by LFsWang** [isagalaev/highlight.js#1157]
test : https://tonicdev.com/leesei/highlightjs-test
copy from https://github.com/hexojs/hexo/issues/1902
```cpp
#include<iostream> //cpp
using namespace std;
mt19937 mt(rd());//broken
//abc aa(aa());    //broken as well
```

view
![image](https://cloud.githubusercontent.com/assets/7088579/14681589/4d698bac-0754-11e6-9b4f-309185a8f1ea.png)

```cpp
#include<iostream> //cpp
using namespace std;
mt19937 mt;
me.seed(rd()); //fine
```
view
![image](https://cloud.githubusercontent.com/assets/7088579/14681608/672ccd88-0754-11e6-9b51-f4ebbcedd7df.png)

**Comment by isagalaev** [comment]
Thanks for reporting it. This is the same problem as #1114. Unfortunately fixing it will take a while.
