### ISSUE TITLE
Backticks break highlighting.

### ISSUE THREAD

**Issue by dzearing** [isagalaev/highlight.js#1158]
![image](https://cloud.githubusercontent.com/assets/1110944/14763047/339000b6-093f-11e6-8833-6b6cdf594452.png)

**Comment by sourrust** [comment]
This example works fine on version 9+. You might want to update your version of highlight.js.

![](https://cloud.githubusercontent.com/assets/365596/14764829/4656e174-097b-11e6-9070-3974d9ac9c17.PNG)

**Comment by dzearing** [comment]
Thanks @sourrust 9.3.0. To clarify; this works it 'javascript' is specified as the language, but not 'typescript'.

**Comment by sourrust** [comment]
I can only reproduce this if the typescript definition is version 8.8.0 and below. Since typescript isn't apart of the default pack, you might want to check to see if you have the latest language definition of typescript.

**Comment by isagalaev** [comment]
@dzearing can you set up a page somewhere showing the error? I can't reproduce it either in any way. (Also for future, please don't post text only as a screenshot, it makes it unnecessarily difficult to re-type)

**Comment by leebenson** [comment]
Expressions within a template string don't seem to work:

Example:

```js
app.use(async (ctx, next) => {
  const start = ms.now();
  await next();
  const end = ms.parse(ms.since(start));
  const total = end.microseconds + (end.milliseconds * 1e3) + (end.seconds * 1e6);
  ctx.set('Response-Time', `${ total / 1e3 }ms` );
});
```

... prevents any highlighting:

<img width="964" alt="screen shot 2017-03-31 at 22 00 15" src="https://cloud.githubusercontent.com/assets/719722/24569315/73977d7a-165d-11e7-8ac1-35cb9595be7a.png">

But changing `${ total / 1e3 }ms` to `${total}ms` works:

<img width="940" alt="screen shot 2017-03-31 at 22 01 48" src="https://cloud.githubusercontent.com/assets/719722/24569371/acf68386-165d-11e7-8465-d3dbf698f050.png">
