### ISSUE TITLE
Any support coming for Jade/Pug?

### ISSUE THREAD

**Issue by insanetisane** [isagalaev/highlight.js#1159]
Looks like there is an old branch for jade support. Any plans for adding support?

**Comment by isagalaev** [comment]
It's a remnant of a [failed attempt][1] at implementing it. We actually should just delete this branch as it's abandoned.

https://github.com/isagalaev/highlight.js/pull/250#issuecomment-38774812

**Comment by isagalaev** [comment]
Just deleted the branch. We will happily accept a new one from anyone motivated enough to to that. A good way to start is the [Language definition giude](http://highlightjs.readthedocs.io/en/latest/language-guide.html).

**Comment by cekvenich** [comment]
Bump.
