### ISSUE TITLE
Markdown: reference syntax

### ISSUE THREAD

**Issue by zlargon** [isagalaev/highlight.js#1160]
![2016-04-27 2 11 00](https://cloud.githubusercontent.com/assets/2791834/14843352/0ceebf06-0c82-11e6-93ee-2fc8bcb9fe3f.png)

### Reference Syntax

```markdown
[1]: http://example.com
```

The highlight rule of reference syntax seems incorrect:

```html
[<span class="hljs-symbo">1</span><span class="hljs-link">]: http://example.com</span>
```

I expect it should look like this:

```html
[<span class="hljs-symbo">1</span>]: <span class="hljs-link">http://example.com</span>
```

https://github.com/isagalaev/highlight.js/blob/master/src/languages/markdown.js#L105-L108

How can I fix this problem?
Thanks.

**Comment by isagalaev** [comment]
Thanks for catching this. It was one of those problems without an obvious solution, so the way to fix it is to try different approaches until you find a working one that doesn't seem terribly hacky. So I just committed the fix :-)
