### ISSUE TITLE
Template literals with interpolated expressions break highlighting

### ISSUE THREAD

**Issue by RinkAttendant6** [isagalaev/highlight.js#1162]
This example works fine:
```js
var time = '09h00'
var msg = `I take the bus to work every day at ${time}`
```

However a slightly more sophisticated example with interpolated expressions does not work:
```js
var buses = [3, 2, 4]
var msg = `I rode on a total of ${buses.reduce((a,b) => a + b, 0)} buses over the course of ${buses.length} days`
```

Multi-line template literals that contain HTML code also seem to trip up the plugin:
```js
var row = `<tr>
        <td>Data</td>
        <td>More data</td>
    </tr>`;
```

Tried forcing it to TypeScript but it did not work. I am using version 9.0.3.

**Comment by isagalaev** [comment]
II can guess that you might be using a CDN-hosted version of highlight.js which only knows most common languages, not including TypeScript. If it's the case, TypeScript can be added separately (`<script src="<cdn-path>/languages/typescript.min.js"></script>`) or downloaded as a part of a custom package at https://highlightjs.org/download/.

**Comment by RinkAttendant6** [comment]
I actually want to use it with JavaScript... it isn't working with JavaScript or TypeScript

**Comment by isagalaev** [comment]
It does work with JavaScript too: https://jsfiddle.net/jqqqy764/
Could you describe your setup in details?
