### ISSUE TITLE
Support line independent output

### ISSUE THREAD

**Issue by rtfpessoa** [isagalaev/highlight.js#1167]
I am trying to highlight some code, and I want to output the lines separately.

I am giving a string to hljs which has the code lines appended with `\n` and after it gives me the output I split the generated html by `\n`.

This has a major problem because there are multi line elements, for example comments.

With my current approach it will only consider the first line of the comment.

To fix this, I would like to pass a separator char to hljs, in this case `\n` and then as soon as it would find this char it would close the pending tags and open them again for the next line.

Is this possible to implement on hljs? How hard it it?

Do you have any other suggestions on how to separate lines after the highlight?

**Example:**

* Currently:

```html
<span class="comment">
 /**
   * Write your comment here
   */
</span>
```

* Desired:

```html
<span class="comment">
 /**
</span>
<span class="comment">
   * Write your comment here
</span>
<span class="comment">
   */
</span>
```

**Comment by isagalaev** [comment]
There are two different solutions depending on what you need those separate strings for.

1. If all you want is to highlight code marked up as, say, an ordered list, you can safely highlight the `<ol>` element, and highlight.js would retain all those `<li>` intact.

2. If you need those individual strings for whatever else, you can highlight them individually, passing along the previous parsing state that `hljs.highlight()` returns as a part of result: 

```js
var source = ('int x = 0;\n' +
  '/* a comment\n' +
  'ends */\n' +
  'int y = 0;').split(/\n/);
var output = [];
var state;
for (var i = 0; i < source.length; i++) {
    var result = hljs.highlight('cpp', source[i], true, state);
    console.log(result);
    state = result.top; // this is the parsing stack
    output.push(result.value);
}
```
It will correctly reopen the comment in the middle.

**Comment by rtfpessoa** [comment]
I think that is exactly what I need. Is there any place where I can see some docs about thoose options and invocation alternatives?

I tried looking but I only saw either invoking line by line without state.

**Comment by isagalaev** [comment]
> Is there any place where I can see some docs about thoose options and invocation alternatives?

docs/api.rst or rendered at http://highlightjs.readthedocs.io/en/latest/api.html

**Comment by isagalaev** [comment]
I've noticed you're writing a diff viewer? :-) Be aware that this solution may still not be complete as you may be lacking necessary context in the diff itself (like, changing one line inside a huge comment).

**Comment by rtfpessoa** [comment]
@isagalaev thanks for the fast answer. I will take a look.

Regarding the diff context I am well aware of that part. Still highlight.js does a great job most of the time even with small or no context. :smile:

**Comment by rtfpessoa** [comment]
@isagalaev is it possible to invoke `highlight` on a DOM node like `highlightBlock`?

**Comment by isagalaev** [comment]
No, `highlight` is a low level API, it doesn't know anything about DOM. `highlightBlock` is, basically, an embodiment of the default case for highlight.js, it calls various low-level stuff in a very specific way and it's unlikely that any other code would need it in exactly the same way. Depending on what you need you can call all this low-level stuff yourself in the way you need. What's your use case?

**Comment by rtfpessoa** [comment]
The `value` that I have to pass to highlight is some html. It means that hljs should not escape it. And instead parse it like the block function does.

How can I go around this?

**Comment by isagalaev** [comment]
If you only need text from that node, then you can simply get `node.textContent`. If you want to retain the original markup, it's more complicated. The way we do it is we first highlight the text content and then [merge the result with the original markup][1]. These functions aren't exposed publicly as nobody ever needed that :-)
If you don't need to deal with arbitrary user markup but have instead some container structure that you yourself know, it would probably make more sense to reconstruct it manually after highlighting.

[1]: https://github.com/isagalaev/highlight.js/blob/master/src/highlight.js#L590-L595

**Comment by rtfpessoa** [comment]
I will look into that merge. I think is the best option. Even thought I will probably need to copy that code.

Maybe you can expose it in some future release.

**Comment by isagalaev** [comment]
Yes, I think we could simply expose both `nodeStream` and `mergeStreams` or may be devise a more high-level wrapper around them.

**Comment by rtfpessoa** [comment]
I was able to make it work perfectly here https://github.com/rtfpessoa/diff2html/issues/75#issuecomment-217749902

Please let me know when you expose those two methods in the public api.

Thanks a lot for your help, it was amazing 👍

**Comment by rtfpessoa** [comment]
Just another thing, I also needed to use `buildClassName` since it was not inserting the class names properly.
