### ISSUE TITLE
Excel formula syntax

### ISSUE THREAD

**Issue by ikhsan017** [isagalaev/highlight.js#1171]
Hi @isagalaev 

Thanks for such great syntax highlighter, btw, is there is any plan to add support for excel or any spreadsheet formula?

**Comment by isagalaev** [comment]
We don't have any plan, it's not how it works: http://highlightjs.readthedocs.io/en/latest/language-requests.html

**Comment by ikhsan017** [comment]
Thanks for the link, also, the language definition guide help me a lot :)

**Comment by pjpscriv** [comment]
To add a comment 5 years later for anyone else who finds themselves here, Excel formula are now supported. Go here: https://highlightjs.org/static/demo/, select language category **all** and search "Excel formula"
