### ISSUE TITLE
Bad highlighting of pattern alternatives in Rust

### ISSUE THREAD

**Issue by pkaminski** [isagalaev/highlight.js#1182]
When a match expression has more than one alternative pattern for a branch, only one of them is highlighted correctly, and highlighting of the corresponding branch expression may also be broken sometimes.  Example here: https://jsfiddle.net/tjggk3vL/2/

**Comment by isagalaev** [comment]
I've stumbled this bug too recently and fixed it in 882fd9b8de11c1.
