### ISSUE TITLE
npm package

### ISSUE THREAD

**Issue by wifiextender** [isagalaev/highlight.js#1185]
The npm package has wrong `Makefile` configuration:

Old configuration:

```make
VERSION=8.7

default: build
	@cp -f build/highlight.* .
	@cp -f highlight/src/styles/* styles
	@du -hs highlight.*

build: highlight
	@cd highlight && git fetch && git checkout $(VERSION)
	@cd highlight && npm install
	@mkdir -p build
	@cd highlight && node tools/build.js && cp build/highlight.pack.js ../build/highlight.pack.min.js
	@cd highlight && node tools/build.js -n && cp build/highlight.pack.js ../build/highlight.pack.js

highlight:
	@git clone git://github.com/isagalaev/highlight.js.git $@

clean:
	@rm -rf build

.PHONY: default
```

The new one:

```make
default: build
	@cp -f build/highlight.* .
	@cp -r highlight.js/src/styles .
	@du -hs highlight.js/*

build:
ifneq ($(wildcard highlight.js/.),)
	@cd highlight.js
else
	@git clone --depth=1 git://github.com/isagalaev/highlight.js.git
	@cd highlight.js && npm install
endif

	@mkdir -p build
	@cd highlight.js && node tools/build.js && cp build/highlight.pack.js ../build/highlight.pack.min.js
	@cd highlight.js && node tools/build.js -n && cp build/highlight.pack.js ../build/highlight.pack.js

clean:
	@rm -rf build

.PHONY: default build clean
```

If you want you can add cdn and browser builds.

**Comment by derhuerst** [comment]
Is the `Makefile` even necessary in the npm package? AFAIK @isagalaev said in https://github.com/isagalaev/highlight.js/issues/1169#issuecomment-217909259 that the published npm module just act as a distribution package.

**Comment by wifiextender** [comment]
The `Makefile` provides to the user a way to download and build the latest highlightjs (not the releases) without leaving the terminal once the library is installed. The building is not so flexible as building it manually though.

```bash
npm install highlightjs
node_modules/highlightjs/
make
```

**Comment by derhuerst** [comment]
The npm package should contain the pre-built (default) distribution files. Anything custom should be done via Git & build. In an effort to make npm packages as lightweight as possible, it is common not to bundle the build files & scripts.

**Comment by wifiextender** [comment]
This `Makefile` came with the npm package, all I did was to modify it and post it here.

```bash
-rw-r--r-- 1 frost frost     65 Aug  5  2015 .npmignore
-rw-r--r-- 1 frost frost   1498 Aug  5  2015 LICENSE
-rw-r--r-- 1 frost frost    543 Aug  5  2015 Makefile <--------
-rw-r--r-- 1 frost frost    320 Aug  5  2015 README.md
-rw-r--r-- 1 frost frost    204 Aug  5  2015 bower.json
-rw-r--r-- 1 frost frost    212 Aug  5  2015 component.json
-rw-r--r-- 1 frost frost    669 Aug  5  2015 composer.json
-rw-r--r-- 1 frost frost 595102 Aug  5  2015 highlight.pack.js
-rw-r--r-- 1 frost frost 401788 Aug  5  2015 highlight.pack.min.js
-rw-r--r-- 1 frost frost   1367 May 23 17:27 package.json
drwxr-xr-x 2 frost frost   1400 May 23 17:27 styles
```

**Comment by derhuerst** [comment]
Sure. I'd suggest to remove it entirely and jsut distribute fully working pre-built version of highlight.js.

**Comment by isagalaev** [comment]
Guys, we don't have a Makefile in our package. @wifiextender you're using some third-party bundle of highlight.js, I guess [this one][1].

[1]: https://github.com/components/highlightjs

**Comment by wifiextender** [comment]
It's bit confusing as I saw your avatar right below the npm package [Collaborators](https://www.npmjs.com/package/highlightjs/access), didn't knew that highlightjs is not uploaded by you, and [highlight**.**js](https://www.npmjs.com/package/highlight.js/access) is your package.
