### ISSUE TITLE
highlighting code cause the missing of the cursor

### ISSUE THREAD

**Issue by dayukiller** [isagalaev/highlight.js#1186]
hi,I use highlight.js as tool to highlight the code blocks in my markdown editor;But when it highlight the code,the cursor in the screen missed.For I used it in a live markdown editor,so missing cursor is a not good for appearance.
So is there anyway i can do to avoid missing the sursor when i use highlight.js(I used the highlightBlock function)?
3Q~

**Comment by isagalaev** [comment]
Sorry for taking so long to answer. I don't know how highlighting might interact with the cursor, but I should say that highlight.js was never intended to work as a live highlighter.

**Comment by dayukiller** [comment]
Thanks anyway ~~ I would try to find out if there's someway else to solve this~
