### ISSUE TITLE
C# generics cause code to be detected as arduino

### ISSUE THREAD

**Issue by chimericdream** [isagalaev/highlight.js#1187]
This came up in an [issue on the Dillinger project](https://github.com/joemccann/dillinger/issues/493). I was able to reproduce the error and suspect the fix is similar to the one for Java generics (see #1010). I have a starting point at my fork, but have not gotten the tests passing. I'd be interested to know what I might be missing.

See my commit here for the code so far.
https://github.com/chimericdream/highlight.js/commit/66d366d2ebfba1ff85a1f500a220c52519991a98

**Comment by chimericdream** [comment]
I should note that if you explicitly specify the code as C#, the syntax highlighting works. But the code is not currently being detected as C#. See screenshots below.

With highlighting
![with-hl](https://cloud.githubusercontent.com/assets/198075/15520035/efad48a6-21c9-11e6-8417-c4a60a32dd37.png)

Without highlighting
![without-hl](https://cloud.githubusercontent.com/assets/198075/15520036/efbc196c-21c9-11e6-80ac-ce483afeb64c.png)

**Comment by isagalaev** [comment]
Thanks for catching it, and for the lead to the fix!
