### ISSUE TITLE
Page of HTML code compiled directly displayed, instead of directly shows the code

### ISSUE THREAD

**Issue by erbing** [isagalaev/highlight.js#1189]
```html
<pre><code class="html">
    <h1>123</h1> 
</code></pre>
```

![q5rb wb7fdd8s qpcu7i2d](https://cloud.githubusercontent.com/assets/9959097/15561321/1c0ec48e-2327-11e6-8c34-3c6fb2573759.png)

Review the elements in the browser

But the js and CSS can be highlighted

**Comment by erbing** [comment]
I have a solution for all of this     #73

**Comment by isagalaev** [comment]
Yes, tags in HTML should be escaped to be displayed.
