### ISSUE TITLE
TSX issue with self-closing tags

### ISSUE THREAD

**Issue by danvk** [isagalaev/highlight.js#1190]
Here's a repro with highlightjs 9.4.0: http://jsbin.com/bidepavose/edit?html,output

Here's the code:

```ts
export default class Foo {
  render() {
    // <hr></hr> works fine, but not <hr/>
    // the two nested <div> tags are required to trigger the bug.
    return <div> <div> <hr/> </div> </div>;
  }
  
  // (syntax highlighting breaks here)

  updateInput() {
    const foo = true
  }
}
```

In the demo, the `const` is not highlighted. Replacing the self-closing `<hr/>` with `<hr></hr>` results in correct highlighting.

**Comment by isagalaev** [comment]
Good catch, thanks!
