### ISSUE TITLE
Custom package: select all themes just by one click

### ISSUE THREAD

**Issue by Alexhha** [isagalaev/highlight.js#1196]
Hello,

it would be great if you add some checkbox to automatically select all themes on the download page - https://highlightjs.org/download/. At the moment there is 154 themes and you have to select all of them one by one. It's really annoying.

Thanks in advance

**Comment by isagalaev** [comment]
This is deliberate as we don't want to encourage people using a full package on the Internet by default, it's more than 400K! If you do need this for some reason, the best way of doing it would be to get the source and build it with `node tools/build.js` — that will give you a full browser build.
