### ISSUE TITLE
cpp - no highlight to the whole file with `# define x(v) ((v))`

### ISSUE THREAD

**Issue by avih** [isagalaev/highlight.js#1199]
This is a weird one. I'm trying to highlight files as `cpp` (like so: `hljs.highlightAuto(str, ['cpp']).value`) and in general it works well, but then it failed on one file completely - i.e. completely no highlight.

I tried to create a small test case, and here's what I have so far:

This fails to highlight as `cpp` (it doesn't throw error but the output is identical to the input - no html spans):
```c
#include <stdio.h>
# define x(v) ((v))

int main (int argc, char **argv) {
    printf("Hello, world!\n");
    return 0;
}
```

The issue is apparently with the `define` line.

If I remove the space after the `#` like so `#define x(v) ((v))` - then it works.

If I put the space in again but remove one pair of parenthesis, like so: `# define x(v) (v)` then it also works.

But with both space after `#` and two pairs of `()` - it fails completely for the entire file - absolutely no highlight.

If I let it auto highlight instead of specifying `cpp` - then it works - but it doesn't end up using `cpp` highlight (didn't check which language it chooses).

**Comment by sourrust** [comment]
This is now fixed in master. Thanks for reporting the issue.
