### ISSUE TITLE
Matching languages regex

### ISSUE THREAD

**Issue by felixsanz** [isagalaev/highlight.js#1200]
the Regex to match language class is this:

```javascript
    match = (/\blang(?:uage)?-([\w-]+)\b/i).exec(classes);
    if (match) {
      return getLanguage(match[1]) ? match[1] : 'no-highlight';
    }
```

But i see that highlight.js supports languages like: C/AL, Cap’n Proto, C++, C#, DOS .bat, F#, Inform 7, etc.

How is this regex matching those? How do you specify those languages in the class names?

**Comment by isagalaev** [comment]
There's a list of corresponding class names in the docs: http://highlightjs.readthedocs.io/en/latest/css-classes-reference.html#language-names-and-aliases
