### ISSUE TITLE
C++: incorrect highlighting of identifiers that starts with "_t"

### ISSUE THREAD

**Issue by jackycute** [isagalaev/highlight.js#1201]
it would looks like this:
![](https://pbs.twimg.com/media/CkAyZwqUoAAcgu5.jpg)

Which only the "_t" parts get highlighted instead whole identifier.
Might refer to #875 #876

Thanks for helping!

**Comment by sourrust** [comment]
You might want to update your version of highlight.js to 9+ because I can't reproduce this issue on version 9.0.0 through master.

**Comment by jackycute** [comment]
You're totally correct!
Not happen anymore in 9+
Thanks a lot :+1:
