### ISSUE TITLE
Perl variables are not detected in 9.4.0

### ISSUE THREAD

**Issue by afresh1** [isagalaev/highlight.js#1205]
I can't seem to get perl variables to be detected properly.  This small example should put an `hljs-variable` span around `$scalar`, `@array`, `%hash` and `$k` but it doesn't.  I looked at the source and the `VAR` definition *seems* like it should be right, but I don't really know a lot about how the internals work. 

I totally didn't expect that it would know that in `foo =&gt;`, "foo" is a string but it does. Cool!

```<html>
    <head>
        <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.4.0/styles/default.min.css">
        <script src="http://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.4.0/highlight.min.js"></script>
        <script>hljs.initHighlightingOnLoad();</script>
    </head>
    <body>
        <pre><code class="perl">
my $scalar = "string";
my @array  = qw{ foo bar baz };
my %hash   = ( foo =&gt; q{ bar baz } );

sub subroutine {
    for my $k (sort keys %hash) {
        print $k;
        $scalar .= " $k: " . $hash{$k};
    }
}

subroutine();
        </code></pre>
    </body>
</html>
```

**Comment by Sannis** [comment]
@afresh1 we decided not to highlight each variable since 9.0 release.

**Comment by afresh1** [comment]
Ahh, I see.  I didn't realize that since the `bash` config does.  Thank you.

**Comment by isagalaev** [comment]
To elaborate on that, here's my answer for a similar problem raised for PHP: https://github.com/isagalaev/highlight.js/issues/1142#issuecomment-209557477

**Comment by afresh1** [comment]
Would it make sense to highlight [perl's special variables](http://perldoc.perl.org/perlvar.html) then?
