### ISSUE TITLE
Golang not highlighting?

### ISSUE THREAD

**Issue by penguinpowernz** [isagalaev/highlight.js#1218]
I'm trying to get my (hugo) blog to highlight go code, but it doesn't seem to work....

I started with v9.1.0, and just changed it to v9.4.0 but still no luck. I using both `go` and `golang`.

See this page for an example: https://penguinpowernz.github.io/2016/06/golang-interfaces/

Any ideas?

([it works for ruby](https://penguinpowernz.github.io/2016/06/too-many-disks/))

**Comment by isagalaev** [comment]
The highlight.js package on CDN doesn't include a definition for Go (it only includes the "Common" set from https://highlightjs.org/download/). You can add it manually:

```html
<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.4.0/languages/go.min.js"></script>
```

If you're going to need more languages it'll be more efficient to download a custom package then to link to individual languages.

**Comment by penguinpowernz** [comment]
Ah!  Terrific, I did not realize that.  Thank you! :D

**Comment by isagalaev** [comment]
Yeah, that's one common gotcha we often have to deal with. The full package would've come close to 500K, so no chance of it being the default option :-)
