### ISSUE TITLE
building a pack on the website that includes arduino leads to an error

### ISSUE THREAD

**Issue by knewter** [isagalaev/highlight.js#1220]
Because of the way the minification reorders things, I'm guessing, the `cpp` language isn't defined by the time the `arduino` language tries to refer to it.  If you make a minimal build from the site including `arduino` and require it on a page, you will see an error related to this when it tries to get the `cpp` language.

**Comment by isagalaev** [comment]
Indeed, the site's code doesn't do the same dependency sorting the build tool does. Thanks for catching it, I'll fix it as time allows.

Removing the 9.5 milestone as it doesn't actually block the release.

**Comment by isagalaev** [comment]
Should be fixed now. Please check and reopen if needed.
