### ISSUE TITLE
Variable in PHP code are not detected

### ISSUE THREAD

**Issue by BrunoJunior** [isagalaev/highlight.js#1226]
In php.js, you have 
`var VARIABLE = {
    begin: '\\$+[a-zA-Z_\x7f-\xff][a-zA-Z0-9_\x7f-\xff]*'
  };`
but when I look in HTML source (https://highlightjs.org/static/demo/) I have :
` $st1 = `
without any span ...
I think the result would be :
`<span class="hljs-variable">$st1</span> = `

**Comment by Sannis** [comment]
As @isagalaev wrote in #1142:
> Dropping highlighting of regular variables was deliberate, this is a design decision.

**Comment by BrunoJunior** [comment]
OK fine.
But If I want to change this in a fork (for exemple), what changes have I to do to obtain
`<span class="hljs-variable">$st1</span>`
?
I tried to make some changes in the "highlight.pack.js" but it didn't work ...
Thanks for your help ;)

**Comment by BrunoJunior** [comment]
I find the solution with file comparison ...
I add `cN:"variable",` for php variables ...

**Comment by isagalaev** [comment]
@BrunoJunior: `cN` is what `className` becomes after compression. It's possible (though not very likely) that we change the compression algorithm in the future, so the safe way to do that would be to add `className: 'variable'` in the source and then build it.
