### ISSUE TITLE
Rehighlight a code

### ISSUE THREAD

**Issue by Alexhha** [isagalaev/highlight.js#1228]
Hello,

is it possible to rehighlight some code that was already previously highlighted with different language?

For example I have the code

```
<pre class="hl_js bash">
var casper = require('casper').create({
    pageSettings: {
        loadImages:  true,
        loadPlugins: false
    },
    verbose: false,
    logLevel: "debug"
});

casper.start().viewport(800, 600).zoom(5).thenOpen('http://localhost/', function() {
    this.capture('test.png', undefined, { format: 'png', quality: 95 });
    this.echo('Done', 'GREEN_BAR');
});

casper.run();
</pre>
```

I'm using the following code to highlight the code
```
$(document).ready(function() {
            $('pre.hl_js').each(function(i, block) { hljs.highlightBlock(block); });
```

If I rerun the code it doesn't work correctly. I have created a simple application - http://sys-adm.org.ua/pb/

**Comment by GiriB** [comment]
What do you mean by re-run the code ? Do you mean refreshing the page ?

**Comment by Alexhha** [comment]
I mean reapply new style (from bash to python for example) without reloading the whole page

**Comment by GiriB** [comment]
To rehighlight the code, add the name of the 'new language' to the class of the element. (Here  `<pre class="hl_js bash">` should change to `<pre class="hl_js python">`). Note that you will also have to call   `$('pre.hl_js').each(function(i, block) { hljs.highlightBlock(block);` again.

**Comment by Alexhha** [comment]
As I have wrote above it doesn't work correctly. You can test it here - http://sys-adm.org.ua/pb/

be default the pre.hl_js has the following classes "hl_js css". And looks like - http://i.imgur.com/TMbccGk.png

Then I'm reapply new class with jquery in FF console
```
$("pre.hl_js").attr("class", "hl_js diff");
$('pre.hl_js').each(function(i, block) { hljs.highlightBlock(block); });
```
The result looks fine - http://i.imgur.com/ZvPHxJ4.png

But

If I revert to css again 
```
$("pre.hl_js").attr("class", "hl_js css");
$("pre.hl_js").each(function(i, block) { hljs.highlightBlock(block); });
```
the result is quite differs from original one

http://i.imgur.com/34gLFl5.png

**Comment by isagalaev** [comment]
> is it possible to rehighlight some code that was already previously highlighted with different language?

You'll need to extract the raw text from the HTML node for that. If you highlight a node with existing markup highlight.js will try to merge the old markup with the new one.

Here's how it might work (untested):

```js
$(document).ready(function() {
  $('pre.hl_js').each(function(i, block) {
    var text = $(block).text();
    var markup = hljs.highlight(language, text).value; 
    $(block).html(value);
  });
}
```

**Comment by Alexhha** [comment]
I have a little bit modified your code

```js
$(document).ready(function() {
   $('pre.hl_js').each(function(i, block) {
      var text = $(block).text();
      var newSyntax = $("#hljsCurrSyntax option:selected").text()
      var markup = hljs.highlight(newSyntax, text).value;
      $(block).html(markup);
   });
});
```

and it seems working correctly. Thanks for the tip.

**Comment by OmkarMohite505** [comment]
If anyone is trying to resolve this issue now, try this one.
```bash
document.querySelectorAll('pre code').forEach((block) => {
      if (block.hasAttribute('data-highlighted')) {
        // block.removeAttribute('data-highlighted');
      }
      else{
        hljs.highlightBlock(block as HTMLElement);
      }
      
    });
```
