### ISSUE TITLE
ABNF support

### ISSUE THREAD

**Issue by mckibbenta** [isagalaev/highlight.js#1233]
https://tools.ietf.org/html/rfc5234

I am working on implementing this. I have syntax highlighting working well, but my implementation is currently breaking auto detection.

So, I'm opening this issue while I work out the auto detection problem hopefully to avoid anyone duplicating the implementation effort in the mean time.

**Comment by mckibbenta** [comment]
Well, auto detection now works when using the [postal address example](https://en.wikipedia.org/wiki/Augmented_Backus%E2%80%93Naur_Form#example) from Wikipedia. However, I notice that the implementation does not currently support multi-line rules, which are legal. This will require a bit of refactoring.

**Comment by mckibbenta** [comment]
Okay, got some more time to work on this. It appears everything is working fine now. Just going to do a code cleanup this afternoon and I'll submit a pull request. I'll close this issue once that pull is addressed.

**Comment by mckibbenta** [comment]
Things were not working as well as I thought! One regular expression is not working the way I expect it to. So I might need to consult the discussion group.

**Comment by isagalaev** [comment]
I'll try to have a look at it later today! Not much time to work on highlight.js these days, sorry :-)

**Comment by mckibbenta** [comment]
If you mean you'll be looking for a pull request, I never sent one since I noticed that my implementation wasn't rock solid. Using a positive look-ahead assertion in the `begin` property of a mode does not appear to capture the characters I think it should. Almost seems like a highlight.js bug to me. But, this is my first experience with the project, so I'm probably just ignorant =)

I'll try to put together a minimal example for the discussion group soon. However I won't get a chance to do that until tonight or tomorrow.

**Comment by mckibbenta** [comment]
> This is usually an anti-pattern.

I agree as it's been causing me much grief. The original issue which I'm trying to work around with the lookahead is that "keywords" are getting highlighted as a different mode (which I've assigned the highlight.js class `type`).

I assume with most languages, a sufficiently sophisticated mode tree makes this a non-issue. Basically, the problem here is that from a parsing standpoint, these "keywords" are legal anywhere that a 'type' entity would be legal.

These keywords are really just a core set of `type` entities which are given as part of the ABNF language specification itself. Other syntax highlighters I've seen seem generally to treat this set of core rules as keywords.

I might not get around to it tomorrow, but I'll go ahead and send what I've got as you ask.

Thanks for your time!

**Comment by mckibbenta** [comment]
Okay, I actually solved the issue by creating a mode which contains nothing but a `beginKeywords` property. This worked and removed the need for the convoluted regular expressions I was using. I still doubt I implemented this in the best possible way, but I can always improve it in the future.

Feel free to leave any critiques you may have on the pull request I sent. I'm closing this issue now =)
