### ISSUE TITLE
Correct reference for browser/commonJS

### ISSUE THREAD

**Issue by userpixel** [isagalaev/highlight.js#1236]
The `main` in [package.json](https://github.com/isagalaev/highlight.js/blob/master/package.json) currently points to `"./lib/index.js"` but that file doesn't exist when Highlight.js is installed via npm. This results to browserify complaining that it can't find the module.

A workaround is to manually write the full path like this:

```
import highlight from '../../node_modules/highlight.js/src/highlight.js';
```

But it's not very elegant.

Another way is to compile Highlight.js but that's a bit unutual for a package to expect being compiled after being installed by npm.

Maybe `main` can points to the right location or automatically [build](https://docs.npmjs.com/cli/build) it upon installation.

-

I also read in the docs that there is a browser version of highlight.js. For that, we can take advantage of the `browser` key in `package.json`. I would be happily submitting a PR :+1:

**Comment by isagalaev** [comment]
Uhm… I just tried installing the latest 9.5.0 and lib/index.js is very definitely there: https://asciinema.org/a/78c01hrmrj6efj4g75118cjsy

**Comment by userpixel** [comment]
My bad, I referenced github repo instead of the npm package:

```
"highlight.js": "isagalaev/highlight.js.git"
```

**Comment by isagalaev** [comment]
Yeah, we should probably rename 'package.json' into 'pacjage.json.template' for it not to look installable straight from the source.
