### ISSUE TITLE
Highlighting in PHP and C not working properly

### ISSUE THREAD

**Issue by PDDStudio** [isagalaev/highlight.js#1240]
When highlighting a PHP file it seems like there is an issue with the `<?php` syntax, refer to this [issue](https://github.com/PDDStudio/highlightjs-android/issues/2) for details.

When highlighting a C code the values inside the include tags are missing, refer to this [issue](https://github.com/PDDStudio/highlightjs-android/issues/3) for details.

I was able to reproduce both issues by simply creating a blank html file with the source content and highlight.js imports.

**Comment by sourrust** [comment]
You need to escape angle brackets or they will turn into html tags:

* `<` to`&lt;`
* `>` to `&gt;`
