### ISSUE TITLE
only minimized language definition are working

### ISSUE THREAD

**Issue by flashpixx** [isagalaev/highlight.js#1248]
Hello,

I try to create my own language file which is based on the existing Prolog definition. The page is located here https://lightjason.github.io/framework/agentspeak/#lambdaexpression
The language file is in the current version not minimized: https://lightjason.github.io/lightjason.js

But I copied the original Prolog style from https://github.com/isagalaev/highlight.js/blob/master/src/languages/prolog.js

But I cannot get an working language code definition, because it should be, that I need to minimized the code. I copy the code from the prolog.js file into my file, but in this case this does not work, only I put the minimized code into the JS file.

How I can get a working code definition? Thanks

**Comment by isagalaev** [comment]
You need to build the library to use it, it doesn't work straight from the source: http://highlightjs.readthedocs.io/en/latest/building-testing.html
