### ISSUE TITLE
Incorrectly highlights parts of variable names as keywords

### ISSUE THREAD

**Issue by thorsteinssonh** [isagalaev/highlight.js#1253]
under bash highlighting, (possibly other too) highlights sections of var and function names as keywords.
E.g.  highlights  the "test"  and "local" part of this function name
$ function test_local_space {}
This is a bug: highlight.js should check if the discovered keyword has white space char to the right of, it, if it does not, then it is clearly var or foo-name.

**Comment by isagalaev** [comment]
Fixed, thanks!
