### ISSUE TITLE
Add support for reStructuredText

### ISSUE THREAD

**Issue by ycopin** [isagalaev/highlight.js#1256]
[reStructuredText](http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html) is a light-weight markup language. See e.g. [pygments.lexer.markup.RstLexer](http://pygments.org/docs/lexers/#pygments.lexers.markup.RstLexer)

**Comment by isagalaev** [comment]
We don't implement languages on request: http://highlightjs.readthedocs.io/en/latest/language-requests.html
