### ISSUE TITLE
Rename Darkula to Darcula

### ISSUE THREAD

**Issue by bulenkov** [isagalaev/highlight.js#1258]
Hello.
I'm the author of Darcula Look-n-Feel and editor theme Darcula for IntelliJ based products. I'm very excited and happy to find Darcula in highlight.js library. I noticed a little typo in the name. May I suggest to rename Darkula to Darcula, so people who's interesting in Darcula theme for web can easily find highlight.js ?    

Thank you.

**Comment by isagalaev** [comment]
It looks like a very reasonable thing to do but unfortunately it's slightly backwards incompatible: the links to darkula.css will stop working with the next release. For now it doesn't feel to me like correcting a typo is worth the trouble of making a breaking change (and I hate typos myself!)

Could you live with "darkula.css" as it is, Konstantin? :-)

**Comment by bulenkov** [comment]
Is this will fix the problem? 
`@import "darkula.css"`

**Comment by isagalaev** [comment]
It will! My brains were stuck for most of the day, so I didn't see the obvious solution :-)
Could you make a pull request with this change? And with a comment in the old file about it being here for compatibility with an old name.

**Comment by CAD97** [comment]
This doesn't appear to be working for me.

From 9.6.0 onward, using the link

```html
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/darkula.min.css">
```

loads the stylesheet

```css
@import url('darcula.css');
```

and `darcula.css` has a content of:

```html
<html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

-- a 404 error.

`darkula.min.css` needs to import `darcula.min.css` and not `darcula.css` which does not exist in the context of the CDN.

(Linking `//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/darcula.min.css` directly works fine.)

(ping @isagalaev)
