### ISSUE TITLE
perl6 support

### ISSUE THREAD

**Issue by melezhik** [isagalaev/highlight.js#1260]
Hi! Does highlight.js support perl6 syntax?

**Comment by isagalaev** [comment]
No, our Perl support is pretty old.

**Comment by melezhik** [comment]
Ah, bummer. Any plans on perl6 support?

**Comment by isagalaev** [comment]
We don't actually have plans for language definitions, we maintain the library, and the languages come from contributors: http://highlightjs.readthedocs.io/en/latest/language-requests.html
