### ISSUE TITLE
"Simple"/"Default" formatting support?

### ISSUE THREAD

**Issue by hmmwhatsthisdo** [isagalaev/highlight.js#1261]
It would be nice if there was support for a "default" format that adds only bare-minimum formatting to an element (background/foreground color, essentially) so code blocks that don't follow a recognized format can have at least some level of style-parity with highlight.js-styled code blocks.

As far as I can tell, this functionality does not currently exist.

**Comment by isagalaev** [comment]
This is one of the deliberate design choices: we don't want to style what we don't highlight in any way. Sites can always style those in their own stylesheet.
