### ISSUE TITLE
PHP variable and chained function support

### ISSUE THREAD

**Issue by cercos** [isagalaev/highlight.js#1264]
Request for PHP variables and method chains highlighting.

**Comment by isagalaev** [comment]
This is a volunteer project, we don't do requests, sorry. Please read http://highlightjs.readthedocs.io/en/latest/language-requests.html (applies to language feature too).

**Comment by isagalaev** [comment]
Also, for the variables part, please read #1142. It might change in the future, but for now it explains why things are the way they are.
