### ISSUE TITLE
Window is not defined using web worker

### ISSUE THREAD

**Issue by Jerome1337** [isagalaev/highlight.js#1266]
I'm trying using `web worker` to load a huge piece of code so I used this code inside a `script` tag in the page.

```
addEventListener('load', function() {
    var code = document.querySelector('pre code');
    var worker = new Worker('/js/worker.js');

    worker.onmessage = function(event) {
         code.innerHTML = event.data;
     };

     worker.postMessage(code.textContent);
});
```

This part is working and using my `worker.js` compilated from my coffeescript file

```
onmessage = (event) ->
  importScripts('//cdnjs.cloudflare.com/ajax/libs/highlight.js/8.4/highlight.min.js')
  result = self.hljs.highlightAuto(event.data)
  postMessage(result.value)
```

The problem is that when the `highlight.pack.js` is loaded inside my worker I get the error

> ReferenceError: window is not defined

But `window` is defined in the `highlight.pack.js` file.
How can I fix this error ?
Is this error is a common one ?

**EDIT**

The error above is gone, I don't get it anymore but when the worker job is finished, the code is not even highlighted. The code is the same as above (same as the doc) 0 error, but nothing is changing, the code is not anymore highlighted. I don't know what to change to make this work.

Is my code is not correct ? Did I miss something ?

Thanks

**Comment by isagalaev** [comment]
We've only got Web Workers support in 9.0, you're trying to use 8.4.

**Comment by Jerome1337** [comment]
Ah okay, everything is working, thanks
