### ISSUE TITLE
How to include punctuations/operators for custom highlighting?

### ISSUE THREAD

**Issue by igauravsehrawat** [isagalaev/highlight.js#1268]
I know this goes against philosophy of highlight.js, but I have been trying to customize it.
I put the following key-value in `keywords` object.

`built_in: /= \+= -= \*= \= %= == != <= >= < > \+ - \* % \^/`

But they aren't getting any `span` class, seems like they are being skipped. Is there a way to this?
Any help would be appreciated.

Thanks

**Comment by isagalaev** [comment]
No, not keywords. You want a separate mode like this:
```js
{
  className: 'built_in',
  begin: /=|+=|-=/
}
```
