### ISSUE TITLE
Why is the code formatting not working on this highlighted generated jekyll page?

### ISSUE THREAD

**Issue by xameeramir** [isagalaev/highlight.js#1269]
In my [gh-page](https://github.com/xameeramir/xameeramir.github.io/blob/master/_posts/2016-6-30-what-is-silverlight.md), the [code formatting tags are properly encoded](http://stackoverflow.com/q/34532476/2404470). 

`&lt; tag name goes here &gt;`

Corresponding `<pre>` and `<code>` tags are enclosed.
I believe this is the reason, the [preview](https://github.com/xameeramir/xameeramir.github.io/blob/master/_posts/2016-6-30-what-is-silverlight.md) renders without any issue.

[![Github page preview renders perfectly][1]][1]

However on the [resulting page UI](http://xameeramir.github.io/what-is-silverlight/), the code highlighting breaks after `# Dependency property system - DPS`.

[![UI breaks on Github page][2]][2]

I'm using [highlightjs](https://highlightjs.org/)

This seems to be a kind of bug to me.

Any suggestions on this?

  [1]: http://i.stack.imgur.com/v5Dgn.png
  [2]: http://i.stack.imgur.com/hKGyl.png

[source](http://stackoverflow.com/q/38790827/2404470)

**Comment by isagalaev** [comment]
It's a bug, but not in highlight.js. Here's an excerpt of the relevant part of your page source:

```html
<pre><code>
namespace abcLib
{
  public class LatinWords : IMarkupExtension<string>
 ...
}&lt;/code&gt;&lt;/pre&gt;
```

There are two problems with it:

- You probably wanted `<string>` displayed as is, so you have to escape it as `&lt;string&gt;`
- It looks like `&lt;/code&gt;&lt;/pre&gt;` was supposed to actually end this code snippet, so they should *not* be escaped: `</code></pre>`

I don't know what kind of software generates this HTML, so I can't give any particular recommendations on how to fix those two problems. But they most certainly have nothing to do with highlighting, it's just HTML.
