### ISSUE TITLE
Possible bug in regex implementation resulting in too much time to process

### ISSUE THREAD

**Issue by igauravsehrawat** [isagalaev/highlight.js#1272]
Hi there,
I have this regex `/^[ ]*?\b[A-Za-z_][0-9A-Za-z_\?]*?\s*?\(\s*?([^\)])*?\)\s*?\=([^\;]*?\;$)/`
I tried this regex too `/^\s*?\b[A-Za-z_][0-9A-Za-z_\?]*?\s*?\(\s*?([^\)])*?\)\s*?\=([^\;]*?\;$)/`
This regex is supposed to match patterns such 
1. `func(x) = x * x;`
2. `func(x) = x 
                         *
                       x; `
3. ` (insert some spaces/identation)    func(x) = x * x;`

First two pattern matches fine but with 3rd type of pattern/procedure definition, it's taking too much time.

I checked this pattern in dev tools, it works there fine with matching, but while using in highlight.js, I seems to spin CPU high and take too much time.

I have some working demo here for the same syntax https://igauravsehrawat.github.io/highlight.js/tools/developer.html 

My code for syntax definition is here: https://github.com/igauravsehrawat/highlight.js/blob/gh-pages/src/languages/custom-lang.js

Looking forward for inputs.
Thanks

**Comment by isagalaev** [comment]
Hi! I'm slowly working through my bug mail queue :-)

Your pattern is more complicated than it needs to be, this one should work:

```js
/^\s*[A-Za-z_][A-Za-z0-9]*\s*\((.*?)\)\s*=(.*?);$/
```

**Comment by isagalaev** [comment]
Also, I'm going to close the issue, as it doesn't assume any actions on the core team's part.

**Comment by igauravsehrawat** [comment]
Ok.

Thanks.
