### ISSUE TITLE
typescript generics are interpreted as html tags

### ISSUE THREAD

**Issue by joost-de-vries** [isagalaev/highlight.js#1280]
The following is valid typescript using generics
```typescript
const stringArray: Array<string> = new Array<string>();
```
It seems that highlightjs interprets the angled brackets as html since it tries to insert a closing tag.
[Here's a pastebin](http://jsbin.com/zopape/edit?html,output) that shows the problem.

**Comment by isagalaev** [comment]
You should escape angle brackets in HTML to have them displayed literally. This has nothing to do with highlight.js, actually. The way you have it in the pastebin, your code snippet has actual HTML tags `<string>`, which browser interprets like tags.
