### ISSUE TITLE
Nested comments break highlighting

### ISSUE THREAD

**Issue by GottemHams** [isagalaev/highlight.js#1283]
When using nested comments, it may produce a syntax highlighting bug. Let's say I forked someone's code and find certain features mentioned in comments don't work anymore. I comment out all the non-working stuff (including comments) but leave it all in there for reference, until I'm completely finished. This may result in __everything__ from the nested comment till the end looking like it's commented out.

You can find a little demo [right here](https://try.gogs.io/GottemHams/SyntaxBug).

I realise it's mostly human error to have comments like this, but I personally like to prefix no longer relevant stuff within block comments with `//` anyways so I can quickly skim over it. It's easily forgotten to add a space between a `*` and `//`. =]
As for other people: They may not realise what causes the bug to appear. It works fine with vim and Sublime Text, for example.

**Comment by isagalaev** [comment]
What language are you talking about?

**Comment by GottemHams** [comment]
Well the demo repo is in C, not sure if it happens with other languages that support block comments like `/* Hi */`.

**Comment by isagalaev** [comment]
I was confused by reading your description which made me think you're suggesting a general rule about comments in all languages. But anyway, I've found and fixed the bug which was caused by the Rust language which does support nested comments but did it for all languages using C-style comments instead of only itself.

Thanks for catching this!

**Comment by GottemHams** [comment]
Sorry about that, thought I was clear enough. =) Thanks for fixing it this quickly though.
