### ISSUE TITLE
More keywords for Pascal/Delphi

### ISSUE THREAD

**Issue by SAmeis** [isagalaev/highlight.js#1285]
Please add the following keywords to the keyword identifiers for the Delphi language. See http://freepascal.org/docs-html/current/ref/refse3.html for reference. They are currently missing in file src/languages/delphi.js

absolute
reintroduce 
operator
as
is
abstract
alias
assembler
bitpacked
break
continue
cppdecl
cvar
enumerator
experimental
platform
deprecated
unimplemented
dynamic
export
far16
forward
generic
helper
implements
interrupt
iochecks
local
name
nodefault
noreturn
nostackframe
oldfpccall
otherwise
saveregisters
softfloat
specialize
strict
unaligned
varargs

Kind Regards

**Comment by isagalaev** [comment]
Could you make a pull request with this change, please? It should be pretty straightforward.
