### ISSUE TITLE
Recent update seems to have broken handling of newlines after javascript comments

### ISSUE THREAD

**Issue by EricBalingit** [isagalaev/highlight.js#1286]
I'm seeing no line breaks between comments followed by key words.

This:
```
// test1
var test1;

/* test2 */
var test2;
```

becomes this:
```
// test1var test;
/* test2 */var test2;
```

But this works:
```
// update
test = test + 1;
```

**Comment by EricBalingit** [comment]
I'm seeing the issue in Chrome browser but not in FF.

**Comment by isagalaev** [comment]
I can't seem to reproduce it on my machine:

- Using a full build, a :common build and a build with only javascript in it
- Both Chromium and Firefox on Ubuntu
- Using tools/developer.html from highlight.js source tree
- This source:
  ```
  // test1
  var test1;

  /* test2 */
  var test2;
  ```
  gives me exactly this markup:
  ```
  <span class="hljs-comment">// test1</span>
  <span class="hljs-keyword">var</span> test1;

  <span class="hljs-comment">/* test2 */</span>
  <span class="hljs-keyword">var</span> test2;
  ```

Could you say more about your environment and what you're doing?

**Comment by EricBalingit** [comment]
My apology.

I found the issue.

It still holds with everything I said above.

The trouble was this in Chrome:
```
pre code {
    display: table;
    ....
```

When I change to:
```
display: block;
```
apparently it works fine.

I doubt it would be worth trying to fix, but you know better than me of course. :)

**Comment by isagalaev** [comment]
Well, since this style rule doesn't come from highlight.js we can hardly fix it even if we wanted to :-) The user style sheet has a precedence over the author one anyway.
