### ISSUE TITLE
Require.js will throw an error when use highlight.js

### ISSUE THREAD

**Issue by poppinlp** [isagalaev/highlight.js#1288]
When i use highlight.js with require.js, there will be an error:
`Uncaught Error: Mismatched anonymous define() module: function (){return n.hljs}`

I think it's because of anonymous module defined in highlight.js

I make a [demo](http://codepen.io/poppinlp/pen/mAbKjK?editors=1010) for error situation. Please open dev tool and you'll see what i said in console.
And i make a [demo](http://codepen.io/poppinlp/pen/amoGJx?editors=1010) which makes things right.

**Comment by sourrust** [comment]
AMD actually [recommends using an anonymous define][1]. Look at the section called "On Almond" for [getting the library][2] in the README.

[1]: https://github.com/requirejs/requirejs/wiki/Updating-existing-libraries#register-as-an-anonymous-module-
[2]: https://github.com/isagalaev/highlight.js#getting-the-library

**Comment by poppinlp** [comment]
I got it. THX.
But at the beginning, i just include require.js and highlight.js in page and then throw a error.
I think there may a nice way to solve this without rebuild highlight.js since i just go to your website and wanna use it.

**Comment by sourrust** [comment]
Sure there is two ways actually:

First one is the file path right in the require

```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.2.0/require.min.js"></script>
<script>
require(['https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.6.0/highlight.min.js'], function(hljs) {
  hljs.initHighlighting();
});
</script>
```

The other is configuration with a named module and a path to the named module

```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.2.0/require.min.js"></script>
<script>
require.config({
  paths: {
    hljs: 'https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.6.0/highlight.min'
  }
});

require(['hljs'], function(hljs) {
  hljs.initHighlighting();
});
</script>
```

**Comment by poppinlp** [comment]
Got it. Sorry for bother you.
REALLY THX.
