### ISSUE TITLE
So slow regex in less

### ISSUE THREAD

**Issue by Vnthf** [isagalaev/highlight.js#1293]
When I write in codeblock about 3000 length charcters (no spaces, no line break like below), browser is stopped. 
```
ABCDBDBCBCBDBDBABCDBDBCBCBDBDBABCDBDBCBCBDBDBABCDBDBCBCBDBDBABCDBDBCBCBDBDBABCDBDBCBCBDBDBABCDBDBCBCBDBDBABCDBDBCBCBDBDBABCDBDBCBCBDBDBABCDBDBCBCBDBDBABCD .........
````
so I debugged this issue. I found that less regex is so slow. 

```
/\/\/|\/\*|@(import|media|charset|font-face|(-[a-z]+-)?keyframes|supports|document|namespace|page|viewport|host)\b|@[\w-]+\s*:|@[\w-]+|([\w-]+|@{[\w-]+})\s*:|[\.#:&\[>]|([\w-]+|@{[\w-]+})[^;]*{|[=>'\/<($"]/gim
```
this regex spend time about 10000ms.

I think that ``([\w-]+|@{[\w-]+})[^;]*{`` is not correct.

It must remove eithor + or *.

I recommend  ``([\w-]+|@{[\w-]+})[^;]{`` .

less.js
``` 
variants: [{
      begin: '[\\.#:&\\[>]', end: '[;{}]'  // mixin calls end with ';'
      }, {
      begin: INTERP_IDENT_RE + '[^;]',
      end: '{'
    }],
```

**Comment by isagalaev** [comment]
Which version of highlight.js are you using? We fixed something like this in less.js a while ago.

**Comment by Vnthf** [comment]
@isagalaev I tested both lastest version and 9.1.0. Both are occured.

**Comment by isagalaev** [comment]
I tried to fix it along the idea you proposed. Let's see how it flies.
