### ISSUE TITLE
Ruby mode doesn't treat heredocs as strings

### ISSUE THREAD

**Issue by pkaminski** [isagalaev/highlight.js#1300]
Repro here: https://jsfiddle.net/ukmy8qdd/1/
Heredocs: https://ruby-doc.org/core-2.2.0/doc/syntax/literals_rdoc.html#label-Here+Documents

**Comment by isagalaev** [comment]
I made a naive implementation that works with your example (thank you for doing one!) It's a pretty naive implementation that doesn't require the end word to be the same as the start word. This is a limitation of our parser, unfortunately. However, PHP and Perl have a similar construct defined just as naively and it mostly works in the wild :-)

**Comment by pkaminski** [comment]
A naive implementation is infinitely better than none!  Thanks for adding this just in time for 9.7.0 -- integrated.

**Comment by isagalaev** [comment]
Unfortunately, the night before release is pretty much the only time I can afford to devote to the project these days… And having a clear description and a repro greatly increases the chance of a particular issue making it into a release :-)
