### ISSUE TITLE
Python multi-line Docstrings

### ISSUE THREAD

**Issue by marcrobinson** [isagalaev/highlight.js#1322]
I'm using highlight.js through remark.js and highlighting of Python multi-line docstrings is not working.

The first line is highlighted - but this is because it is detected as a 'hljs-string'. 

Does highlighter support multi-line docstrings ? Would be a similar behaviour to block comments in C etc...

**Comment by isagalaev** [comment]
I once ran into it myself :-) remark.js uses some ancient version of highlight.js, you should harass its maintainer to update it. That should fix it.
