### ISSUE TITLE
Inconsistent colors for `shell` 

### ISSUE THREAD

**Issue by kadimi** [isagalaev/highlight.js#1325]
![Preview for shell syntax highlighting](http://i.imgur.com/rup1owd.png)

Thanks

**Comment by camilstaps** [comment]
Do you mean that `cd` is green and `cat` is not? `cd` is a sh builtin (see `man sh`), while `cat` is part of coreutils (`man cat`).

**Comment by kadimi** [comment]
@camilstaps That makes sense, thank you
