### ISSUE TITLE
Unable to highlight dynamically created content

### ISSUE THREAD

**Issue by runsun** [isagalaev/highlight.js#1328]
Have a html that downloads code from the internet and displays it using the following javascript callback:

``` javascript
function display_file(fileInfo)
{
    $('#div_pygments_loadfiles')[0].innerHTML +=
    ` <details class="fileContent">
      <summary><b>${fileInfo.path}</b></summary>
      <pre><code class="python hljs">${fileInfo.data}</code></pre>
     </details>
    `   
}
```

It creates a `<pre><code class="python hljs">` block to hold the code. The element inspection using the developer tools shows that it is classed with "python hljs" as expected, but the code is not highlighted, only the background is painted with the desired color/pattern. Tried several styles but all behave the same way. 

The same downloaded code, if copied and pasted to the `<body>` section with the same `<pre><code class="python hljs">` tags, is highlighted normally.

**Comment by runsun** [comment]
You can download the file `demo.html` from my Bitbucket snippet to check it out:

https://bitbucket.org/snippets/runsun/bMKzz

or copy and paste its raw file:

https://bitbucket.org/!api/2.0/snippets/runsun/bMKzz/f64fda6945c927511d7e6e96f2387fd185e7caa1/files/demo.html

**Comment by fsharpasharp** [comment]
You have to use the highlightBlock function after you have added new content. The default behavior is highlighting only when the page loads.
