### ISSUE TITLE
src code not working

### ISSUE THREAD

**Issue by brucejcw** [isagalaev/highlight.js#1340]
I'm using [uncompress highlightjs](https://github.com/isagalaev/highlight.js/blob/master/src/highlight.js), but seems it not work, js doesn't parse code between `pre code`

**Comment by brucejcw** [comment]
[demo here](http://plnkr.co/edit/OTkulcLqaZq1X2Cz4H1D?p=preview) from [source code](https://github.com/isagalaev/highlight.js/blob/master/src/highlight.js)

**Comment by MikeHarrison** [comment]
I am seeing the same issue

**Comment by isagalaev** [comment]
Indeed, it's not supposed to work straight out of the source: https://github.com/isagalaev/highlight.js#getting-the-library
