### ISSUE TITLE
go.min.js:1 Uncaught ReferenceError: hljs is not defined

### ISSUE THREAD

**Issue by jorenvh** [isagalaev/highlight.js#1343]
Can't seem to get the lib working.
```

<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.4.0/languages/go.min.js"></script>
<script>hljs.initHighlightingOnLoad();</script>

<script>
    $(document).ready(function() {
        $('pre').each(function(i, block) {
            hljs.highlightBlock(block);
        });
    });
</script>
```

**Comment by sourrust** [comment]
Right now you included the language but not the core library. You also only need to choose one initialization function, because `initHighlightingOnLoad` and the jQuery `$(document).ready(function() { ... })` are essentially the same thing. So change your example to:

```html
<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.8.0/highlight.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.8.0/languages/go.min.js"></script>
<script>hljs.initHighlightingOnLoad();</script>
```

**Comment by jorenvh** [comment]
@sourrust I forgot I created this issue, I found it out myself already, Only thing I can say is that the docs are not very clear in that case.
