### ISSUE TITLE
Double slash // is recognized as comment in Ruby code

### ISSUE THREAD

**Issue by hachi8833** [isagalaev/highlight.js#1351]
## Version 9.8.0 "New York"

![image](https://cloud.githubusercontent.com/assets/4289625/20294490/d915de26-ab41-11e6-9e01-8b9a2f53eb57.png)

As shown the screenshot above, double slash "//" is recognized as comment in Ruby code.

```ruby
def match?(string, pos = 0)
  !!match(string, pos)
end unless //.respond_to?(:match?)
```

*"//" is a representation of Regex object in the case.

Thank you,

**Comment by isagalaev** [comment]
It was indeed a bug, thanks for reporting it! Although judging by your screenshot alone in your case the code was also mis-detected as some other language. Hopefully, the fix would also nudge the detection towards Ruby as well (it should, I just don't know if it'd be enough enough :-) )

**Comment by hachi8833** [comment]
I should've posted with the actual code. Sorry.
Looks like the language of the code is incorrectly detected as you guessed.

* Actual page: https://techracho.bpsinc.jp/hachi8833/2016_11_15/28993
  * code part:

<pre>
```ruby
def match?(string, pos = 0)
  !!match(string, pos)
end unless //.respond_to?(:match?)
```
</pre>

Just now I found that the language detection looks duplicated:
![image](https://cloud.githubusercontent.com/assets/4289625/20772973/1e8b415a-b793-11e6-89c6-b29f22c9ce2e.png)

`pre` class says "hjls go" while `code`class says "ruby".

Best,
