### ISSUE TITLE
Missing test/detect/css/default.txt

### ISSUE THREAD

**Issue by marcoscaceres** [isagalaev/highlight.js#1354]
After doing `npm install` or `yarn install`, with a package.json entry of:

```JSON
{
  "dependencies": {
      "highlight.js": "git+ssh://git@github.com/isagalaev/highlight.js"
   }
 }
```

I try to run: 
```bash
node ./tools/build.js -n xml javascript css http markdown xquery
```

And get the following error:
```bash
Starting build.
Copying documentation.
Writing documentation.
Generating demo.
{ task: 'tasks',
  error:
   { task: 'readSnippet',
     error:
      { Error: ENOENT: no such file or directory, open 'test/detect/css/default.txt'
        errno: -2,
        code: 'ENOENT',
        syscall: 'open',
        path: 'test/detect/css/default.txt' } } }
```

I can confirm that the test/ directory is in fact not created.

**Comment by marcoscaceres** [comment]
sorry, accidentally submitted the bug... sending again.

**Comment by marcoscaceres** [comment]
Updated description. Sorry for the additional noise!

**Comment by isagalaev** [comment]
Hm… I'm not sure I understand what's happening here. The test/ directory is in the root of this repository. If you simply check it out and run the command your provided (`node ./tools/build.js ...`) it works as expected. I'm not sure how you end up with a checkout that does have tools/ but doesn't have test/.

**Comment by marcoscaceres** [comment]
I know... it's weird (I'm inclined to blame yarn 17 at this point) :( I'll look a little more.

**Comment by marcoscaceres** [comment]
ok, yeah... yarn is screwing up. I did a `rm -rf node_modules; npm install` and it worked again. 

Not sure why yarn is not including the test directory. I've switched back to npm for now.

**Comment by isagalaev** [comment]
OK :-)

**Comment by chestnutchen** [comment]
This issue occured in npm5 again. Not bug this time. https://github.com/npm/npm/issues/18961
