### ISSUE TITLE
Add a little (Discord) after Solarized Dark?

### ISSUE THREAD

**Issue by austinhuang0131** [isagalaev/highlight.js#1364]
I mean, since [Discord](http://discordapp.com) uses this style for the code block markup in chats and Discord is pretty popular and there are lots of Discord users, why don't just add a little `(Discord)` label after the `Solarized Dark` style on the demo page?

*Just the demo page.*

**Comment by Oxylibrium** [comment]
Solarized Dark _is_ Solarized Dark, no matter what app uses it. It's a standard so many places else too. I think this can be closed.

**Comment by isagalaev** [comment]
Yes, we definitely don't want to go the slippery slope of adding all the possible aliases to names (as soon as we add one, other people will ask for more). Sorry!
