### ISSUE TITLE
Delphi Directives

### ISSUE THREAD

**Issue by PauloFrancaLacerda** [isagalaev/highlight.js#1366]
Hello.
I'm using Highlight.js (v9.8.0) along with Asciidoctor. Both amazing tools!
I'm a programmer in Delphi, so I'd like to leave a contribution in the form of a bug report...

Delphi directives are being mistakenly recognized as comments. 
Examples:
    `{this is a comment} (*same here*)`
    `{$but this is a directive} (*$same here*)`

Despite the fact `{$but}`, `{$same}` and the others are not valid directives, both should be highlighted as directives.The picture below shows the correct highlighting:
![delphidirectives](https://cloud.githubusercontent.com/assets/17791112/20694036/94c9f6de-b5c9-11e6-876c-88ebe2ff8c16.png)
The highlighter doesn't have to know which directives are (or not) valid, but just distinguish between comments and directives depending on the leading string: `{$` or `(*$` .

Thanks in advance.

**Comment by logicplace** [comment]
In src/languages/delphi.js try adding to COMMENT_MODES before the hljs.COMMENT entries:

    {
      className: 'meta',
      begin: /\{\$/, end: /\}/
    },
    {
      className: 'meta',
      begin: /\(\*\$/, end: /\)/,
      relevance: 10
    },

I'd do it but I don't want to test it (I don't know delphi).

**Comment by PauloFrancaLacerda** [comment]
@logicplace: Thank you for responding. I'd like to try out your code, but I'm unable to compile the sources. I just use the precompiled version (by the site).
I'm on Windows and have absolutely no experience on node.js and other tools necessary to rebuild the sources.

Loking at the pre-built `highlight.pack.js`, I can't see how to adjust it to include your code.
Thanks anyway.

**Comment by isagalaev** [comment]
Thanks for the report and the investigation to both of you! The fix will be out in the next release planned on December 13.
