### ISSUE TITLE
Ruby's comment sign # is incorrectly recognized unless it is on the top of the line

### ISSUE THREAD

**Issue by hachi8833** [isagalaev/highlight.js#1370]
I found some incorrect highlighting for Ruby syntax:

* Works fine as far as '#' is on the top of the line
  * ![image](https://cloud.githubusercontent.com/assets/4289625/20747693/5f7eab3a-b72e-11e6-892b-ab32e314269f.png)
* Not working if '#' is in the middle of the line
  * ![image](https://cloud.githubusercontent.com/assets/4289625/20747698/64be8138-b72e-11e6-913f-68b98155fe86.png)

I hope you kindly fix the issue.

Thank you,

**Comment by isagalaev** [comment]
Just by looking at the screenshots I could suggest that the language of those snippets isn't set to Ruby (or your custom package of highlight.js doesn't contain the Ruby definition). I could dig more if you'd posted the actual text of those snippets.

**Comment by hachi8833** [comment]
Thank you for looking into it!
As you pointed out, the detection might be incorrect in some cases while designated 'ruby' in Markdown.

* Actual page: https://techracho.bpsinc.jp/baba/2011_08_23/4403
  * code part 1:

<pre>
```ruby
class String
  def hex2bin
    s = self
    raise "Not a valid hex string" unless(s =~ /^[\da-fA-F]+$/)
    s = '0' + s if((s.length & 1) != 0)
    s.scan(/../).map{ |b| b.to_i(16) }.pack('C*')
  end

  def bin2hex
    self.unpack('C*').map{ |b| "%02X" % b }.join(")
  end
end
```
</pre>

  * code part 2:

<pre>
```ruby
# RIFFのチャンク識別子を取得(単純に先頭4byte)
# ここは1byteずつ格納されているのでエンディアン非依存
def chunk_identifier(data)
  data[0..3]
end

# RIFFチャンクのデータサイズを取得
def chunk_size(data)
# 4..7バイト目に、リトルエンディアン4byteでチャンクサイズが格納されている.
# Vはリトルエンディアン32bitの意味
  data[4..7].unpack('V')[0]
end

def make_chunk(identifier, data)
  c = ''.force_encoding(Encoding::ASCII_8BIT)
  c << identifier.dup.force_encoding(Encoding::ASCII_8BIT)
  c << [data.bytesize].pack('V')
  c << data.dup.force_encoding(Encoding::ASCII_8BIT)
  if data.bytesize & 1 != 0
    c << 0 #サイズが奇数の場合はパディングを詰める
  end
  return c
end
```
</pre>

Regards,

**Comment by hachi8833** [comment]
Finally we found that the invocation of highlight.js was incorrect. Not your bug. Sorry.
Closing the issue...
