### ISSUE TITLE
Messing With Site 

### ISSUE THREAD

**Issue by EricHamby** [isagalaev/highlight.js#1377]
How do i wrap the code so its not interfering with my site css?

**Comment by logicplace** [comment]
By default the code you add is wrapped in <pre><code> and all the classes added to created elements for styling are prefixed with **hljs-** so I'm not sure what issue there would be?

**Comment by isagalaev** [comment]
> By default the code you add is wrapped in `<pre><code>`

Only, highlight.js doesn't itself wrap the code in anything. `<pre><code>` is what it looks for on the page by default but the user is free to feed it any container in fact.

**Comment by EricHamby** [comment]
Building a WordPress theme for snips and trying to use this js. As you can see from the link the CSS inside the pre/code is destroying the rest of the page. 

http://www.terranbytes.com/wordpress/pastepress/code/simple-wordpress-page-php/

**Comment by isagalaev** [comment]
We're not going to fix your site for you, sorry. None of highlight.js styles even include fonts, so this breakage doesn't come from highlight.js (which is also evident if you inspect affected elements in your browser's dev tools).

**Comment by EricHamby** [comment]
Odd it only affects the page displaying css inside highlight.js. I also dont see where fonts are the issue. The main issue im getting is the padding and margin over rides from the css inside the highlight.js.

**Comment by logicplace** [comment]
The code is inside the CSS you're highlighting, no where else. For whatever reason you're including that CSS actively. It's not highlight.js because you can see it in the page source (Ctrl+U). If you're not selecting for it to, it may be something wordpress is doing.

**Comment by EricHamby** [comment]
So if anyone post code that just also happens to be in my style sheet, even if canceled out its going to activate it again. thanks.
