### ISSUE TITLE
Swift 3.0 support

### ISSUE THREAD

**Issue by paweldudek** [isagalaev/highlight.js#1380]
First of all let me say huge thank you for all the awesome work highlight.js! Great piece of open source software! 

The problem that I have is with how highlight.js works with latest Swift 3.0 changes. For instance simple code like this:

```
tableView.register(class: YourTableViewCell.self)
tableView.register(class: TheirTableViewCell.self)
```

is rendered as

![screen shot 2016-12-08 at 12 27 06](https://cloud.githubusercontent.com/assets/968513/21008384/c8e53616-bd41-11e6-86ce-1099262a2e03.png)

whereas Xcode (default IDE for Swift) rendering looks like this: 

<img width="386" alt="screen shot 2016-12-08 at 12 39 22" src="https://cloud.githubusercontent.com/assets/968513/21008992/96fa5cd2-bd44-11e6-8106-88b94694f914.png">

I understand it's not easy to keep up with changes to Swift, but it'd be great to have Swift 3.0 supported!

I might be able to tackle this on my own, but unfortunately I have a very limited knowledge of Javascript and how highlight.js works. Perhaps there's someone more experienced who'd like to tackle this. If so - go for it!

**Comment by isagalaev** [comment]
In fact, our team has no hope in keeping up with all the languages, and that never was even the idea :-) This falls on the shoulders of language contributors and whoever in language communities feels motivated to do it. So, if you're not up to doing the update yoursself, look into https://github.com/isagalaev/highlight.js/blob/master/src/languages/swift.js to find out who did what contribution and try contacting them (keeping in mind they're all volunteers and made no promises either).

**Comment by paweldudek** [comment]
Totally understood! I filled this issue to make sure that it's accounted for, perhaps someone someday (possibly me? 😉) finds time to update Swift support. I might be able to tackle this during Christmas break, but no promises!

**Comment by isagalaev** [comment]
I prefer not to keep open issues which are essentially feature request. They don't add much (or anything) in enabling the feature to be implemented, because motivation is coming from outside, not from the project. But they do add noise to the list of actionable items. So I'll close it for now so a new one can be created with a pull request.
