### ISSUE TITLE
highlight is incorrect

### ISSUE THREAD

**Issue by nicothin** [isagalaev/highlight.js#1381]
I want to highlight LESS
but I get the backlight another language :(
what am I doing wrong?

http://codepen.io/nicothin/pen/MbBXYx?editors=1000 — example

**Comment by isagalaev** [comment]
You're using a CDN-hosted build of highlight.js which only contains a dozen of common languages, and Less is not one of them. Either get yourself a custom build with all the languages you need from https://highlightjs.org/download/ or include a separate Less definition from the same CDN:

    <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.8.0/languages/less.min.js"></script>

And make sure to [read through README][1] :-)

[1]: https://github.com/isagalaev/highlight.js/#getting-the-library
