### ISSUE TITLE
Function name standards is garbage

### ISSUE THREAD

**Issue by mossarelli** [isagalaev/highlight.js#1398]
```
/*! highlight.js v9.6.0 | BSD3 License | git.io/hljslicense */
...
function t(e) {
    return e.nodeName.toLowerCase()
}

function r(e, n) {
    var t = e && e.exec(n);
    return t && 0 === t.index
}

function a(e) {
    return k.test(e)
}
```

Yes, I've looked in the highlight.js file on Github but this was the download version from the website. This naming convention makes editing of highlight functions obfuscated and harder than necessary.

Is this intentional or just an old version?

**Comment by timacdonald** [comment]
Its the build/minification build process. It makes the final production version as small as possible to help with file size, thus a function name
`doSomeFancyThing()` can become `s()`
Its only meant to be computer readable, if you wanna work pn the actual readable code you will want to, as you mentioned, view the code on github (which needs to be compiled before you can use it)

**Comment by timacdonald** [comment]
So to actually answer your question, its by design :)

**Comment by Sannis** [comment]
@mossarelli, yes, this is by design. If you want to change or add new language you should clone this repository, write code and build it into library. Some docs: http://highlightjs.readthedocs.io/en/latest/building-testing.html.
