### ISSUE TITLE
Lua library and meta methods undefined

### ISSUE THREAD

**Issue by mossarelli** [isagalaev/highlight.js#1399]
https://github.com/isagalaev/highlight.js/blob/master/src/languages/lua.js

```
keywords: {
  keyword:
    'and break do else elseif end false for if in local nil not or repeat return then ' +
    'true until while',
  built_in:
    '_G _VERSION assert collectgarbage dofile error getfenv getmetatable ipairs load ' +
    'loadfile loadstring module next pairs pcall print rawequal rawget rawset require ' +
    'select setfenv setmetatable tonumber tostring type unpack xpcall coroutine debug ' +
    'io math os package string table'
}
```
true and false are bools, nil is absent value. They should have different CSS-styles and highlighter should mark them as:
`<span class="hljs-literal">true</span>`
or:
`<span class="hljs-bool">true</span>`

There's also multiple keywords missing from the list, including meta methods and library methods.

Here's a good start including the table, string and math libraries:
`built_in: "_G _ENV _VERSION __index __newindex __mode __call __metatable __tostring __len __gc __add __sub __mul __div __mod __pow __concat __unm __eq __lt __le assert collectgarbage dofile error getfenv getmetatable ipairs load loadfile loadstring module next pairs pcall print rawequal rawlen rawget rawset require select self setfenv setmetatable tonumber tostring type unpack xpcall coroutine debug io math abs acos asin atan ceil cos deg exp floor fmod huge max maxinteger min mininteger modf pi rad random randomseed sin sqrt tan tointeger ult os clock date difftime execute exit getenv remove rename setlocale time tmpname string byte char dump find format gfind gmatch gsub len lower match rep reverse sub upper table concat insert maxn pack remove sort unpack"`

I did not get _library.method()_ to render properly so I split the methods and library names up.

**Comment by timacdonald** [comment]
Nice! This should be a pull request, as you have the solution. Put one together so everyone can benifit

**Comment by mossarelli** [comment]
Made a pull request.
I will add the remaining libraries to the file after I've dug them out.
This was my first pull request, merge and commit on github. If something is wrong, teach me what I am supposed to do.

**Comment by mossarelli** [comment]
Does the HLJS use regexp for keywords? And if so, does the period character have to be escaped with backslash in order to work?

**Comment by mossarelli** [comment]
Lua is now up to date with 5.2 because of:
https://github.com/isagalaev/highlight.js/pull/1414

Enjoy.
