### ISSUE TITLE
Some languages (fe. x86asm and Haskell) won't highlight while the common languages work.

### ISSUE THREAD

**Issue by sevaho** [isagalaev/highlight.js#1413]
Hello

I'm having some trouble with figuring out why some less common (other) languages won't highlight.
So I have downloaded all the languages that are supported and are in the languages folder, however the languages who are categorised as other [https://highlightjs.org/download/] don't highlight.

My code:

```
<link rel='stylesheet' href='libs/styles/default.css'> 

<pre><code class="language-x86asm">
[org 0x7c00] 

mov ah, 0x0e ; BIOS teletype function
mov al, 'A'

loop:
  int 0x10 ; Print al
  add al, 0x01
  cmp al, 'Z'
  jle loop ; Only jump when lower or equal

jmp $ ; endless jump

times 510-($-$$) db 0
dw 0xAA55
</code></pre>

<pre><code class="language-haskell">
{- Multiple line
comment -}

--One line comment
</code></pre>

<script src='//cdn.jsdelivr.net/highlight.js/9.9.0/highlight.min.js'></script>  
hljs.initHighlightingOnLoad();

```

x86asm.js and haskell.js located in the languages folder.

**Comment by isagalaev** [comment]
You can either get a one-file custom package or link to individual languages from CDN [as described in the README][1]. If, as I'm assuming, you downloaded the raw language files from GitHub, they won't do any good, as they have to go through a build process to be hooked up to the main library.

[1]: https://github.com/isagalaev/highlight.js#getting-the-library

**Comment by sevaho** [comment]
Thank you very much makes it all clear now!
