### ISSUE TITLE
Can't run tests on Windows 10

### ISSUE THREAD

**Issue by KasMA1990** [isagalaev/highlight.js#1419]
I cloned the repository, ran `npm install`, `node tools/build.js`, and `npm test`.

The tests fail to run with the error `Cannot find module '../../build'`, when `require`ing (what I assume is) the build output. If I manually change all the paths from `../../build` to `../../build/highlight.pack.js` then the tests will run, but I get test failures because `hljs.IDENT_RE` is undefined.

I'm using node v6.9.4 and npm v4.1.1, running on Windows 10. I don't have another environment on hand to test on unfortunately.

**Comment by sourrust** [comment]
You need to build for node since the default build type is for the browser.

```
node tools/build.js -t node
```

https://highlightjs.readthedocs.io/en/latest/building-testing.html

**Comment by KasMA1990** [comment]
Oh darn, I missed that there were different targets. I might try and do a PR to the docs to make it clearer.

Thanks for the tip :)
