### ISSUE TITLE
Add support for Google Closure Templates (Soy)

### ISSUE THREAD

**Issue by zenorocha** [isagalaev/highlight.js#1448]
Hello,

First of all, I just wanted to say that I love highlight.js and I appreciate all the work you guys have done here.

Secondly, I would like to suggest adding support to [Google Closure Templates (aka Soy)](https://developers.google.com/closure/templates/). There are few implementations out there that could serve as inspiration, such as:
* [CodeMirror](https://github.com/codemirror/CodeMirror/tree/master/mode/soy)
* [Sublime Text](https://github.com/Medium/soy-sublime)
* [Textmate](https://github.com/anvie/SoyTemplate)
* [Vim](https://github.com/duganchen/vim-soy)
* [IntelliJ IDEA](https://github.com/evenaglia/Non-Dairy-Soy-Plugin)

Unfortunately I don't have the expertise to implement this, but if there's anyone reading this that has we would appreciate a lot your contribution.

**Comment by jbalsas** [comment]
Just FYI, I'm working on it, @zenorocha!

**Comment by zenorocha** [comment]
Thanks @jbalsas!

**Comment by jbalsas** [comment]
I just sent https://github.com/isagalaev/highlight.js/pull/1526 with at least some basic support
