### ISSUE TITLE
making highlight.js non-node friendly

### ISSUE THREAD

**Issue by eman1986** [isagalaev/highlight.js#1473]
I'm using npm to grab all of my dependencies and when I try to grab this package it looks like the code is optimised for using on node as I keep getting the error message 

> module is not defined

I'd really prefer to not have to download it manually but looking like I may have to, hoping maybe you could steer me in the right direction.

Thanks

**Comment by isagalaev** [comment]
The package that is hosted on npmjs is indeed node-specific. We try not to support the entire multitude of packaging solutions ourselves, but there is a third-party project that does it: https://github.com/components/highlightjs
