### ISSUE TITLE
Please remove lodash from dependencies

### ISSUE THREAD

**Issue by bORm** [isagalaev/highlight.js#1479]
Subj,
please use only needed lodash methods

```javascript
import _ from 'lodash';
_.map()
```

You can use as
```javascript
import map from 'lodash.map';


```

**Comment by sourrust** [comment]
There is no point to this. The main reason people would change to including specific sub-modules from lodash is size, but lodash is only being used on the development side of highlight.js -- the build tools and tests. The core highlight.js library has no dependencies so switching to sub-modules of lodash would only make development a bit inconvenient as we are currently using about 24 different functions and maybe we would include more or less in the future.

Here are the functions I found:

* compact
* defaults
* each
* filter
* find
* head
* includes
* isEmpty
* isString
* last
* map
* merge
* method
* partial
* partition
* range
* reduce
* slice
* some
* some
* startCase
* tail
* template
* transform
