### ISSUE TITLE
Add a name alias for a language

### ISSUE THREAD

**Issue by ararslan** [isagalaev/highlight.js#1500]
Is it possible to add an alias to a language definition, i.e. saying that X should use the definition for Y? In particular, for the documentation generator used for Julia, Markdown code blocks labeled `jldoctest` rather than `julia` are used to run tests in the documentation. All blocks labeled `jldoctest` are Julia code, so it would be great to be able to take advantage of the existing Julia highlighting definition, but currently `jldoctest` is unrecognized so no highlighting is added. Is it possible to achieve this without duplicating the Julia definition?

**Comment by isagalaev** [comment]
Yes :-)

**Comment by ararslan** [comment]
Fantastic! Thanks so much!!!
