### ISSUE TITLE
Highlight Auto breaking on multiple periods

### ISSUE THREAD

**Issue by geekgonecrazy** [isagalaev/highlight.js#1505]
Running across an odd issue.  

If we do: `highlightjs.highlightAuto('I ..');` the browser tab completely locks up.  We're on the latest version of highlightjs 9.11.0

https://runkit.com/590140aeafa0170012b6169c/590141941ce99600127a433b

A single period seems to work fine.  But multiple breaks and if no space before it it also works fine.

Also oddly seems to be a single char space and then multiple periods.  If you do multiple letters first its a no go.

`<letter>+<space>+..`

**Comment by isagalaev** [comment]
Thanks for reporting this! Our parser is indeed susceptible to such things if not handled carefully. Fixed.

**Comment by geekgonecrazy** [comment]
@isagalaev No problem thanks for the quick fix! :+1:

**Comment by isagalaev** [comment]
Also, until the next version of highlight.js is released you can either [build yourself a copy from master][b] or explicitly [list all the language you need for auto highlighting][c], so the offending language ("gams") is not included.

[b]: http://highlightjs.readthedocs.io/en/latest/building-testing.html
[c]: http://highlightjs.readthedocs.io/en/latest/api.html#highlightauto-value-languagesubset

**Comment by rodrigok** [comment]
@isagalaev Are you planing to release the next version soon? Or maybe some alfa version?

This fix is very important to us at Rocket.Chat and we don't want to release a new NPM package just to get this fix in our next version.

Can we help you in some way?

Thanks

**Comment by isagalaev** [comment]
Our upcoming release date is Tuesday May, 30 (we do it every 6 weeks). In the meantime you can always build a custom version for yourself from master: http://highlightjs.readthedocs.io/en/latest/building-testing.html
