### ISSUE TITLE
Need parser for query strings.

### ISSUE THREAD

**Issue by ethaniel** [isagalaev/highlight.js#1512]
Hello!

I think it would be a good addition to highlightjs, if we code colourize query strings.
For example, if I put a URL into a box: `https://github.com/isagalaev/highlight.js/issues/new?query1=1&query2=2` - it would be cool if query1 & query2 would be different colours from their values.

This way if I am building a manual, readers would easily understand what parameters are used in a URL.

**Comment by isagalaev** [comment]
Yes, it would be useful. Pull requests are welcome! http://highlightjs.readthedocs.io/en/latest/language-requests.html
