### ISSUE TITLE
Incorrect syntax highlighting in Rust raw strings

### ISSUE THREAD

**Issue by budziq** [isagalaev/highlight.js#1527]
Hi,

This is a direct copy of bug https://github.com/azerupi/mdBook/issues/269 (mdBook which uses highlight.js directly).
> The code formatting for many of the snippets 'breaks' when it sees quote-pairs inside raw strings 
> `r#"like "this" eg"#` , it would unhighlight the word `'this'`.

I have checked against the latest highlight.js 9.11.0 and the problem still persists.
The effect can be seen live on:
https://brson.github.io/rust-cookbook/encoding.html#serialize-and-deserialize-unstructured-json
![2017-05-23-184301_1366x768_scrot](https://cloud.githubusercontent.com/assets/221000/26365430/e1c5e5da-3fe7-11e7-9f10-afdbd22e3ec6.png)

**Comment by isagalaev** [comment]
Fixed. Thanks for catching it!

**Comment by budziq** [comment]
Wow that was quick! Thanks a lot :)

**Comment by isagalaev** [comment]
It was a straightforward bug in a language I happen to know :-)
