### ISSUE TITLE
HTML is detected as Javascript with auto highlighting on

### ISSUE THREAD

**Issue by flagbug** [isagalaev/highlight.js#1544]
Take the following super-small code snippet that I want to highlight: `<iframe></iframe>`

In order to also highlight possible embedded Javascript and CSS, I'm calling the following:

```js
hljs.highlightAuto(code, [ "javascript", "html", 'css' ]);
```

Expected result: Detected and highlighted language is `html`
Actual result:  Detected and highlighted language is `javascript`

If I change the code to

```js
hljs.highlightAuto(code, [ "html", 'css' ]);
```

it seems to work fine

**Comment by isagalaev** [comment]
Normally I'd suggest that due to small size of the snippet you can't rely on heuristics anyway, but here it actually demonstrated one thing we could do better. Thanks for catching it :-)

**Comment by flagbug** [comment]
@isaglaev Wow, thanks for the super quick fix and response, awesome! 💯
