### ISSUE TITLE
There is no distributables in the repository.

### ISSUE THREAD

**Issue by lewisgoddard** [isagalaev/highlight.js#1591]
jsDelivr is moving to a system where they load directly from GitHub releases, no need for packages submissions. Unfortunately this requires a CDN distributable version in the repository. This is the only way for jsDelivr to get updated versions, and I would really like to continue serving from there.

Ref: https://github.com/elementary/website/pull/1795

**Comment by MartinKolarik** [comment]
Fyi, jsDelivr can also fetch files from npm (which is actually the preferred way). It seems there's already [a UMD build](https://cdn.jsdelivr.net/npm/highlight.js@9.12.0/lib/highlight.js) in the npm package, but the language files are only available in cjs format.

**Comment by isagalaev** [comment]
I don't watch highlight.js GitHub very closely these days, but this caught my attention, and it has a simple answer. We have a separate repo with CDN-specific builds published for every release: https://github.com/highlightjs/cdn-release

It's been working fine, but for the past few releases jsDeliver apparently had some problems updating from it. No idea what problems, though, I didn't pay much attention.

**Comment by lewisgoddard** [comment]
They've deprecated the old way so the website isn't showing latest versions anymore. The latest version is available at https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@9/build/highlight.min.js

**Comment by isagalaev** [comment]
Oh, thanks. Updated the links on the site.
