### ISSUE TITLE
A question about activity

### ISSUE THREAD

**Issue by revosw** [isagalaev/highlight.js#1670]
Hey @isagalaev, I see you haven't had any activity since one contribution at 17th october, and before that june 14th. I'm by no means trying to rush you, and I understand that stuff happens in life. However I was just curious, and wanted to ask for a little status update on how you're doing?

**Comment by thomas-mc-work** [comment]
Have a look at here: #1678

**Comment by revosw** [comment]
Ah, thanks for the heads up man
