### ISSUE TITLE
How to get highlight.pack.js?

### ISSUE THREAD

**Issue by zhouxy666** [isagalaev/highlight.js#1706]
highlight.js can not work in my project. I know it need to build to highlight.pack.js ,but how?

**Comment by idleberg** [comment]
Reading the [documentation](http://highlightjs.readthedocs.io/en/latest/building-testing.html) usually helps 😉

**Comment by zhouxy666** [comment]
I have solved the problem by reading the documentation,it is really helpful,thanks a lot!

**Comment by fhwedel-hoe** [comment]
I might be a sorry case, but I fail to see how this helps. The documentation does not say anything about "[pack](https://highlightjs.readthedocs.io/en/stable/search.html?q=pack&check_keywords=yes&area=default)" single-file distribution.

https://highlightjs.org/download/ gives me a zip file containing a bunch of files and no clear indication of how to merge them into one.

**Comment by joshgoebel** [comment]
Where does it still say pack?

**Comment by fhwedel-hoe** [comment]
Nowhere in the current documentation, and everywhere in the old projects I am currently tending to. That was my problem. I expected https://highlightjs.readthedocs.io/en/latest/upgrade-11.html to mention something like this: 

>`highlight.pack.js` is no longer being shipped. It has been superseeded by `highlight.min.js`.

For the folks who maintain highlight.js, this change may seem obvious. To me who is only using it, checking in once in a couple of years, it is not.

**Comment by joshgoebel** [comment]
Did it change from 10 to 11, I forget?  I'd be fine with a PR adding that to the upgrade docs.

**Comment by joshgoebel** [comment]
> the method of distribution at https://highlightjs.org/download. 

Ah, the old website did use `pack` a bit longer, an oversight.  Everywhere else (docs, GH, packaging, etc) has used `min` for quite some time and also the new website (maybe even the old one was fixed for quite some time, I can't remember).
