### ISSUE TITLE
Working directory tree highlighting

### ISSUE THREAD

**Issue by ozlerhakan** [isagalaev/highlight.js#680]
Hi @isagalaev,

Probably, this purpose will not be provided by highlight.js since it deals with concrete language definitions. Considering this case, we just created a new language definition for tree structures. Perhaps, anyone can make use of it and contribute: https://github.com/asciidocfx/highlight-treeview.js

**Comment by Sannis** [comment]
Looking deeper this cannot be simply merged now due to data URLs for icons. Maybe we can come back after styles reorganisation in #348.

**Comment by isagalaev** [comment]
Just to confirm, I also think it would be useful to have it as a language: people do often display directory structures along with code snippets. I don't have an easy solution as to where put those icons either. They probably have to live in a separate style and we could document it somewhere.

**Comment by Sannis** [comment]
Yes, we can look how this language looks without any styles and make decision.

Anyway, I'll not close any issues with `on hold` label.

**Comment by isagalaev** [comment]
So… I was thinking about this idea lately and it still feels to me like a bit of a stretch to bundle a very special case with a very special CSS along with the library. So I think we could just live with it being a nice derivative project until a better idea comes up.

@ozlerhakan thanks for doing this anyway!

**Comment by ozlerhakan** [comment]
Np @isagalaev , You're welcome!
