### ISSUE TITLE
C++ highlighting breaks on "else if"

### ISSUE THREAD

**Issue by pwmarcz** [isagalaev/highlight.js#690]
Sample code:

    int main() {
        int a = 2;
        if (a == 2)
            return 3;
        else if (a == 3)
            return 4;      
        else
            return 5;
      }

It seems that the second `if` is treated as function name (`hljs-title`), and `return 4;` as function parameters (`hljs-params`).

(See http://codepen.io/anon/pen/MYjLex for live example).

**Comment by Sannis** [comment]
`else if` is one of the few constructions that may be a function definition that looks like `<type> <name>`. My fists try was to iilegalize it in function mode:
```
diff --git a/src/languages/cpp.js b/src/languages/cpp.js
index 3418788..6a543d6 100644
--- a/src/languages/cpp.js
+++ b/src/languages/cpp.js
@@ -83,6 +83,7 @@ function(hljs) {
       {
         className: 'function',
         begin: '(' + hljs.IDENT_RE + '\\s+)+' + hljs.IDENT_RE + '\\s*\\(', returnBegin: true, end: /[{;=]/,
+        illegal: /else if/,
         excludeEnd: true,
         keywords: CPP_KEYWORDS,
         contains: [
```
but it does not work. Is it expected, @isagalaev?

**Comment by isagalaev** [comment]
`illegal` is a nuclear option: it will drop any attempt at highlighting the language further, so yeah, it's not what we need here. One thing I could suggest is having a dummy mode like `{begin: /\belse\s+if\b/, keywords: CPP_KEYWORDS}`, or something like that… Could you play with this approach? Or I can look at it myself when time allows…

**Comment by monoidal** [comment]
I'm confused by this fix. Isn't the same with, say, `else for` or `else while` or `else /* comment */ if`? I would expect the keywords to be always highlighted, independently of whether they are after an `else` or not.

**Comment by isagalaev** [comment]
@monoidal ah yes, you are correct. Actually I think that special-casing just `else` would suffice. Let me check…
