### ISSUE TITLE
Wrong highlighting in <script> bodies where content is not javascript

### ISSUE THREAD

**Issue by balinterdi** [isagalaev/highlight.js#695]
It seems to me that in some cases, the language of a `script` tag is incorrectly assumed to be javascript although the type attribute explicitly defines it as something else.

The case at hand is:

    ``` html
    <!DOCTYPE html>
    <html>
    <body>
    <script type="text/x-handlebars">
      <!-- Handlebars body highlighted as javascript -->
    </script>
    </body>
    </html>
    ```

The html output generated from the `script` tag above has `class="javascript"` which results in incorrect highlighting (handlebars template highlighted as javascript code).

I think the type attribute should be taken into consideration and the body of the `script` tag highlighted as such.

**Comment by Sannis** [comment]
Maybe we should use auto highlighting for `<script>` tag content.

**Comment by balinterdi** [comment]
If that means that the body of the <script> tag will be auto-detected, I agree that is the way to go.
