### ISSUE TITLE
Demo Language Categories: shows the right frame at odd positions

### ISSUE THREAD

**Issue by eksperimental** [isagalaev/highlight.js#697]
visit https://highlightjs.org/static/demo/
and start click on the language categories,
it doesn't take you to the top.
you end up reading one category, and then you click on the left sidebar another category, but you don't got to the top, but to the bottom of that page,
weird.

**Comment by eksperimental** [comment]
sorry, but i don't see the changes reflected in the site.

**Comment by auge8472** [comment]
To fix the bug in the repo doesn't mean nessecary to update the website at the same time. :-)

**Comment by eksperimental** [comment]
well, it's been 20 days.. anyway

**Comment by eksperimental** [comment]
well, the changes were added to the highlight.js project, not to the website, I can understand now why they are not reflected, not until a new version is released
