### ISSUE TITLE
Wrongly identify emacs lisp into bash, v8.4

### ISSUE THREAD

**Issue by redguardtoo** [isagalaev/highlight.js#699]
See,
http://blog.binchen.org/posts/how-to-validate-html5-code-with-flymake-effectively.html

My question is, since I already specify the language with "lang-lisp", can you use lisp without auto language detection at the beginning unless the language I specified is not defined?

**Comment by Sannis** [comment]
It looks like you uses highlight.min.js without lisp language included:

```
> hljs.getLanguage('lisp')
undefined
> hljs.getLanguage('bash')
Object {aliases: Array[2], l: /-?[a-z\.]+/, k: Object, c: Array[8], compiled: true…}
```

**Comment by redguardtoo** [comment]
It is from cdnjs. Can I still use cdnjs?

**Comment by isagalaev** [comment]
Yes, if you only need a couple of additional languages, just include those as separate scripts after the main one:

```html
<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/8.4/highlight.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/8.4/languages/lisp.min.js"></script>
```

If you need a dozen though, I'd recommend building your own package as requesting multiple scripts works slower.

**Comment by redguardtoo** [comment]
Thanks
