### ISSUE TITLE
Add a plain/text highlighter that does not highlight.

### ISSUE THREAD

**Issue by ePirat** [isagalaev/highlight.js#700]
This may sound weird at first, but I consider it actually really useful. There are a lot of projects using highlight.js (even some markdown apps on OS X) but there seems to be no way to have a code block unhighlighted. Customizing the css to achieve this, is some of the cases is not easily possible. So I would love to see a text  or plaintext highlighter that does not highlight at all.

**Comment by ePirat** [comment]
Ok, `no-highlight` did the trick… (Maybe text should be added as an alias for it)
The only problem I have now is that the theme broke, because the code has no hljs class anymore, but that's not really a highlight.js issue.

**Comment by isagalaev** [comment]
> Maybe text should be added as an alias for it

Already done in e278472b8.

BTW, to my personal liking the best way to have unhighlighted piece of computer output is to mark it up as `<pre><output>..</output></pre>`.

**Comment by ePirat** [comment]
:+1: Thanks, I wasn't aware that there is an `<output>` html tag!

**Comment by auge8472** [comment]
On the level of semantic the use of `<output>` at this point is not correct. [It's defined](http://dev.w3.org/html5/spec-preview/the-output-element.html) as the output of a calculation.

**Comment by ePirat** [comment]
It seems [`<samp>`](http://dev.w3.org/html5/spec-preview/the-samp-element.html#the-samp-element) would be the right thing to use in this case.
