### ISSUE TITLE
Highlight Java Enums and Constants

### ISSUE THREAD

**Issue by reinert** [isagalaev/highlight.js#702]
Enums and Constants in Java are conventionally written in uppercase letters. HLjs currently doesn't highlight such pattern.

A live example can be seen here: http://reinert.io/requestor/latest/examples/showcase/#building-requests (go down to Response Type  topic)

**Comment by Sannis** [comment]
None languages supported by highlight.js defines modes for constants, it's by design. We try to keep modes list minimum to simplify custom styles support: https://github.com/isagalaev/highlight.js/issues/348#issuecomment-58228366
