### ISSUE TITLE
Ft. Request: Add isHighlighted function to hljs object

### ISSUE THREAD

**Issue by webketje** [isagalaev/highlight.js#708]
Would it be possible to add an `hljs.isHighlighted` function to check whether the code is currently highlighted? (so as not to reperform). Not only as a JS property changed after initiation, but also by truly checking the DOM, as eg. Chrome tabs seem to preserve some tab state. I'm thinking something like: 

```js
 // if no param provided, checks first element, else param element
 function isHighlighted(element) {
     var code = element ? element : document.getElementsByTagName('code')[0];
     if ( code && code.className.match('hljs'))  
         return true;
     else 
         return false;
 };
```

**Comment by webketje** [comment]
Update on this: it wasn't Chrome; it is pages loaded with AJAX (for example when navigating articles on [Medium](http://medium.com)). They change the main content (with highlighted codeblocks) so a built in function would come in handy to 'dirty-check' the DOM and re-highlight when necessary. 
<br> This could be done with a simple `setInterval` call that toggles a `hljs.isHighlighted` boolean , which could be optionally enabled in the options passed to `configure`

**Comment by isagalaev** [comment]
Why not just check for "hljs" class name? I don't think a whole API function is warranted for such a simple thing… Or am I missing something?
