### ISSUE TITLE
PHP static call to class not highlighted

### ISSUE THREAD

**Issue by VladShcherbin** [isagalaev/highlight.js#711]
If we have a static call to the class, the class name is not highlighted nor identified.
e.g.
```
echo Guy::doSomething();
```

The class name `Guy` is not identified.

The same from the examples page.
![screen shot 2015-01-14 at 07 37 10](https://cloud.githubusercontent.com/assets/6711845/5734144/46e8d96e-9bc0-11e4-8f4f-e79c57a6a852.png)

**Comment by isagalaev** [comment]
Upon looking at this closely I can say that it's actually how it's supposed to work: we only highlight identifiers at a place where they're defined, not everywhere. If I've misunderstood the problem (which is totally possible), please reopen this with a further explanation.
