### ISSUE TITLE
No highlighting for Haskell type signatures

### ISSUE THREAD

**Issue by MatthewJA** [isagalaev/highlight.js#713]
Syntax highlighting for Haskell doesn't seem to highlight type signatures. GitHub highlights like this, for comparison:

```Haskell

main :: IO ()
main = putStrLn $ hello

hello :: String
hello = "hello" ++ "world"
```

...but as far as I can tell, the only highlighting for Haskell is on keywords and strings.

(Additionally, there's no highlighting for infix operators like `$` or `+` --- Sublime (for example) highlights these --- but as they're technically functions, would I be right in assuming that that's a design decision? There's also no highlighting for `=`, which probably should be highlighted.)

**Comment by isagalaev** [comment]
@sourrust happens to be our Haskell expert so I'll trust his judgment on usefulness and feasibility of implementing it.

(We don't highlight single-letter operators as a general rule, it makes for a really noisy highlighting.)

**Comment by sourrust** [comment]
I'm not sure which style you are using, but there are some styles that don't implement the css classes for `hljs-type` and `hljs-title` -- which are the two classes used inside of type signatures. With a quick search I see 23 of the 50 that actually have Haskell type classes defined to a color.

If you want to sent in a pull request to fix it for the style you are using you can and it is welcome. However with there being 27 styles missing a color, specifically for types, I currently don't have the time to look up the set color for each style.

**Comment by MatthewJA** [comment]
Ah, cool, maybe that's the problem then! I'm happy to investigate that and send a pull request if need be.

**Comment by MatthewJA** [comment]
So I tested some things out, and it seems that the indentation in front of the code was making it not highlight. If I remove that indentation, it works fine, so this isn't a problem after all.
