### ISSUE TITLE
highlightAuto just returns an escaped string

### ISSUE THREAD

**Issue by Robdel12** [isagalaev/highlight.js#715]
I've been trying to get Highlight.js to play nicely with marked pretty much all day and I can't seem to get it to work. 

I think this picture pretty much sums it up. 
![screen shot 2015-01-22 at 9 29 39 pm](https://cloud.githubusercontent.com/assets/2072894/5868863/f362a1f2-a27d-11e4-8ae0-0b9822641a1a.png)

I don't know what I'm doing wrong. Any help would be appreciated!

**Comment by isagalaev** [comment]
What does `hljs.listLanguages()` say?

**Comment by Robdel12** [comment]
```javascript
> hljs.listLanguages()
<- ["cpp", "ruby", "apache", "python", "javascript", "coffeescript", "http", "scss", "css", "ini", "objectivec", "bash", "markdown", "java", "diff", "perl", "makefile", "cs", "json", "nginx", "sql", "xml", "php"]
```

**Comment by isagalaev** [comment]
Can't say anything from the top of my head so I'll try to figure out what's wrong. Could you also post this code sample as text so I won't have to re-type it for testing :-).

**Comment by Robdel12** [comment]
Hm. I replaced the version of Highlight.js I had from bower with a build and it works now. :D

**Comment by isagalaev** [comment]
Oh, that explains it then. Bower package is actually a third-party effort, we have no idea how it's maintained.

**Comment by Robdel12** [comment]
Hah, interesting. I'm probably going to pack this up with marked and make an Ember CLI addon. Thanks for the direction!

**Comment by Robdel12** [comment]
@isagalaev what would cause hljs.listLanguages() to return empty?

**Comment by isagalaev** [comment]
Languages have to be registered with the library. The build process generates code calling `hljs.registerLanguage(...)` for every language included in the build. If you just wrap the unbuilt code into some package the library won't know anything about the languages.

**Comment by Robdel12** [comment]
I see now. I'm trying to build an Ember CLI addon that includes highlight.js. Ember CLI requires things that are included with broccoli to be bower packages. 

Were there any technical or any other reasons why this isn't published to bower?

**Comment by Robdel12** [comment]
Maybe I should dig a little before commenting :P 

`"highlightjs": "~8",` works in my bower.json

**Comment by isagalaev** [comment]
> Were there any technical or any other reasons why this isn't published to bower? 

I really should have it explained somewhere, it's a very common question :-). The thing is, we don't want to play the game of supporting every packaging system out there as they seem to emerge and die at an ever-increasing rate. Instead, we keep the source relatively free of complications and encourage people to maintain packages in whatever format downstream. The only two packages we do support are the browser because we have to serve something from the site and the node.js because we use it for testings anyway.
