### ISSUE TITLE
Constructor undefined when building highlight

### ISSUE THREAD

**Issue by k33g** [isagalaev/highlight.js#716]
Hello

I try to add a new language:

    /*
    Language: Yo
    */

    function(hljs) {
      return {
        aliases: ["yolang"],
        keywords: {
          keyword:"yo yo!"
        }
      };
    }

but when I try to build it: `node tools/build.js yo`, I've got this error:

    Starting build.
    Copying documentation.
    Generating demo.
    Building highlight.js pack file.
    Writing documentation.

    /Users/k33g_org/Dropbox/Public/highlight.js/tools/tasks.js:219
            blob = new blob.constructor(blob.result, meta);
                           ^
    TypeError: Cannot read property 'constructor' of undefined
        at addMeta (/Users/k33g_org/Dropbox/Public/highlight.js/tools/tasks.js:219:24)
        at /Users/k33g_org/Dropbox/Public/highlight.js/node_modules/gear/lib/blob.js:75:21
        at fs.js:208:20
        at Object.oncomplete (fs.js:108:15)

Any idea?
If I want to build an already existing language like go, it's ok.
I work with node v0.10.35

regards
Philippe

**Comment by isagalaev** [comment]
It may be caused by outdated dependencies (even though it doesn't explain why existing languages do get built). Can you make sure it still happens after `npm update`?

**Comment by isagalaev** [comment]
Nope, I'll take it back. I just reproduced this error locally, so I'll have a look now.

**Comment by isagalaev** [comment]
Okay, so the problem is that you're supposed to also have a file with the test snippet for the languages located in "test/detect/yo/default.txt" that is used to build the demo page along the library. But we really need to fix the obscure error reporting here.

**Comment by k33g** [comment]
Thank you very much for the response :)

**Comment by isagalaev** [comment]
Fixed. To clarify, the test snippet is still required for the tests to pass, I just made it so the browser build doesn't crash if you hadn't yet a chance to create one.

**Comment by k33g** [comment]
Fine, it runs :+1:

**Comment by isagalaev** [comment]
btw, I don't want to create an impression that we always react on bugs this fast :-) It's pure luck :-)

**Comment by k33g** [comment]
:)
