### ISSUE TITLE
Improper syntax highlighting for multiple line preprocessor

### ISSUE THREAD

**Issue by candronikos** [isagalaev/highlight.js#720]
Multi-line preprocessor defines are not following the backslash properly:

#define TYPES(_) \
  _(double, x) \
  _(double, y) \
  _(double, z) \
  _(double, w)

The top line renders as expected but the rest don't

**Comment by Sannis** [comment]
So bad that Javascript does not natively support lookbehind matches to do this without hacks...

**Comment by isagalaev** [comment]
This is C++, right?

**Comment by isagalaev** [comment]
OK, I went ahead and fixed that in cpp.js. Feel free to reopen if I did a blunder in that :-)
