### ISSUE TITLE
Freezes on auto language detection

### ISSUE THREAD

**Issue by kelunik** [isagalaev/highlight.js#733]
highlight.js doesn't process long words very well on language detection.

Here's a simple reproduce script:
```js
var hljs = require("highlight.js");
console.log(hljs.highlightAuto(process.argv[2]).value);
```
Just run it with
```bash
node test.js aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
```

This will take very long if you add more `a`s and very quickly just continues forever. It only happens with all languages enabled, not with only the common ones.

**Comment by isagalaev** [comment]
We recently fixed a couple of bugs that were manifesting in the same way, and right now I can't reproduce the bug with your example running it with the master code. Could you check it with the master too?

**Comment by kelunik** [comment]
It doesn't seem to be fixed with current master.

```bash
node test.js aaaaaaaaaaaaaaaaaaaaaaaaaaa
```

This one seems to be the first one that takes really long.

**Comment by isagalaev** [comment]
Could it be that `require("highlight.js")` imports the latest released version installed from npm on your machine? To use the version built from the current master this line should be `require("./build")` or something.

**Comment by kelunik** [comment]
Yes, you're right. It's fixed, thanks.
