### ISSUE TITLE
[NFR] Added support for Zephir Language

### ISSUE THREAD

**Issue by ovr** [isagalaev/highlight.js#736]
Hi ;)
First thanks contributors for this library :smiley: 

https://github.com/phalcon/zephir

This will be similar for PHP
but without `<?php` open tags, `$` for variables

Can anyone help with it?

**Comment by ovr** [comment]
@Sannis Any news? It's rly important. For upcomming conference
Thanks

**Comment by ovr** [comment]
@Sannis ping

@isagalaev Can you help?

**Comment by isagalaev** [comment]
Can't speak for @Sannis what he meant by assigning this to himself but generally we don't take requests on implementing languages, instead we accept implementations from contributors (http://highlightjs.readthedocs.org/en/latest/language-requests.html). In any case, we're all volunteers here and don't adhere to any time schedule.

**Comment by Sannis** [comment]
PHP detection depends on PHP-specific things like $-started variables. I've stat working on it but currently I have many test broken :-(

**Comment by ovr** [comment]
Парни вопрос жизни или смерти
Даже 1С есть, прошу молю :smiley_cat:

**Comment by Sannis** [comment]
Fixed in #793.
