### ISSUE TITLE
Highlight with different background specified line(s) in source code

### ISSUE THREAD

**Issue by szpak** [isagalaev/highlight.js#740]
In some cases it is very useful to be able to highlight specified line(s) in source code by giving them other background (e.g. yellow).

The mentioned effect achieved with remark.js: http://jsfiddle.net/szpak/059x3ygs/1/, but I think it would be good to have it in highlight.js itself.

**Comment by Nedudi** [comment]
+1

**Comment by szpak** [comment]
As a bonus it would be great to have an ability to highlight only a part of given line.

**Comment by isagalaev** [comment]
It is already possible without any changes to highlight.js: just use normal HTML markup to highlight whatever you need in your code.

**Comment by isagalaev** [comment]
btw, @Nedudi, most engineers would automatically *demote* an issue to the very end of their priority queue after receiving useless "+1" on that. Kindly please don't do that anymore anywhere.

**Comment by isagalaev** [comment]
So, to summarize. I don't want to introduce any custom syntax within highlight.js to adorn source code for a few reasons:

- Inventing a new syntax compatible with various markup languages out there is mighty hard, and it will be a source of bugs and surprises for users who don't expect parts of their source code to be treated in a special way.
- Implementation of such a syntax will add a whole new dimension of complexity to highlight.js.

Since highlight.js already can work with custom HTML markup, such a syntax is best left to the specialized markup processor that produces it.

**Comment by devurandom** [comment]
@isagalaev Could you please give an example of how to do this? From your answer I assume there are some HTML/CSS elements, which I can place external to the <code> element, that influence the visual style. But how…?

I would assume/suggest some <code>.highlightLines(123,456) API, but I cannot find any such thing.

**Comment by tovic** [comment]
Something like this &rarr; http://jsfiddle.net/tovic/059x3ygs/2

**Comment by isagalaev** [comment]
@devurandom by "external" I mean external to the library, so there's no API for this. I mean that one can insert arbitrary markup inside the `<code>` element (or invent an extension to markdown that would do that) so it would look like:

```html
<pre><code><span class="odd">...</span>
<span class="even">...</span>
</code></pre>
```

And then you can call `hljs.highlightBlock` on this `<code>` element and highlight.js would keep those spans merging them with its own markup.

**Comment by devurandom** [comment]
Oh, I did not know that <code> blocks do not escape HTML tags inside. I assumed they would be printed literally.

**Comment by isagalaev** [comment]
It's probably the most wide-spread misconception about the `<code>` tag in HTML :-).

**Comment by TRSasasusu** [comment]
This issue has already been closed, but please let me announce to you.
I made a plugin highlighting specific lines.
https://github.com/TRSasasusu/highlightjs-highlight-lines.js

**Comment by triskweline** [comment]
> Since highlight.js already can work with custom HTML markup, such a syntax is best left to the specialized markup processor that produces it.

This no longer seems be a solution in current versions of Highlight.js (11.6.0). Highlight.js discards any HTML in the `<code>` element it is highlighting.

**Comment by triskweline** [comment]
Here is my crude solution for this in case someone Google this in the future.

My approach is:

- Look for comments containing the word `mark-line`.
- Wrap the entire line in a `<mark>` element
- Delete the comment containing `mark-line`

Our example is the Javascript snippet below, although it works with any language that has comments.

```js
foo()
bar() // mark-line
baz()
```

The default Highlight.js output for this snippet looks something like this:

```html
<span class="hljs-title">foo</span>()
<span class="hljs-title">bar</span>() <span class="hljs-comment">// mark-line</span>
<span class="hljs-title">baz</span>()
```

I now want to wrap the line with the `// mark-line` comment inside a `<mark>` element. We can do so by post-processing the HTML output from Highlight.js:

```js
hljs.highlightElement(fragment)

html = fragment.innerHTML

markedHTML = html.replaceAll(/^(\s*)(.+?)\s*<span class="hljs-comment">.*?\bmark-line\b.*?<\/span>$/mg, '$1<mark>$2</mark>')

// Only update the DOM if we made changes
if (html != markedHTML) {
  fragment.innerHTML = markedHTML
}
```

The processed HTML now looks like this:

```html
<span class="hljs-title">foo</span>()
<mark><span class="hljs-title>bar</span>()</mark>
<span class="hljs-title>baz</span>()
```

What's not optimal about this solution is that we reset the `{ innerHTML }` of the highlighted snippet, requiring the browser to parse the HTML and re-create DOM elements.

Hope this helps someone.

**Comment by TRSasasusu** [comment]
triskweline, thank you for notifying the update of Highlight.js, and providing alternative solution.
Now, I checked [highlightjs-highlight-lines.js](https://github.com/TRSasasusu/highlightjs-highlight-lines.js) works on Highlight.js v11.6.0.
Please check its DEMO.

**Comment by moubi** [comment]
Might be useful for someone working with **markdown** and wants line highlighting:

```
```javascript{3} -> highlights line 3
```jsx{3, 4} -> highlights lines 3 and 4
```html{3, 4, 20, 33} -> highlights several lines
```

Setup with [markedjs](https://marked.js.org/):

```javascript
import { marked } from "marked";
import hljs from "highlight.js";

marked.setOptions({
  renderer: new marked.Renderer(),
  highlight: function (code, language) {
    let linesToHighlight = [];

    // Detect if line highlighting is enabled for a given code block
    if (language.indexOf("{") > 0) {
      linesToHighlight = language
        .slice(language.indexOf("{") + 1, language.indexOf("}"))
        .split(",")
        .map(Number);

      // Extract the actual language back from something like "html {1,2,3}"
      language = language.slice(0, language.indexOf("{")).trim();
    }

    const validLanguage = hljs.getLanguage(language) ? language : "plaintext";
    let output = hljs.highlight(code, { language: validLanguage }).value;

    if (linesToHighlight.length > 0) {
      // Split code blocks in lines
      const codeByNewLines = output.split("\n");

      // Wrap each highlightable line with <mark></mark>
      linesToHighlight.forEach((n) => {
        n = n - 1;
        if (codeByNewLines[n]) {
          codeByNewLines[n] = `<mark>${codeByNewLines[n]}</mark>`;
        }
      });

      output = codeByNewLines.join("\n");
    }

    return output;
  },
});
```

Then styling `<mark>` elements it's up to you.

Sorry for the barebone look.

**Comment by joshgoebel** [comment]
That code is not correct as it doesn't account for tags in the highlighted content than span multiple lines... you can't just insert tags on a per-line basis without dealing with other tags that may already be open (and then close in the middle of the next line, etc)... it's not super hard, but it's more involved than a simple loop over the newlines.

**Comment by moubi** [comment]
@joshgoebel do you have a test or codesandbox with the use case for ref?

Trying something like 
```html
<span>Some multiline
content Some multiline
content</span>
```
from a markdown generated code works as expected.
But maybe I am missing something.

**Comment by joshgoebel** [comment]
> do you have a test or codesandbox with the use case for ref?

Your sample case is great - what would the output be in that case?  You can't just wrap the first line in `mark` because then mark closes before `span` does, which is invalid XML - even if some browsers will render it.

You have to rewrite the HTML to close and reopen the tags on every line:

```
<span>Some multiline</span>
<span>content Some multiline</span>
<span>content</span>
```

After that it's safe to do per-line whatever.

**Comment by moubi** [comment]
I've created a [codesandbox with the example](https://codesandbox.io/p/sandbox/weathered-fog-rtv032?file=%2FREADME.md).

All this happens in Node environment **not in the browser**.

We have markdown code
```
```jsx{2}
<span>Some multiline content 
Some multiline 
content</span>
```

that is parsed to `highlightjs` (by `marked.parse()`) as

```
<span>Some multiline content 
Some multiline 
content</span>
```

and in turn highlightjs outputs:

```
<mark>&lt;span&gt;<span class="hljs-title class_">Some</span> multiline content </mark>
<span class="hljs-title class_">Some</span> multiline 
content&lt;/span&gt;
```
___
Was the confusing part related to the assumption `highlightjs` outputs 

```
<span>Some multiline content 
Some multiline 
content</span>
```
?

**Comment by joshgoebel** [comment]
> Was the confusing part related to the assumption highlightjs outputs

That's what we DO output but more specifically (roughly):

```
"<span class=".hljs-string">Some multiline content 
Some multiline 
content</span>"
```

Now you can't just add `<mark>` tags willy nilly because sometimes you're inside the outer span and sometimes you aren't and the tags won't match.
