### ISSUE TITLE
Enteties not preserved

### ISSUE THREAD

**Issue by jdagerot** [isagalaev/highlight.js#743]
I found an issue about this from 2012 but it is actually bothering us.

We are building a site with some localized strings, for example words like "får, häst, ödla" 
    
    f&aring;r, h&auml;st, &ouml;dla

Above is the text with html enteties. We are doing this out of recommendation and that we've found that the character encoding is somewhat flaky within out rather huge development environment.

I would love to be able to not have highlight.js deentetize these entities in some way, could anyone maybe help where I should start?

Update, here's the older issue: https://github.com/isagalaev/highlight.js/pull/141

**Comment by isagalaev** [comment]
I'm not sure I understand the problem you're describing. Highlight.js doesn't do anything special to HTML entities whatsoever. Could you show an example code snippet and how it's mis-represented after applying highlighting?

**Comment by jdagerot** [comment]
My bad.

When I put up an example snippet and started to isolate the issue I found out that it was jQuery that messed up. If I was running highlightAuto directly on a html-fragment everything works.

I'm truly sorry for raising an issue and taking up your time.

However, I'm runnings highlight.js in a node.js environment and wants to highlight just the code fragments I'm ending up with having all my entities unescaped. I googled around and it's not even jQuery to be blamed, this is a browser implementation issue. I'll need to dig into this more unless someone has a solution.


    jsdom = require("jsdom");
    fs = require('fs');
    var hljs = require("highlight.js");
    
    hljs.configure({
    	useBR: true
    	,tabReplace : "&nbsp;"
    
    });
    
    fs.readFile("index.html", function(err,fileData){
    	if(err) {
    		console.dir(err);
    		return false;
    	}
    
    fileData = "" + fileData;	
    jsdom.env(
      fileData,
      ["http://code.jquery.com/jquery.js"],
    	  function (errors, window) {
    	  	var $ = window.$;
    	  	$code = window.$("code");
    	  	$code.each(function(){
    	  		$this = $(this);
    	  		var fixed = hljs.fixMarkup(hljs.highlightAuto($this.html()).value);
    	  		$this.html(fixed);
    	  	});
    	  	fs.writeFile("dist/index.html", window.$("body").html(), function(err) {
    	  		if(err) {
    	  			console.log(err);
    	  			return false;
    	  		}
    	  		console.log("done")
    
    	  	});
    	}
      );
    });

**Comment by isagalaev** [comment]
> `var fixed = hljs.fixMarkup(hljs.highlightAuto($this.html()).value);`

I think the problem is here, in the `.html()`. The `highlightAuto` works on plain text, not HTML. The difference in your case being that the HTML representation would retain all those &-entities which, apart from looking ugly within text strings, may easily result in an incorrect syntax: `if (x &lt; 5) ... `. So I think simply switching to `.text()` should solve it for you.

**Comment by jdagerot** [comment]
Thanks a lot for your effort. Unfortunately $.text() just returns the text-nodes, not the elements so that's not the path to go.

I'll look into if I can get "something" to not deentitize my fragments before sending them to highlight.js

**Comment by isagalaev** [comment]
Wait a second :-). Are you trying to highlight HTML *source code* and have it like this:

```html
<pre><code>
  <html> ... </html>
</pre></code>
```

?

**Comment by jdagerot** [comment]
Yes, without the 
    
    <pre>

But I have something going on now.  Hold on a second.

**Comment by isagalaev** [comment]
Well, you're trying to shoot yourself in the foot then :-). In HTML tags inside `<code>` are just normal tags, like everywhere else (so you can use formatting inside `<code>`). So to correctly display HTML code within HTML, irregardless of any highlighting, you have to escape it first:

```html
<code>
  &lt;html&gt; ... &lt;/html&gt;
</code>
```

If instead you rely on this hack with `.html()` then yes, you will run into corner cases, like the one with entities: you *want* HTML tags to be escaped but you *don't* want* entities to be escaped, and HTML can't know the difference. So I'd suggest to just escape HTML source code before it gets between `<code>..</code>`.

Anyway, it really has nothing to do with highlighting :-)

**Comment by jdagerot** [comment]
Thanks for your help, and you are perfectly right, it certanly hasn't anything to do with highlight.js, a great tool by the way. Thanks again.
