### ISSUE TITLE
PHP 5.5 class resolution operator breaks styles 

### ISSUE THREAD

**Issue by acelaya** [isagalaev/highlight.js#749]
There is a "class" resolution operator in php 5.5 that breaks the styles once used. This is its syntax `Controller::class`. 

It returns the fully qualified class name, but highlight.js detects it as a class declaration, so everything after that is used is broken. 

You can see an example using monokai sublime theme in the link or the attached image. 

![screenshot_2015-02-18-08-04-35 2](https://cloud.githubusercontent.com/assets/2719332/6243629/f88141f2-b745-11e4-9023-3e72cfbd99e1.jpg)

http://blog.alejandrocelaya.com/2015/02/06/managing-objects-creation-and-dependency-injection-with-zend-service-manager/

**Comment by Sannis** [comment]
Ref #653

**Comment by acelaya** [comment]
Thanks @Sannis. That works for me by the moment.

**Comment by SamSaffron** [comment]
@isagalaev having trouble getting a working bundle post this change

**Comment by isagalaev** [comment]
On 03/12/2015 08:13 PM, Sam wrote:
> @isagalaev <https://github.com/isagalaev> having trouble getting a
> working bundle post this change

What do you mean, exactly?

**Comment by SamSaffron** [comment]
Sorry deleted that comment was a user bug
