### ISSUE TITLE
C++: Can the list of built-ins be removed from languages/cpp.js?

### ISSUE THREAD

**Issue by BorisSchaeling** [isagalaev/highlight.js#750]
If I understand correctly, the built-ins are a subset of classes and functions from the standard library. As it's a subset the highlighting isn't consistent. For example, the namespace **std**, the class **string** and the function **labs** from &lt;cmath&gt; are built-ins. But the namespace **placeholders** (as in std::placeholders), the class **thread** and the function **llabs** from &lt;cmath&gt; aren't. That said, my preference would be to remove the list of built-ins. Or is there a good reason why the subset looks the way it does? 

Thanks, 
Boris

**Comment by isagalaev** [comment]
You're bringing up a good point, thank you! One practical reason for having built-ins is to help with language detection. And one practical reason for not including all of them is to keep the size of the library down. In this particular case I wouldn't want to remove them altogether as C-like syntaxes are widespread and it's good to have a few commonly used words as a clue.

One workaround to inconsistent highlighting would be to use a theme (or a local CSS rule) that simply doesn't style this class. Another possible idea is to treat built-ins specially and stop generating markup for them but it requires further thinking…

**Comment by BorisSchaeling** [comment]
I agree that the list of built-ins could get too long. And I see that you need some built-ins if they are used to automatically detect the language. I guess it means that I support the idea you outlined in #751 (language detection but no markup). 

I wouldn't mind if built-ins with markup remain (the way how it currently works) if there was a configuration option to disable them. Maybe that's another idea to let users chose between common usage (with markup for some built-ins) and consistency (with no markup)?

**Comment by isagalaev** [comment]
The solution with simply un-styling built-ins is effectively that user-operated switch you're talking about, no?

(I'm going to close this issue now as we don't really want to simply remove built-ins (however inconsistent) from cpp.js, and all the brain-storming ideas is best suitable for #751.)

**Comment by BorisSchaeling** [comment]
Yes, a user-operated switch would be great.
