### ISSUE TITLE
Special treatment for built-ins

### ISSUE THREAD

**Issue by isagalaev** [isagalaev/highlight.js#751]
(This is just a vague idea at the moment.)

There are a few corner cases where built-ins aren't working right being simply a class name for keywords:

- Proper keywords can't have adjacent dots while built-ins in many languages can. We currently have a hack for this that only works for `beginKeywords`.
- Built-in lists may be huge and impractical to include in their entirety but including only subsets of built-ins leads to inconsistent highlighting. It might make sense to stop generating markup for those altogether (see #750).

Implementation-wise we might grow a new dedicated property "built_ins" along "keywords" and only count those towards relevance, without bothering with markup. However, there are built-ins that do benefit from being highlighted (think `window`, `document`, etc. in JS). May be have different names for those?

**Comment by BorisSchaeling** [comment]
Here's a codepen of what's currently wrong (or at least not ideal): http://codepen.io/anon/pen/LEmvwX

**Comment by isagalaev** [comment]
@Sannis don't assign a milestone to this. As long as it *is* a vague idea, it's impossible to adhere to any time frame anyway. Same probably goes for any "on hold" issue.

**Comment by Sannis** [comment]
> on Jul 28

It looks good to try change that with total styles refactoring at that moment. But you are right - we can keep 'on hold' issues without linking with any milestones.

**Comment by isagalaev** [comment]
Closing this as I don't really see a good merit to this idea. It'll surface by itself when/if there's more use cases and better understanding why we need anything like that.
