### ISSUE TITLE
"nohighlight" class not behaving as expected

### ISSUE THREAD

**Issue by gpocentek** [isagalaev/highlight.js#758]
I followed the documention and used a "nohighlight" class to disable highlighting, but it didn't work. "no-highlight" works though.

I see from the tests that both classes could be used, but only "no-highlight" seems to work.

**Comment by Terri5732** [comment]
Ok thanks,  do what you need to do to fix it.   It will be fine.

**Comment by Sannis** [comment]
@gpocentek, which hljs  version are you use?

**Comment by Terri5732** [comment]
iPad air 2 OSX and IPhone 6+

**Comment by gpocentek** [comment]
@Sannis, I'm using the version that comes bundled with reveal.js, I have no idea if it's possible to extract the version number.

**Comment by Sannis** [comment]
It is pretty old according to https://github.com/hakimel/reveal.js/commit/80fc214af1b93ba83c385c92df7806dfd98927c6.

**Comment by gpocentek** [comment]
Ok, thanks for your feedback.
