### ISSUE TITLE
Partially highlighted

### ISSUE THREAD

**Issue by Legends** [isagalaev/highlight.js#773]
Using VS theme.

&lt;link rel=&quot;stylesheet&quot; href=&quot;//cdnjs.cloudflare.com/ajax/libs/highlight.js/8.4/styles/vs.min.css&quot;&gt;

&lt;script type=&quot;text/javascript&quot; src=&quot;//cdnjs.cloudflare.com/ajax/libs/highlight.js/8.4/highlight.min.js&quot;&gt;&lt;/script&gt;

&lt;script type=&quot;text/javascript&quot; src=&quot;//cdnjs.cloudflare.com/ajax/libs/highlight.js/8.4/languages/powershell.min.js&quot;&gt;        &lt;/script&gt;

&lt;script type=&quot;text/javascript&quot; src=&quot;//cdnjs.cloudflare.com/ajax/libs/highlight.js/8.4/languages/vbscript-html.min.js&quot;&gt;        &lt;/script&gt;

&lt;script type=&quot;text/javascript&quot;&gt; hljs.initHighlightingOnLoad();&lt;/script&gt;

&lt;pre&gt;&lt;code class=&quot;ps&quot;&gt;
Set-ExecutionPolicy RemoteSigned
Set-ExecutionPolicy Unrestricted
&lt;/code&gt;&lt;/pre&gt;

<pre><code class="ps">
Set-ExecutionPolicy RemoteSigned
Set-ExecutionPolicy Unrestricted
</code></pre>

Only the first line gets highlighted, but not the second line.
On a local test site it works good, but when I include this in my Blogger post, I have the above issue.

I think Highlight.js will be mostly used in blogs, perhaps you know that kind of issue, regarding Blogger?

**Comment by isagalaev** [comment]
Could you give a link to a page where it doesn't work? It should work by the look of it and it does work on my local machine, highlighting both "Set-ExecutionPolicy" words as PowerShell built-ins.

**Comment by Legends** [comment]
Shame on me and WLW (Windows Live Writer) Editor, the Editor puts <br/> tags between the two lines, even if I do work in Source Mode.... that's the problem. After removing the <br/> tag it works again.

**Comment by isagalaev** [comment]
OK, glad you found the culprit :-)

**Comment by Legends** [comment]
Strange, now it works with &lt;br/&gt; tag inbetween. How can I distribute the code onto different lines without using any html tags, i.e. p, br, ...?

**Comment by isagalaev** [comment]
This is what the `<pre>` tag is for: it keeps line breaks and white space intact (unless it's overridden in CSS).

**Comment by Legends** [comment]
Can you take a look at the theme codepen-embed.min.css v8.4 (hosted on cdnjs ), it breaks the javascript layout, while others don't. Perhaps the bug is only present in cdn hosted file, as I can see that it works on your demo page. 

JSBIN (Just select the theme from the dropdown list):
http://jsbin.com/wafanu/2/

**Comment by isagalaev** [comment]
There was a weird rule in the CSS file that was causing it. Fixed in 86632d19. Thanks for catching this! One polite request though: please don't post new issues as comments to unrelated (and closed) issues, it's really hard to keep track of them this way.

**Comment by Legends** [comment]
Actually this time I wanted to be sure, that it's really a bug :) that's why I didn't raise a new issue ;-)
Ok, no problem.

**Comment by isagalaev** [comment]
Well, regardless of the outcome, it's still easier to keep an eye on it separately :-) We don't always react on bugmail fast, so a stray comment in a closed issue has all the chances to be simply forgotten in a few weeks :-)
