### ISSUE TITLE
Lua comments are broken

### ISSUE THREAD

**Issue by CalinLeafshade** [isagalaev/highlight.js#777]
The Lua highlighter recognises # as the comment signifier when lua uses -- for comments.

**Comment by isagalaev** [comment]
As far as I can see Lua definition doesn't define #-starting comments anywhere, so what you're seeing is probably an attempt to highlight the code in question as some other language. To investigate we're going to look at the code snippet and to know which highlight.js instance you're using (custom built, from a CDN, from the npm package).

**Comment by CalinLeafshade** [comment]
Actually it seems that .highlightauto is recognising it as a different language which would explain my error. Sorry for the invalid bug.

**Comment by isagalaev** [comment]
It might still be worth fixing though. If the code is not tiny and decidedly Lua-looking we might want to improve detection on it. Could you post it here?

**Comment by CalinLeafshade** [comment]
Sure, the code is question was:

    adore.event("repeatedly_execute_always", function()
        if #queue > 0 then
            queue[1]:update(adore.getGameDT())
            if queue[1]:isDone() then
                table.remove(queue, 1)
            end
        end
    end)

The # character confused it. "#" is the array length operator in Lua.

**Comment by isagalaev** [comment]
Thanks, I'll have a look at it!

**Comment by sourrust** [comment]
I got it this sample to autodetect as lua and it is now in master.
