### ISSUE TITLE
Fortran support added or not?

### ISSUE THREAD

**Issue by steverep** [isagalaev/highlight.js#788]
This is not a request for Fortran support, but rather a question and possible issue from a new user who has read nearly all the docs.  I see there is a fortran.js file in src/languages, and also it is listed in the CSS classes reference at http://highlightjs.readthedocs.org/en/latest/css-classes-reference.html.

So, I'm wondering why Fortran is not a checkbox on the download page, included in the 112 languages supported, or anywhere on the demo page.  If this is a simple oversight, please fix it.  If there is something missing or wrong with the language definition, please let me know why it's not included and perhaps I can make an attempt at the fixes or re-definition.  Thanks.

**Comment by isagalaev** [comment]
Hello! Fortran is there in the code, fully functional, but we simply haven't yet released a new version with it. It's coming along nicely and probably should be out next week.

**Comment by steverep** [comment]
Oh.... my bad.  I should have checked the version tags.  Thanks for setting me straight and I'll be sure to check it out.

**Comment by isagalaev** [comment]
No problem :-) I don't assume everyone to be automatically familiar with our development and release process.

**Comment by wolfiex** [comment]
Has fortran still not been added to the main list of supported languages?

**Comment by joshgoebel** [comment]
Did you even look?

**Comment by wolfiex** [comment]
- Its not on indexed in the documentation (read the docs) ! 
- its not in the supported languages markdown file. 
- It flags up as an error when trying to specify it directly. 

Yes the file exits, but instructions on how to embed it are severely lacking. 

For others, this can be done with 
```js
hljs.registerLanguage('f90', require('./node_modules/highlight.js/lib/languages/fortran.js'));
```
allowing you to then specify `f90` as a language.

**Comment by joshgoebel** [comment]
The documentation mentions/references the SUPPORTED_LANGUAGES document here on Github which has a full and complete list (including Fortran, and 3rd party grammars also).

> its not in the supported languages markdown file.

I'm not sure what you are looking at, it's right there in alphabetical order:

https://github.com/highlightjs/highlight.js/blob/main/SUPPORTED_LANGUAGES.md

> Yes the file exits, but instructions on how to embed it are severely lacking.

There is nothing special about Fortran - it's used in the same way all all the other languages... perhaps you're running into some other difficulty.

> allowing you to then specify f90 as a language.

`f90` is one of fortran aliases, traditionally you'd use the name:

```
hljs.registerLanguage('fortan', require('./node_modules/highlight.js/lib/languages/fortran.js'));
```

Though I'm not sure using f90 is actually problematic.

**Comment by joshgoebel** [comment]
>...it would work fine.

_Unless aliases conflict with language names_, that was my exact point regarding `f95`.  But I was only trying to throw a wide net since for a moment you made it sound like Fortran doesn't work like every other language when included, which it does.

>  no obvious way to know...it is supported

- SUPPORTED_LANGUAGES, mentioned both in the README and on the docs site.

> no obvious way to know...a user requires a command similar to the one below

- README

While we could discuss the merits of this being in the docs right now the README is usage/getting started and the doc are more the nitty gritty details, which I think is a pretty common pattern.
