### ISSUE TITLE
Auto highlight won't end with this file

### ISSUE THREAD

**Issue by harttle** [isagalaev/highlight.js#791]
// !$*UTF8*$!
{
	archiveVersion = 1;
	classes = {
	};
	objectVersion = 46;
	objects = {

/* Begin PBXBuildFile section */
		E32D37AE1AB426260019547B /* AppDelegate.swift in Sources */ = {isa = PBXBuildFile; fileRef = E32D37AD1AB426260019547B /* AppDelegate.swift */; };
		E32D37B01AB426260019547B /* ViewController.swift in Sources */ = {isa = PBXBuildFile; fileRef = E32D37AF1AB426260019547B /* ViewController.swift */; };
		E32D37B31AB426260019547B /* Main.storyboard in Resources */ = {isa = PBXBuildFile; fileRef = E32D37B11AB426260019547B /* Main.storyboard */; };
		E32D37B51AB426260019547B /* Images.xcassets in Resources */ = {isa = PBXBuildFile; fileRef = E32D37B41AB426260019547B /* Images.xcassets */; };
		E32D37B81AB426260019547B /* LaunchScreen.xib in Resources */ = {isa = PBXBuildFile; fileRef = E32D37B61AB426260019547B /* LaunchScreen.xib */; };
		E32D37C41AB426260019547B /* HelloWorldTests.swift in Sources */ = {isa = PBXBuildFile; fileRef = E32D37C31AB426260019547B /* HelloWorldTests.swift */; };
/* End PBXBuildFile section */

/* Begin PBXContainerItemProxy section */
		E32D37BE1AB426260019547B /* PBXContainerItemProxy */ = {
			isa = PBXContainerItemProxy;
			containerPortal = E32D37A01AB426260019547B /* Project object */;
			proxyType = 1;
			remoteGlobalIDString = E32D37A71AB426260019547B;
			remoteInfo = HelloWorld;
		};
/* End PBXContainerItemProxy section */

/* Begin PBXFileReference section */
		E32D37A81AB426260019547B /* HelloWorld.app */ = {isa = PBXFileReference; explicitFileType = wrapper.application; includeInIndex = 0; path = HelloWorld.app; sourceTree = BUILT_PRODUCTS_DIR; };
		E32D37AC1AB426260019547B /* Info.plist */ = {isa = PBXFileReference; lastKnownFileType = text.plist.xml; path = Info.plist; sourceTree = "<group>"; };
		E32D37AD1AB426260019547B /* AppDelegate.swift */ = {isa = PBXFileReference; lastKnownFileType = sourcecode.swift; path = AppDelegate.swift; sourceTree = "<group>"; };
		E32D37AF1AB426260019547B /* ViewController.swift */ = {isa = PBXFileReference; lastKnownFileType = sourcecode.swift; path = ViewController.swift; sourceTree = "<group>"; };
		E32D37B21AB426260019547B /* Base */ = {isa = PBXFileReference; lastKnownFileType = file.storyboard; name = Base; path = Base.lproj/Main.storyboard; sourceTree = "<group>"; };
		E32D37B41AB426260019547B /* Images.xcassets */ = {isa = PBXFileReference; lastKnownFileType = folder.assetcatalog; path = Images.xcassets; sourceTree = "<group>"; };
		E32D37B71AB426260019547B /* Base */ = {isa = PBXFileReference; lastKnownFileType = file.xib; name = Base; path = Base.lproj/LaunchScreen.xib; sourceTree = "<group>"; };
		E32D37BD1AB426260019547B /* HelloWorldTests.xctest */ = {isa = PBXFileReference; explicitFileType = wrapper.cfbundle; includeInIndex = 0; path = HelloWorldTests.xctest; sourceTree = BUILT_PRODUCTS_DIR; };
		E32D37C21AB426260019547B /* Info.plist */ = {isa = PBXFileReference; lastKnownFileType = text.plist.xml; path = Info.plist; sourceTree = "<group>"; };
		E32D37C31AB426260019547B /* HelloWorldTests.swift */ = {isa = PBXFileReference; lastKnownFileType = sourcecode.swift; path = HelloWorldTests.swift; sourceTree = "<group>"; };
/* End PBXFileReference section */

/* Begin PBXFrameworksBuildPhase section */
		E32D37A51AB426260019547B /* Frameworks */ = {
			isa = PBXFrameworksBuildPhase;
			buildActionMask = 2147483647;
			files = (
			);
			runOnlyForDeploymentPostprocessing = 0;
		};
		E32D37BA1AB426260019547B /* Frameworks */ = {
			isa = PBXFrameworksBuildPhase;
			buildActionMask = 2147483647;
			files = (
			);
			runOnlyForDeploymentPostprocessing = 0;
		};
/* End PBXFrameworksBuildPhase section */

/* Begin PBXGroup section */
		E32D379F1AB426260019547B = {
			isa = PBXGroup;
			children = (
				E32D37AA1AB426260019547B /* HelloWorld */,
				E32D37C01AB426260019547B /* HelloWorldTests */,
				E32D37A91AB426260019547B /* Products */,
			);
			sourceTree = "<group>";
		};
		E32D37A91AB426260019547B /* Products */ = {
			isa = PBXGroup;
			children = (
				E32D37A81AB426260019547B /* HelloWorld.app */,
				E32D37BD1AB426260019547B /* HelloWorldTests.xctest */,
			);
			name = Products;
			sourceTree = "<group>";
		};
		E32D37AA1AB426260019547B /* HelloWorld */ = {
			isa = PBXGroup;
			children = (
				E32D37AD1AB426260019547B /* AppDelegate.swift */,
				E32D37AF1AB426260019547B /* ViewController.swift */,
				E32D37B11AB426260019547B /* Main.storyboard */,
				E32D37B41AB426260019547B /* Images.xcassets */,
				E32D37B61AB426260019547B /* LaunchScreen.xib */,
				E32D37AB1AB426260019547B /* Supporting Files */,
			);
			path = HelloWorld;
			sourceTree = "<group>";
		};
		E32D37AB1AB426260019547B /* Supporting Files */ = {
			isa = PBXGroup;
			children = (
				E32D37AC1AB426260019547B /* Info.plist */,
			);
			name = "Supporting Files";
			sourceTree = "<group>";
		};
		E32D37C01AB426260019547B /* HelloWorldTests */ = {
			isa = PBXGroup;
			children = (
				E32D37C31AB426260019547B /* HelloWorldTests.swift */,
				E32D37C11AB426260019547B /* Supporting Files */,
			);
			path = HelloWorldTests;
			sourceTree = "<group>";
		};
		E32D37C11AB426260019547B /* Supporting Files */ = {
			isa = PBXGroup;
			children = (
				E32D37C21AB426260019547B /* Info.plist */,
			);
			name = "Supporting Files";
			sourceTree = "<group>";
		};
/* End PBXGroup section */

/* Begin PBXNativeTarget section */
		E32D37A71AB426260019547B /* HelloWorld */ = {
			isa = PBXNativeTarget;
			buildConfigurationList = E32D37C71AB426260019547B /* Build configuration list for PBXNativeTarget "HelloWorld" */;
			buildPhases = (
				E32D37A41AB426260019547B /* Sources */,
				E32D37A51AB426260019547B /* Frameworks */,
				E32D37A61AB426260019547B /* Resources */,
			);
			buildRules = (
			);
			dependencies = (
			);
			name = HelloWorld;
			productName = HelloWorld;
			productReference = E32D37A81AB426260019547B /* HelloWorld.app */;
			productType = "com.apple.product-type.application";
		};
		E32D37BC1AB426260019547B /* HelloWorldTests */ = {
			isa = PBXNativeTarget;
			buildConfigurationList = E32D37CA1AB426260019547B /* Build configuration list for PBXNativeTarget "HelloWorldTests" */;
			buildPhases = (
				E32D37B91AB426260019547B /* Sources */,
				E32D37BA1AB426260019547B /* Frameworks */,
				E32D37BB1AB426260019547B /* Resources */,
			);
			buildRules = (
			);
			dependencies = (
				E32D37BF1AB426260019547B /* PBXTargetDependency */,
			);
			name = HelloWorldTests;
			productName = HelloWorldTests;
			productReference = E32D37BD1AB426260019547B /* HelloWorldTests.xctest */;
			productType = "com.apple.product-type.bundle.unit-test";
		};
/* End PBXNativeTarget section */

/* Begin PBXProject section */
		E32D37A01AB426260019547B /* Project object */ = {
			isa = PBXProject;
			attributes = {
				LastUpgradeCheck = 0620;
				ORGANIZATIONNAME = v_hasu;
				TargetAttributes = {
					E32D37A71AB426260019547B = {
						CreatedOnToolsVersion = 6.2;
					};
					E32D37BC1AB426260019547B = {
						CreatedOnToolsVersion = 6.2;
						TestTargetID = E32D37A71AB426260019547B;
					};
				};
			};
			buildConfigurationList = E32D37A31AB426260019547B /* Build configuration list for PBXProject "HelloWorld" */;
			compatibilityVersion = "Xcode 3.2";
			developmentRegion = English;
			hasScannedForEncodings = 0;
			knownRegions = (
				en,
				Base,
			);
			mainGroup = E32D379F1AB426260019547B;
			productRefGroup = E32D37A91AB426260019547B /* Products */;
			projectDirPath = "";
			projectRoot = "";
			targets = (
				E32D37A71AB426260019547B /* HelloWorld */,
				E32D37BC1AB426260019547B /* HelloWorldTests */,
			);
		};
/* End PBXProject section */

/* Begin PBXResourcesBuildPhase section */
		E32D37A61AB426260019547B /* Resources */ = {
			isa = PBXResourcesBuildPhase;
			buildActionMask = 2147483647;
			files = (
				E32D37B31AB426260019547B /* Main.storyboard in Resources */,
				E32D37B81AB426260019547B /* LaunchScreen.xib in Resources */,
				E32D37B51AB426260019547B /* Images.xcassets in Resources */,
			);
			runOnlyForDeploymentPostprocessing = 0;
		};
		E32D37BB1AB426260019547B /* Resources */ = {
			isa = PBXResourcesBuildPhase;
			buildActionMask = 2147483647;
			files = (
			);
			runOnlyForDeploymentPostprocessing = 0;
		};
/* End PBXResourcesBuildPhase section */

/* Begin PBXSourcesBuildPhase section */
		E32D37A41AB426260019547B /* Sources */ = {
			isa = PBXSourcesBuildPhase;
			buildActionMask = 2147483647;
			files = (
				E32D37B01AB426260019547B /* ViewController.swift in Sources */,
				E32D37AE1AB426260019547B /* AppDelegate.swift in Sources */,
			);
			runOnlyForDeploymentPostprocessing = 0;
		};
		E32D37B91AB426260019547B /* Sources */ = {
			isa = PBXSourcesBuildPhase;
			buildActionMask = 2147483647;
			files = (
				E32D37C41AB426260019547B /* HelloWorldTests.swift in Sources */,
			);
			runOnlyForDeploymentPostprocessing = 0;
		};
/* End PBXSourcesBuildPhase section */

/* Begin PBXTargetDependency section */
		E32D37BF1AB426260019547B /* PBXTargetDependency */ = {
			isa = PBXTargetDependency;
			target = E32D37A71AB426260019547B /* HelloWorld */;
			targetProxy = E32D37BE1AB426260019547B /* PBXContainerItemProxy */;
		};
/* End PBXTargetDependency section */

/* Begin PBXVariantGroup section */
		E32D37B11AB426260019547B /* Main.storyboard */ = {
			isa = PBXVariantGroup;
			children = (
				E32D37B21AB426260019547B /* Base */,
			);
			name = Main.storyboard;
			sourceTree = "<group>";
		};
		E32D37B61AB426260019547B /* LaunchScreen.xib */ = {
			isa = PBXVariantGroup;
			children = (
				E32D37B71AB426260019547B /* Base */,
			);
			name = LaunchScreen.xib;
			sourceTree = "<group>";
		};
/* End PBXVariantGroup section */

/* Begin XCBuildConfiguration section */
		E32D37C51AB426260019547B /* Debug */ = {
			isa = XCBuildConfiguration;
			buildSettings = {
				ALWAYS_SEARCH_USER_PATHS = NO;
				CLANG_CXX_LANGUAGE_STANDARD = "gnu++0x";
				CLANG_CXX_LIBRARY = "libc++";
				CLANG_ENABLE_MODULES = YES;
				CLANG_ENABLE_OBJC_ARC = YES;
				CLANG_WARN_BOOL_CONVERSION = YES;
				CLANG_WARN_CONSTANT_CONVERSION = YES;
				CLANG_WARN_DIRECT_OBJC_ISA_USAGE = YES_ERROR;
				CLANG_WARN_EMPTY_BODY = YES;
				CLANG_WARN_ENUM_CONVERSION = YES;
				CLANG_WARN_INT_CONVERSION = YES;
				CLANG_WARN_OBJC_ROOT_CLASS = YES_ERROR;
				CLANG_WARN_UNREACHABLE_CODE = YES;
				CLANG_WARN__DUPLICATE_METHOD_MATCH = YES;
				"CODE_SIGN_IDENTITY[sdk=iphoneos*]" = "iPhone Developer";
				COPY_PHASE_STRIP = NO;
				ENABLE_STRICT_OBJC_MSGSEND = YES;
				GCC_C_LANGUAGE_STANDARD = gnu99;
				GCC_DYNAMIC_NO_PIC = NO;
				GCC_OPTIMIZATION_LEVEL = 0;
				GCC_PREPROCESSOR_DEFINITIONS = (
					"DEBUG=1",
					"$(inherited)",
				);
				GCC_SYMBOLS_PRIVATE_EXTERN = NO;
				GCC_WARN_64_TO_32_BIT_CONVERSION = YES;
				GCC_WARN_ABOUT_RETURN_TYPE = YES_ERROR;
				GCC_WARN_UNDECLARED_SELECTOR = YES;
				GCC_WARN_UNINITIALIZED_AUTOS = YES_AGGRESSIVE;
				GCC_WARN_UNUSED_FUNCTION = YES;
				GCC_WARN_UNUSED_VARIABLE = YES;
				IPHONEOS_DEPLOYMENT_TARGET = 8.2;
				MTL_ENABLE_DEBUG_INFO = YES;
				ONLY_ACTIVE_ARCH = YES;
				SDKROOT = iphoneos;
				SWIFT_OPTIMIZATION_LEVEL = "-Onone";
				TARGETED_DEVICE_FAMILY = "1,2";
			};
			name = Debug;
		};
		E32D37C61AB426260019547B /* Release */ = {
			isa = XCBuildConfiguration;
			buildSettings = {
				ALWAYS_SEARCH_USER_PATHS = NO;
				CLANG_CXX_LANGUAGE_STANDARD = "gnu++0x";
				CLANG_CXX_LIBRARY = "libc++";
				CLANG_ENABLE_MODULES = YES;
				CLANG_ENABLE_OBJC_ARC = YES;
				CLANG_WARN_BOOL_CONVERSION = YES;
				CLANG_WARN_CONSTANT_CONVERSION = YES;
				CLANG_WARN_DIRECT_OBJC_ISA_USAGE = YES_ERROR;
				CLANG_WARN_EMPTY_BODY = YES;
				CLANG_WARN_ENUM_CONVERSION = YES;
				CLANG_WARN_INT_CONVERSION = YES;
				CLANG_WARN_OBJC_ROOT_CLASS = YES_ERROR;
				CLANG_WARN_UNREACHABLE_CODE = YES;
				CLANG_WARN__DUPLICATE_METHOD_MATCH = YES;
				"CODE_SIGN_IDENTITY[sdk=iphoneos*]" = "iPhone Developer";
				COPY_PHASE_STRIP = NO;
				ENABLE_NS_ASSERTIONS = NO;
				ENABLE_STRICT_OBJC_MSGSEND = YES;
				GCC_C_LANGUAGE_STANDARD = gnu99;
				GCC_WARN_64_TO_32_BIT_CONVERSION = YES;
				GCC_WARN_ABOUT_RETURN_TYPE = YES_ERROR;
				GCC_WARN_UNDECLARED_SELECTOR = YES;
				GCC_WARN_UNINITIALIZED_AUTOS = YES_AGGRESSIVE;
				GCC_WARN_UNUSED_FUNCTION = YES;
				GCC_WARN_UNUSED_VARIABLE = YES;
				IPHONEOS_DEPLOYMENT_TARGET = 8.2;
				MTL_ENABLE_DEBUG_INFO = NO;
				SDKROOT = iphoneos;
				TARGETED_DEVICE_FAMILY = "1,2";
				VALIDATE_PRODUCT = YES;
			};
			name = Release;
		};
		E32D37C81AB426260019547B /* Debug */ = {
			isa = XCBuildConfiguration;
			buildSettings = {
				ASSETCATALOG_COMPILER_APPICON_NAME = AppIcon;
				INFOPLIST_FILE = HelloWorld/Info.plist;
				LD_RUNPATH_SEARCH_PATHS = "$(inherited) @executable_path/Frameworks";
				PRODUCT_NAME = "$(TARGET_NAME)";
			};
			name = Debug;
		};
		E32D37C91AB426260019547B /* Release */ = {
			isa = XCBuildConfiguration;
			buildSettings = {
				ASSETCATALOG_COMPILER_APPICON_NAME = AppIcon;
				INFOPLIST_FILE = HelloWorld/Info.plist;
				LD_RUNPATH_SEARCH_PATHS = "$(inherited) @executable_path/Frameworks";
				PRODUCT_NAME = "$(TARGET_NAME)";
			};
			name = Release;
		};
		E32D37CB1AB426260019547B /* Debug */ = {
			isa = XCBuildConfiguration;
			buildSettings = {
				BUNDLE_LOADER = "$(TEST_HOST)";
				FRAMEWORK_SEARCH_PATHS = (
					"$(SDKROOT)/Developer/Library/Frameworks",
					"$(inherited)",
				);
				GCC_PREPROCESSOR_DEFINITIONS = (
					"DEBUG=1",
					"$(inherited)",
				);
				INFOPLIST_FILE = HelloWorldTests/Info.plist;
				LD_RUNPATH_SEARCH_PATHS = "$(inherited) @executable_path/Frameworks @loader_path/Frameworks";
				PRODUCT_NAME = "$(TARGET_NAME)";
				TEST_HOST = "$(BUILT_PRODUCTS_DIR)/HelloWorld.app/HelloWorld";
			};
			name = Debug;
		};
		E32D37CC1AB426260019547B /* Release */ = {
			isa = XCBuildConfiguration;
			buildSettings = {
				BUNDLE_LOADER = "$(TEST_HOST)";
				FRAMEWORK_SEARCH_PATHS = (
					"$(SDKROOT)/Developer/Library/Frameworks",
					"$(inherited)",
				);
				INFOPLIST_FILE = HelloWorldTests/Info.plist;
				LD_RUNPATH_SEARCH_PATHS = "$(inherited) @executable_path/Frameworks @loader_path/Frameworks";
				PRODUCT_NAME = "$(TARGET_NAME)";
				TEST_HOST = "$(BUILT_PRODUCTS_DIR)/HelloWorld.app/HelloWorld";
			};
			name = Release;
		};
/* End XCBuildConfiguration section */

/* Begin XCConfigurationList section */
		E32D37A31AB426260019547B /* Build configuration list for PBXProject "HelloWorld" */ = {
			isa = XCConfigurationList;
			buildConfigurations = (
				E32D37C51AB426260019547B /* Debug */,
				E32D37C61AB426260019547B /* Release */,
			);
			defaultConfigurationIsVisible = 0;
			defaultConfigurationName = Release;
		};
		E32D37C71AB426260019547B /* Build configuration list for PBXNativeTarget "HelloWorld" */ = {
			isa = XCConfigurationList;
			buildConfigurations = (
				E32D37C81AB426260019547B /* Debug */,
				E32D37C91AB426260019547B /* Release */,
			);
			defaultConfigurationIsVisible = 0;
		};
		E32D37CA1AB426260019547B /* Build configuration list for PBXNativeTarget "HelloWorldTests" */ = {
			isa = XCConfigurationList;
			buildConfigurations = (
				E32D37CB1AB426260019547B /* Debug */,
				E32D37CC1AB426260019547B /* Release */,
			);
			defaultConfigurationIsVisible = 0;
		};
/* End XCConfigurationList section */
	};
	rootObject = E32D37A01AB426260019547B /* Project object */;
}

**Comment by harttle** [comment]
highlightAuto won't terminate on line 47 of this file, which is:

```
runOnlyForDeploymentPostprocessing = 0;
```

You can run this script with node.js:

```js
var h=require('highlight.js');

console.log('begin');
result = h.highlightAuto('runOnlyForDeploymentPostprocessing = 0;');
console.log('never come here');

console.log(result.value);
```

**Comment by isagalaev** [comment]
Could you try it with the current master code, not the latest released version. We fixed a couple of hanging bugs in the last iteration.

**Comment by harttle** [comment]
I'm working with highlight.js npm package, with version is 8.4.0. Maybe too old, it's published 4 months ago...

**Comment by isagalaev** [comment]
Yes, that's why I'm asking to check it with the new code. I can't reproduce it on my machine so it's probably fixed but I wanted to make sure it works for you too.

**Comment by Sannis** [comment]
Cannot reproduce this with current master and v8.5.

I've added rendering time stats to developers tool (aa342e01f239163aad60d8f4d540b1ec6da6ad64), it takes about 500 ms on my PC.
