### ISSUE TITLE
CSS theme minified

### ISSUE THREAD

**Issue by cmoulliard** [isagalaev/highlight.js#792]
Hi,

Is there a way to minify the css theme during the build process ?

Regards,

Charles

**Comment by isagalaev** [comment]
`node tools/build.js -t cdn` would do that for you. It's the build targeted for CDNs and it includes all styles minified under build/styles/.

**Comment by cmoulliard** [comment]
Thx for the info.

**Comment by Sannis** [comment]
There is some informations in docs: http://highlightjs.readthedocs.org/en/latest/building-testing.html.

**Comment by sourrust** [comment]
I added a more detailed explanation for each build target results is `tools/build.js`. The baseline information mentioned by @Sannis is great for the general stuff, but if you want the detail that will be in the source.

**Comment by isagalaev** [comment]
@sourrust thanks for doing that! There can never be enough documentation effort :-)
