### ISSUE TITLE
Highlight js will dead loop on following markdown

### ISSUE THREAD

**Issue by sunyc** [isagalaev/highlight.js#796]
```
#参考
    123building-your-own-ember-app-kit-lite
```

Using above markdown with hightlight js autodetection will cause hightlight js to loop infinitely.  The problem is that it is detecting as "stata" language, and apparently that is not very mature...

**Comment by sunyc** [comment]
```stata
123building-your-own-ember-app-kit-lite
```

**Comment by sunyc** [comment]
```stata
123building-your-own-ember-app-kit-lite
```

**Comment by sunyc** [comment]
https://jsfiddle.net/178bxmkn/2/

Please see this example ， it loops for ever.

**Comment by sunyc** [comment]
(clicking above link will cause chrome tab to hang) , try use safari.

**Comment by Sannis** [comment]
> Using above markdown with hightlight js autodetection will cause hightlight js to loop infinitely.
> The problem is that it is detecting as "stata" language, and apparently that is not very mature...

I've check this snipped with current master and it was successfully highlighted as Stata. So, what was your report about: wrong language detection or high CPU usage?

**Comment by isagalaev** [comment]
I think he tests against 8.4. We will be releasing the next version soon-ish and it is fixed in that.
