### ISSUE TITLE
javascript (ES6) multiline strings aren't highlighted correct

### ISSUE THREAD

**Issue by shuvalov-anton** [isagalaev/highlight.js#799]
![screen shot 2015-04-02 at 00 08 58](https://cloud.githubusercontent.com/assets/1410106/6952692/bf75a418-d8cc-11e4-8838-403200a9bf58.png)

**Comment by sourrust** [comment]
ES6 template strings were added pretty recently and this works correctly in master.
![](https://cloud.githubusercontent.com/assets/365596/6955503/69d1ce6c-d893-11e4-80fd-34bd0914fa40.PNG)

**Comment by shuvalov-anton** [comment]
Thank you! I'm waiting for release :D
