### ISSUE TITLE
Inline comment problem with html-formatted code

### ISSUE THREAD

**Issue by jansiegel** [isagalaev/highlight.js#801]
I have a problem with inline comments inside a "html-formatted" code. 
What i mean is, when i format the code (inside the `code` tag) using `&nbsp;` and `<br>`, the inline comments don't recognise the end of the lines. 
Not sure if it's a bug, or is it not supported?

I made a jsfiddle: http://jsfiddle.net/ec7koywq/

Thanks!

**Comment by isagalaev** [comment]
It's not a bug but a configurable behavior, you can use `hljs.configure({useBR: true});` to make it understand `<br>` as proper line breaks. This means, though, that you can't have it both ways on the same page.

Just out of curiosity, why would you want to use `<br>` and `&nbsp;` inside a `<pre>`?

**Comment by Sannis** [comment]
@jansiegel, fill free to reopen it to continue discussion.
