### ISSUE TITLE
Highlighting JavaScript regular expressions?

### ISSUE THREAD

**Issue by mariusschulz** [isagalaev/highlight.js#802]
Is it possible to configure highlight.js to highlight regular expressions in JavaScript code, e.g. like this?

```js
var endsInScriptPattern = /Script$/;
```

I'm not looking for a full-blown regex parser which analyzes the regex pattern and highlights special characters like `$`. It would totally be enough to have the `/Script$/` displayed in a different color.

Is that possible, and if yes, how?

**Comment by isagalaev** [comment]
It is already the case. If you don't see it happening, could you point at the example showing the problem?

**Comment by mariusschulz** [comment]
My bad! I just saw that the regex was wrapped within a `<span>` with the `hljs-regexp` class, but my theme doesn't specify any highlight color for regular expressions, so it doesn't look highlighted. Doh!

**Comment by isagalaev** [comment]
Yeah, our styles are quite inconsistent at the moment but we have a plan to deal with it eventually.
