### ISSUE TITLE
What is the correct way to specify a language for a block?

### ISSUE THREAD

**Issue by d0ugal** [isagalaev/highlight.js#816]
I thought this would do it:

```html
<pre><code class="lua">
print("Hello, world!")
</code></pre>
```

However, after highlight.js is applied it looks a it like this...

```html
<code class="lua hljs vbnet">
<span class="hljs-keyword">print</span>
(<span class="hljs-string">"Hello, world!"</span>)
</code>
```

So it seems hljs still detects the language which isn't what I hoped would happen :) Is there a way to specify a language?

**Comment by Sannis** [comment]
Which hljs version are you using?

**Comment by d0ugal** [comment]
@Sannis I'm not actually sure, if this is a known old bug I can update and make sure we are using the latest version. Which I think is 8.5?

**Comment by d0ugal** [comment]
I tested with the latest, it does resolve my problems. Sorry for the noise, I should have tried this but figured I was doing something wrong.

**Comment by Sannis** [comment]
Your highlight.pack.js doest not contain Lua definition, so it try to autohightlight with one of existing languages and VB.NET is the best fit:
```
> hljs.getLanguage('vbnet');
Object {cI: true, k: Object, i: "//|{|}|endif|gosub|variant|wend", c: Array[4], compiled: true…}
> hljs.getLanguage('lua');
undefined
```

**Comment by d0ugal** [comment]
Aha, thanks. When updating I added the other languages in too.
