### ISSUE TITLE
Breaking change from 0.4.16 -> 0.4.17 .empty() undefined

### ISSUE THREAD

**Issue by adamkdean** [isagalaev/highlight.js#817]
I'm using search-index on my current site, and it works on 0.4.16, but I've just installed it on my current dev machine and it installed 0.4.17 (because that ~0.4.16 essentially), and it is broken.

It spits it's dummy out when I try to do searchIndex.empty( ... ), saying it's undefined. I specifically went back to 0.4.16 and it works fine. Is this due to me using .empty() wrong? Or is this a breaking change? If so, shouldn't the major be updated?

Thanks though, thought I'd report it. I'm frozen on 0.4.16 for now though.

**Comment by Sannis** [comment]
Highlight.js version 0.4 was released more than 6 years ago, also we user 2-numbers format for versions. You probably talk about some other library.

**Comment by adamkdean** [comment]
Oh wow, how on earth did that happen? Must have been in the wrong tab. 

A thousand apologies, @Sannis!
