### ISSUE TITLE
[cpp11] multiline raw string not supported!

### ISSUE THREAD

**Issue by movsb** [isagalaev/highlight.js#818]
Multiline raw strings are introduced in c++11, but highlightjs does not support that pattern.

```cpp
int main()
{
    std::cout &lt;&lt; 
R"(multiline
raw string from c++11
will not be properly highlighted!
)";
}
```
codes like above won't be highlighted!

**Comment by sourrust** [comment]
What version are you using because 8.5 seems to be doing the right thing:

![](https://cloud.githubusercontent.com/assets/365596/7056847/4b70c2cc-de04-11e4-994f-f32c0a86a939.PNG)

If anything, the bug might just be an incorrect language detect.

**Comment by movsb** [comment]
@sourrust try this: http://twofei.com/doodle/hljs.html
I think I'm using the latest version of hljs, because I downloaded it yestoday. (Original name is `highlight.pack.js`, I renamed it )
And, I have explicitly specified the language to be used.

If the link isn't accessible，the code is showing bellow:
```html
<!doctype html>
<html>
<head>
	<meta charset="UTF-8" />
	<style>
		div.code {
			overflow: auto;
			white-space: pre;
		}
	</style>
	<link rel="stylesheet" href="../plugins/highlightjs/monokai_sublime.css" />
</head>
<body>
<div class="code">int main()
{
    std::cout &lt;&lt; 
R"(multiline
raw string from c++11
will not be properly highlighted!
)";
}
</div>
<div class="code">int main()
{
    std::cout &lt;&lt; 
R"(single line raw string from c++11 will be properly highlighted!)";
}
</div>

<script src="../admin/scripts/jquery-2.1.3.min.js"></script>
<script src="../plugins/highlightjs/highlight.min.js"></script>
<script>
	$('div.code').each(function(i,e){
		var ho = {tabReplace: '    ',languages: ['cpp']};
		hljs.configure(ho);
		hljs.highlightBlock(e);
	});
</script>
</body>
</html>
```

**Comment by sourrust** [comment]
Ok, I fixed the issue and it's now in master. Thanks for reporting this.

![](https://cloud.githubusercontent.com/assets/365596/7059778/2bb5ab88-de2b-11e4-9812-a2ffd1d79634.PNG)

Also, as a side note, you don't need to stick the configuration inside of a loop. It doesn't actually break anything but configure only needs to be set once.

```javascript
hljs.configure({
    tabReplace: '    ',
    languages: ['cpp']
});

$('div.code').each(function(i,e){
    hljs.highlightBlock(e);
});
```
