### ISSUE TITLE
Will this support code beauty? 

### ISSUE THREAD

**Issue by lichenhao** [isagalaev/highlight.js#820]
RT. highlight and beauty can do both together?

**Comment by sourrust** [comment]
Most likely not considering the goal of this project to be simple. There isn't really a reason for a code highlighting library to also beautify it as well. If anything this is something similar to @isagalaev's [stance on line numbering][1] in highlight.js.

[1]: https://highlightjs.readthedocs.org/en/latest/line-numbers.html

**Comment by lichenhao** [comment]
There maybe some suggestions or recommends in the docs or guid (^_^) ~

**Comment by sourrust** [comment]
Not sure if I understand. However when it comes to code formatting, or beautification, it is about doing so manually.

**Comment by mjrev** [comment]
faced the same problem too - i used ajax to load code from files, in result there was different indent starting point, [this plugin](https://code.google.com/p/jquery-clean/) worked for me

**Comment by lichenhao** [comment]
@mjrev  that's awesome.
