### ISSUE TITLE
Support DNS Zone files

### ISSUE THREAD

**Issue by enko** [isagalaev/highlight.js#821]
It would be cool if highlight.js would support [dns zone files](http://en.wikipedia.org/wiki/Zone_file). I'm using highlight.js in my blog and have written an [article about dnssec](https://datenknoten.me/blog/dnssec-mit-bind-und-ovh) and especialy the dnskey example does not look so nice.

**Comment by isagalaev** [comment]
We'd be glad to have it supported too: http://highlightjs.readthedocs.org/en/latest/language-requests.html
