### ISSUE TITLE
Bower support

### ISSUE THREAD

**Issue by bennyn** [isagalaev/highlight.js#823]
Hey guys,

I really like your library and I will use it in my next project.

Are you planning to add [Bower](http://bower.io/) support and can you add [highlight.pack.js](https://highlightjs.org/static/highlight.pack.js) to your distributables? Because it seems to be different from the `highlight.js` which is in the `src` directory?

**Comment by Sannis** [comment]
This is a frequent request. Please see this [explanation why we don't do it within our own source][1]. And feel free to use a [Bower build of highlight.js from another repository][2].

[1]: https://github.com/isagalaev/highlight.js/issues/182#issuecomment-29251147
[2]: https://github.com/components/highlightjs

**Comment by Sannis** [comment]
We have prebuild highlight.pack.js on cdn.js: https://github.com/cdnjs/cdnjs/tree/master/ajax/libs/highlight.js
