### ISSUE TITLE
Pseudocode

### ISSUE THREAD

**Issue by pepelsbey** [isagalaev/highlight.js#830]
Is there a way to properly highlight such pseudocode in a single `<pre>` element?
```
<a href="#" class="button"></a>

.button {
	background-image: url(button-with-fake-text.png);
}
```
Currently it looks like this

![image](https://cloud.githubusercontent.com/assets/105274/7148090/ab515f2c-e308-11e4-8204-192f89d77730.png)

I guess it could be achieved by putting `<style>` element around CSS part, but is there any other ways to mark different parts on code “this is CSS”?

**Comment by pepelsbey** [comment]
Resulted DOM:
```
<pre><code class="hljs xml"><span class="hljs-tag">&lt;<span class="hljs-title">a</span> <span class="hljs-attribute">href</span>=<span class="hljs-value">"#"</span> <span class="hljs-attribute">class</span>=<span class="hljs-value">"button"</span>&gt;</span><span class="hljs-tag">&lt;/<span class="hljs-title">a</span>&gt;</span>

.button {
	background-image: url(button-with-fake-text.png);
}
</code></pre>
```

**Comment by isagalaev** [comment]
You could wrap parts in two separate `<code>..</code>` and highlight those separately. But highlighting different languages in one block is definitely not something we could do. It requires a human to know that the second part is in fact CSS and would benefit from being highlighted as such. For a computer it's just some text between HTML tags.

**Comment by pepelsbey** [comment]
In my case it’s just a Markdown indented by tab and it’s really hard to keep it structurally simple for authors and properly highlighted at the same time. I wonder if it could be possible to group languages that could be easily mixed (HTML, CSS, JS for example) and make the second guess for “plain text” based on this.

**Comment by isagalaev** [comment]
The problems start with something as basic as splitting code into separate blocks. What tells that lines 3-5 in your example is something that should be treated together? Working with single lines doesn't make sense. As doesn't dividing by empty lines, because a single block of code can have empty lines too.

It feels to me that the solution lies somewhere along the line of custom markup or authoring conventions for separating languages.

**Comment by pepelsbey** [comment]
I totally agree, will try to solve this on my side.
