### ISSUE TITLE
Obvious HTML detected as Stylus

### ISSUE THREAD

**Issue by pepelsbey** [isagalaev/highlight.js#831]
I have two following code samples:

```
<a href="#" class="button"></a>

.button {
	background-image: url(button-with-fake-text.png);
}
<!-- some paragraphs -->
<a href="#" class="button" aria-label="Launch missile at my own face"></a>
```
They look like this
![image](https://cloud.githubusercontent.com/assets/105274/7148155/24151764-e309-11e4-876b-75316590fa9c.png)
The second one for some reason is detected as Stylus. Source:
```
<pre><code>&lt;a href="#" class="button"&gt;&lt;/a&gt;

.button {
	background-image: url(button-with-fake-text.png);
}
</code></pre>
…
<pre><code>&lt;button&gt;&lt;span aria-label="site navigation"&gt;≡&lt;/span&gt; menu&lt;/button&gt;
</code></pre>
```
Resulted DOM:
```
<pre><code class="hljs xml"><span class="hljs-tag">&lt;<span class="hljs-title">a</span> <span class="hljs-attribute">href</span>=<span class="hljs-value">"#"</span> <span class="hljs-attribute">class</span>=<span class="hljs-value">"button"</span>&gt;</span><span class="hljs-tag">&lt;/<span class="hljs-title">a</span>&gt;</span>

.button {
	background-image: url(button-with-fake-text.png);
}
</code></pre>
…
<pre><code class="hljs stylus">&lt;<span class="hljs-tag">a</span> href=<span class="hljs-string">"#"</span> class=<span class="hljs-string">"button"</span> aria-label=<span class="hljs-string">"Launch missile at my own face"</span>&gt;&lt;/a&gt;
</code></pre>
```

**Comment by pepelsbey** [comment]
I use Highlight.js 8.4 packed with Apache, CSS, HTTP, JavaScript, Bash, JSON, Markdown, HTML, XML, Less, Stylus, SCSS.

**Comment by Sannis** [comment]
With master first one is detected as [javascript: 4, xml: 4], second one as [javascript: 5, xml: 5, stylus: 5].

**Comment by Sannis** [comment]
With current master first one is detected as [applescript: 5, processing: 5], second one as [xml: 5, autohotkey: 5].

It looks like bug with second snippet was fixed.
First snipper contains two parts from different languages, so I don't think we should do anything with it.
