### ISSUE TITLE
Can I highlight the code after changing it ? 

### ISSUE THREAD

**Issue by faressoft** [isagalaev/highlight.js#832]
The code that I want it to be highlighted is requested by Ajax many times to get updates versions of the code.

Can I highlight the code after updating the content of the <code> element with the new code ?

**Comment by faressoft** [comment]
I tried
hljs.highlight('http', data).value
But it is not working for http !

**Comment by Sannis** [comment]
Sure, you can do this. You can found example here: https://github.com/isagalaev/highlight.js/blob/master/tools/developer.html#L17
