### ISSUE TITLE
Stricter E4X/JSX parsing

### ISSUE THREAD

**Issue by isagalaev** [isagalaev/highlight.js#839]
Currently E4X is expected to be an arbitrary XML ending with `>;` which is too limited as XML can happen in other contexts too (see #494).

Since E4X is actually always a single XML element we could (try to) redefine it like this:

- don't rely on external XML highlighting
- on detecting first `<` return it to the parser and start a new "element" mode which can be either `<.../>` or `<..> .. </..>` and can be nested
- copy over attribute highlighting from xml.js

We also need to support JSXSpreadAttribute, if possible.

**Comment by Sannis** [comment]
How we should highlight them, according to latest initiatives?

**Comment by Sannis** [comment]
IMO we can leave this for some far future due to fix in #767.

**Comment by isagalaev** [comment]
I've cleared the milestone because it's not an actionable item yet, just a vague brain dump. I still think I could come up with a better idea.

**Comment by isagalaev** [comment]
I have had come up with a better idea, actually. It's a new [mode attribute `skip`][s] that can provide arbitrary complex parsing to sub-language modes without breaking them up into real parsing modes of the parent language.

[s]: https://github.com/isagalaev/highlight.js/blob/master/docs/reference.rst#skip
