### ISSUE TITLE
TypeScript fails with any reasonably complex parameters

### ISSUE THREAD

**Issue by blakeembrey** [isagalaev/highlight.js#841]
I tried to play around on `master`, but couldn't get anything to test or build. So I'm including a pretty complex use case here (completely valid) to make sure it can be covered or at least fail gracefully (currently the entirely block will not be highlighted).

```ts
function test <T>(fn: (...args: any[]) => T = <(...args: any[]) => T>function (...args: any[]) {}): T {
  return fn();
}
```

**Comment by sourrust** [comment]
I tried this snippet in master and it does highlight more than you descriptive but there are issues that I will work on.

![](https://cloud.githubusercontent.com/assets/365596/7383222/714a46b8-edd0-11e4-89bf-1911178cb9b6.PNG)

 Few questions:

* What distribution of highlight.js are you using to test this (from a cdn, our site, etc...)?
* Since you can't get highlight.js to build locally, can you post the errors you are getting from the build script?

**Comment by blakeembrey** [comment]
That certainly does look much better than I'm getting. I'm using the latest version on NPM (https://www.npmjs.com/package/highlight.js). I'm using the `highlight('ts', code)` feature, so it's not auto highlighting. To be honest, I didn't delve too far with trying to build it. Once I couldn't find an `package.json` script, a `make` file or any developer instructions I gave up.

**Comment by isagalaev** [comment]
@blakeembrey FWIW, the building instructions are here: http://highlightjs.readthedocs.org/en/latest/building-testing.html, but you've got a point that we probably should get ourselves a makefile too to make it more obvious.

**Comment by blakeembrey** [comment]
Or even adding an `build` script to `package.json`. I just discovered it by reading the `travis.yml` file, but it shouldn't be that hard. It just wasn't obvious after I'd started hacking with the code how to build it. Looking through the API docs didn't occur to me (since they're API docs), so I just checked the usual places. I think a little note on the readme would more than help on this. Or even a `CONTRIBUTING.md` file (though I don't think I looked for this first). If nothing else, a script in `package.json` is what typically works for me.

**Comment by isagalaev** [comment]
> I think a little note on the readme would more than help on this

It's actually there :-)
https://github.com/isagalaev/highlight.js#getting-the-library

**Comment by blakeembrey** [comment]
Wow, sorry. I skimmed right over that. I was looking at the headings and "getting the library" didn't register as building it.

**Comment by sourrust** [comment]
Alright, the snippet is looking way better. I've got types highlighted in arguments and the function keyword at the end isn't being incorrectly marked as a title.

![](https://cloud.githubusercontent.com/assets/365596/7384555/42efebe6-edea-11e4-98fb-014392d10761.PNG)
