### ISSUE TITLE
Ignore code blocks with unsupported languages

### ISSUE THREAD

**Issue by hubgit** [isagalaev/highlight.js#842]
If a language is specified using a classname on a code block, but that language is unsupported by highlight.js (e.g. `language-yaml`), ignore this code block rather than trying to highlight it wrongly as a different language.

**Comment by Sannis** [comment]
You can use no-highlight class for that.

**Comment by hubgit** [comment]
> You can use no-highlight class for that.

That's a good workaround, but it means knowing in advance which languages are supported for highlighting, which can change over time as they get added.

**Comment by sourrust** [comment]
The alternative way to turn off autodetection is with `hljs.configure`:

```javascript
hljs.configure({ languages: [] });
hljs.initHighlighting();
```

That way if the language isn't there, highlight.js doesn't try to guess the language itself.

**Comment by sourrust** [comment]
This is pretty much resolved so  I'm closing this issue.

**Comment by hubgit** [comment]
> The alternative way to turn off autodetection is with hljs.configure

Turning off autodetection would turn off autodetection completely, though - the aim of this issue is to keep autodetection enabled, but not to try to guess a different language when one is already specified.

**Comment by isagalaev** [comment]
One problem here is that it'd be hard to solve in a good way. We could tell that a class name is a language name only if it's prefixed by "language-". However people mostly just use unprefixed names like "php", "cpp", which highlight.js can't distinguish from any other class names having nothing to do with languages.

I'd say rather then put a usecase-specific code into core it's better to use custom initialization on the client side.

**Comment by hubgit** [comment]
If the class name _is_ prefixed with `language-` then it is definitely specifying a language - and in that case, the autodetection could be turned off.

**Comment by isagalaev** [comment]
Yes, I understand that. My point is that the prefix isn't used often enough to warrant a non-obvious special case condition in the core library. I may be very well wrong about it (I'm rather away from that part of code right now) so if it is easy to implement in a readable way I see no problem in fixing it. Could you try and make the fix? It should probably be somewhere around `highlightBlock` and `blockLanguage` functions.

**Comment by hubgit** [comment]
I've had a go at treating `language-*` as `no-highlight` if no supported language is present:
https://github.com/isagalaev/highlight.js/compare/master...hubgit:unsupported-language?expand=1 

It's a bit less efficient, so up to you whether it makes sense to include - I'll make a pull request if it's useful.

**Comment by isagalaev** [comment]
Okay, I've taken this change but while testing realized that it still would highlight blocks with classes like "c language-plain", so I've changed all that logic in dde27ca.

**Comment by hubgit** [comment]
Brilliant, thanks @isagalaev :+1:
