### ISSUE TITLE
Move Scala from "misc" language category to "functional"

### ISSUE THREAD

**Issue by non** [isagalaev/highlight.js#845]
Scala is a functional programming language that is at least as popular as Erlang, SML, etc.

We should move it from the "misc" category (which has 39 entries) into the "functional" category (which has 7).

**Comment by isagalaev** [comment]
Sure, go ahead and add `Category: functional` to the language file header. I didn't do it before simply because I'm not very familiar with the languages.

**Comment by non** [comment]
This issue will be resolved if/when #846 is merged.

**Comment by isagalaev** [comment]
Just to be clear, the new-style branch is going to be long-lived with no definite time frame. We're probably going to make a few 8.x releases before that merges back into master and becomes 9.0. So it probably makes sense to make that single change against master.
