### ISSUE TITLE
Quotes

### ISSUE THREAD

**Issue by tcurdt** [isagalaev/highlight.js#847]
The following html

    <pre><code>def map
      "bla"
    end
    </code></pre>

comes out as

    <pre><code><span class="hljs-function"><span class="hljs-keyword">def</span> <span class="hljs-title">map</span>  &amp;quot;bla&amp;quot;
    <span class="hljs-keyword">end</span></span></code></pre>

The `&amp;quot;` is not right here.

This is via `highlight.js` 8.4.0 via `gulp-highlight`

    ├─┬ gulp-highlight@1.0.0
    │ ├─┬ cheerio@0.18.0
    │ │ ├─┬ CSSselect@0.4.1
    │ │ │ ├── CSSwhat@0.4.7
    │ │ │ └─┬ domutils@1.4.3
    │ │ │   └── domelementtype@1.3.0
    │ │ ├─┬ dom-serializer@0.0.1
    │ │ │ └── domelementtype@1.1.3
    │ │ ├── entities@1.1.1
    │ │ ├─┬ htmlparser2@3.8.2
    │ │ │ ├── domelementtype@1.3.0
    │ │ │ ├── domhandler@2.3.0
    │ │ │ ├── domutils@1.5.1
    │ │ │ ├── entities@1.0.0
    │ │ │ └─┬ readable-stream@1.1.13
    │ │ │   ├── core-util-is@1.0.1
    │ │ │   ├── inherits@2.0.1
    │ │ │   ├── isarray@0.0.1
    │ │ │   └── string_decoder@0.10.31
    │ │ └── lodash@2.4.2
    │ └── highlight.js@8.4.0

**Comment by Sannis** [comment]
Looks very strange. It works well in browser with both master and 8.4 version for me.

Please, specify which languages are included in your version and how are you do it.

**Comment by tcurdt** [comment]
After digging deeper I found the problem isn't really `highlight.js`.

  https://github.com/chjj/marked/issues/590

Sorry for the noise.
