### ISSUE TITLE
CSS wrongly detected 

### ISSUE THREAD

**Issue by mydigitalself** [isagalaev/highlight.js#848]
In 8.5.0

```
.hljs-bullet,
.hljs-blockquote,
.hljs-horizontal_rule,
.hljs-number,
.hljs-regexp,
.alias .hljs-keyword,
.hljs-literal,
.hljs-hexcolor {
  color: #ae81ff;
}
```

Detected as:

```
language: 'asciidoc',
relevance: 1
...
second_best:
   { relevance: 4,
   ...
   language: 'css',
   ...
```

**Comment by mydigitalself** [comment]
Interestingly, when running it again I'm getting different relevances, perhaps I misread my output, the detection is still wrong, but the asciidoc relevance is higher:

```
Lang css  scored  4
Lang asciidoc  scored  8
```

**Comment by mydigitalself** [comment]
Thanks guys! Much appreciated. Is there an estimated release date for 8.6? Busy updating Gitter's highlight.js as we had forked a while ago and now back on highlight.js master and would love to include the CSS improvements soon.

**Comment by isagalaev** [comment]
@mydigitalself no idea at the moment. I'm currently invested in the big style refactoring and don't track master too well.
@Sannis since it's you (I guess) who made the 8.6 milestone, how about planning and making a release this time? :-)

**Comment by Sannis** [comment]
I'll go through open issues in few next days and check what we can include in next release. So we can release 8.6. at next week, I hope.
