### ISSUE TITLE
Theme assets missing from cdn;  inline via data uris?

### ISSUE THREAD

**Issue by cmawhorter** [isagalaev/highlight.js#850]
Using pojoaque theme from cdnjs, there is a missing [pojoaque.jpg image](https://github.com/isagalaev/highlight.js/blob/d9b73e9f34aac58ecbc642925278afd8e7e170b1/src/styles/pojoaque.css#L14).

Does cdnjs accept images?  If not, can we inline these in the css as data uris? 

If you're open to inlining, I can do a PR.

**Comment by isagalaev** [comment]
It's probably easier to just include .jpg in the build, it's just an omission. 

@sourrust I tried to stick `*.{css,jpg}` in tools/cdn.js:57 but it failed later at trying to minify those jpegs as CSS. I'm not sure if it warrants another build step or just some conditions to minify only .css files. The renaming should also preserve the extension. Could you pick it up?

**Comment by sourrust** [comment]
Alright the fix is merged into master. You'll have to what for the next release but the cdn build is now including the style images.
