### ISSUE TITLE
Library not work when is used as CommonJS module + browserify

### ISSUE THREAD

**Issue by unreal666** [isagalaev/highlight.js#851]
(function(factory) {

      // Setup highlight.js for different environments. First is Node.js or
      // CommonJS.
      if(typeof exports !== 'undefined') {
        factory(exports);
      } else {
        ...
      }

    }(function(hljs) {
    ...
    }))
    hljs.registerLanguage(...)

If ` exports !== 'undefined' ` (ie is used as CommonJS module), `hljs.registerLanguage` throw exception because there is no `hljs` variable.

**Comment by isagalaev** [comment]
highlight.js requires building, it's not supposed to be used from raw source: http://highlightjs.readthedocs.org/en/latest/building-testing.html

**Comment by unreal666** [comment]
I am building highlight.js as `node tools/build.js -n -t browser`.
Probably, in an amicable way, need to build for browser as:

    (function(factory) {

      // Setup highlight.js for different environments. First is Node.js or
      // CommonJS.
      if(typeof exports !== 'undefined') {
        factory(exports);
      } else {
        ...
      }

    }(function(hljs) {
      ...
      hljs.registerLanguage(...)
      hljs.registerLanguage(...)
    }))

**Comment by unreal666** [comment]
PS.
Only hamper

    return hljs;

**Comment by unreal666** [comment]
Probably, can as:

    var hljs;

    (function(factory) {

      // Setup highlight.js for different environments. First is Node.js or
      // CommonJS.
      if(typeof exports !== 'undefined') {
        hljs = factory(exports);
      } else {
        ...
      }

    }(function(hljs) {
      ...
      hljs.registerLanguage(...)
      hljs.registerLanguage(...)
    }))

**Comment by sourrust** [comment]
At the moment you need to use the node build for browserify. This is the main reason the AMD logic includes a window bound `hljs`. The work around for a smaller build for the node build would be to specify the languages or use the `common` bundle like:

```bash
node tools/build -t node :common

# or

node tools/build -t node javascript json xml css
```

**Comment by unreal666** [comment]
I guessed about node build. But my variant is inetersny.

**Comment by sourrust** [comment]
Just to let you know, you don't need to use that workaround anymore. I got the browser build working with browserify and it's in master, so you can feel free to use it or the node build I mentioned previously.
