### ISSUE TITLE
Is something wrong here?

### ISSUE THREAD

**Issue by sargeant45** [isagalaev/highlight.js#852]
I am trying to print syntax highlighted code in color and it prints like this:
![printsrc](https://cloud.githubusercontent.com/assets/8540373/7627813/53e61f00-f9d0-11e4-84f9-13cddfea6f75.png)
Even though it is syntax highlighted in the browser...
![printrl](https://cloud.githubusercontent.com/assets/8540373/7627821/66add038-f9d0-11e4-8909-5c920479e3d8.png)

This is my code:
HTML:
```html
<pre class="collapse" id="codepre"><code class="hljs" id="codeoutput"></code></pre>
```
JavaScript:
```javascript
function papercode() {
  $('link[title=printstyle]')[0].disabled=true;
  var code = document.getElementById("sourcecode").value;
  var lang = document.getElementById("lang").value;
  var output = document.getElementById("codeoutput");
  
  $("#all").hide();
  $("#codepre").collapse("show");
  
  if(lang !== null)
  {
    $("#codeoutput").addClass(lang);
    output.innerHTML = code;
    $('#codeoutput').each(function(i, block) {
      hljs.highlightBlock(block);
    });
    var capitalizedLang = lang.charAt(0).toUpperCase() + lang.slice(1);
    document.title = "Sexydown — " + capitalizedLang + " Document";
  }
  else
  {
    $('#codeoutput').each(function(i, block) {
      hljs.highlightBlock(block);
    });
    document.title = "Sexydown — Code Document";
  }
  window.setTimeout(function(){window.print();}, 1000);
}
```
CSS:
```css
pre {
  background-color: white;
  border: none;
}
```

**What am I doing wrong?**

**Comment by isagalaev** [comment]
It hardly has anything to do with what highlight.js does. May guess would be that the highlighting CSS is somehow constrained to be used only on screen media.

**Comment by sargeant45** [comment]
I figured out what it was, Bootstrap was interfering with print stylesheets.
Thanks!
