### ISSUE TITLE
Java `else if` is not highlighted properly

### ISSUE THREAD

**Issue by yihangho** [isagalaev/highlight.js#854]
Should look something like:

![Screenshot from GitHub](http://i.imgur.com/IgZTPkK.png)

but looks like:

![Screenshot from highlight.js](http://i.imgur.com/PPsbxoq.png)

**Comment by Sannis** [comment]
This should be fixed as #690.

**Comment by yihangho** [comment]
:+1: Look forward to seeing this being released!

**Comment by Sannis** [comment]
I hope this will be in a week.
