### ISSUE TITLE
Building mangles image files in styles/

### ISSUE THREAD

**Issue by isagalaev** [isagalaev/highlight.js#859]
Before build:

    -rw-rw-r-- 1 maniac maniac 1186 Aug 31  2012 src/styles/pojoaque.jpg

After build:

    -rw-rw-r-- 1 maniac maniac 1990 May 26 14:56 build/demo/styles/pojoaque.jpg

The size is different and the files are non-displayable. Some stray compression attempt, perhaps?

**Comment by sourrust** [comment]
It wasn't compression but rather the wrong encoding. I also messed up the utility function `glob` by adding the module with the same variable name, but everything is fixed now.

**Comment by isagalaev** [comment]
Got it. Thanks!
