### ISSUE TITLE
Since 8.6.0 the word "bug" is incorrectly highlighting in comments for language CSS.

### ISSUE THREAD

**Issue by philipwalton** [isagalaev/highlight.js#861]
Giving the following comments, I'm getting weird highlighting in CSS since 8.6.0.

```css
/**
 * 1. Avoid the IE 10-11 `min-height` bug.
 */
```

Here's a screenshot of what I see (with the Github theme):

![screen shot 2015-06-01 at 12 01 45 am](https://cloud.githubusercontent.com/assets/326742/7907727/e35d07d2-07f1-11e5-9ae4-2f76601b1396.png)

**Comment by Sannis** [comment]
Thanks for your report, fixed.
