### ISSUE TITLE
Mention (in README) that the browser bundle supports AMD

### ISSUE THREAD

**Issue by xixixao** [isagalaev/highlight.js#863]
There are some old docs floating around the net suggesting you need to build with python, if you google for highlight.js AMD.

**Comment by isagalaev** [comment]
We actually need a few words in the README describing our relationship with various build systems and distribution means. I'll use this open issue as a reminder to do that and mention AMD too. Thanks!

**Comment by sourrust** [comment]
I added being able to use both AMD and CommonJS in the README. All that's left is left is the russian translation.
