### ISSUE TITLE
Could we use &nbsp; and <br /> instead of ' ' and '\n' in HTML?

### ISSUE THREAD

**Issue by MrHuxu** [isagalaev/highlight.js#865]
Hi, @isagalaev 

I have used highlightjs in my own blog, and some other projects, and I have to say the I very enjoy the experience. But currently I have some trouble when highlight a markdown formatted code, that is, I found in the render result you use ```' '```and ```\n``` for white spaces and line breaks, I think this action does not make sense, it will cause some problems when show the result in web page.

Here is a [sample page](http://xhu.me/article/59*%E4%B9%96%E4%B9%96%E5%BD%93%E7%97%85%E5%8F%B7%20&%20HOJ_1628%20&%20HOJ_1629*20140605*%E6%97%A5%E5%B8%B8-HOJ.md) in my blog, I want the ```pre``` element show scroll bar when its child node is too long, I do not want any ```span``` element break line even it is wider than its parent node. But if I add the attribute ```white-space: nowrap``` to the ```span``` elements, the entire ```code``` element will shrunk to one line, because an element with that attribute will break line only when there is ```<br />```, at the same time, the indention will disappear because all extra white spaces are deleted.

But after I used regular expression to modify all the characters and using ```&nbsp;``` and ```<br />```, the white spaces and line breaks will not be affected by the attribute ```white-space```, so could highlightjs replace ```' '``` and ```\n``` with ```&nbsp;``` and ```<br />``` when formating content? And I think the latter is more suitable for HTML.

Very appreciate for your work, and I'm looking forward to your replay.

**Comment by sourrust** [comment]
I looked into what was going and and it seems your issue with long lines wrapping has more to do with bootstrap. Mainly these:

```css
pre code {
  white-space: pre wrap;
}

pre {
  word-wrap: break word;
}
```

 By default highlight.js adopts what the parent element does with overflows -- all styles have this `overflow-x: auto`. Also, the fact that you used `white-space: nowrap`, which actually [collapses whitespace][1], that is actually the real cause the other problem you had.

The solution I found, without having to resort to using `<br>` and `&nbsp;` is to do this:

```css
.hljs {
  white-space: pre;
  word-wrap: normal
}
```

I tested it out by replace `<br>` with newline literals and `&nbsp;` with space literal and it seems to work. Can you confirm if this fixes your issue or not?

[1]: https://developer.mozilla.org/en-US/docs/Web/CSS/white-space#Values

**Comment by MrHuxu** [comment]
Hi, @sourrust 

Thanks for your reply, I have tested the code in my project and it worked well. So I will close this issue, and maybe I should pay more time on learning CSS...
