### ISSUE TITLE
Not working with XML/HTML

### ISSUE THREAD

**Issue by dlinx** [isagalaev/highlight.js#866]
I tried to use this library, it worked perfectly fine with css, but its not working with xml,html code.

Tried using all methods, but it is showing output of html instead of showing html code.

**Comment by Sannis** [comment]
Can you please provide any reproducable example? It looks like you don't properly escape HTML.

**Comment by dlinx** [comment]
Here is what I did, please provide a client side html sample in documentation, which we can refer.

http://plnkr.co/edit/ecdGcjqRF71E8mJO6HlK?p=preview

**Comment by Sannis** [comment]
Yes, you should escape HTML within <pre><code> block.

Few references:
http://stackoverflow.com/questions/42182/how-to-escape-and-inside-pre-tags
http://www.w3schools.com/HTML/html_entities.asp

**Comment by be-codified** [comment]
Hi,

I know this is an old topic. So, correct me if I am wrong.

I can not do:

    <pre><code class="hljs xml">
        <h3>test</h3>
    </code></pre>

But must do

    <pre><code class="hljs xml">
        &lt;h1&gt;test&lt;/h1&gt;
    </code></pre>

**Comment by isagalaev** [comment]
@be-codified yes, correct.
