### ISSUE TITLE
Rust code loses all syntax highlighting if there is a trait declaration in there

### ISSUE THREAD

**Issue by keithamus** [isagalaev/highlight.js#867]
Moved from https://github.com/jashkenas/docco/issues/338

> An entire block of Rust code (between two comments) will lose all its syntax highlighting if there is a single trait block with a "supertrait" declaration in there. That is, even the part of the code that's correctly highlighted usually will be broken once more code is added to the end of the file. Yeah, that doesn't make much sense, but what can I say^^

> The following two files demonstrate the issue:

```js
hljs.highlight('rs', 'fn sqr(i: i32) { i * i }');
> Object {r: 3, value: "<span class="hljs-function"><span class="hljs-keyw… <span class="hljs-keyword">i32</span>) { i * i }", language: "rs", top: Object}
```

```js
hljs.highlight('rs', 'fn sqr(i: i32) { i * i }\ntrait Minimum : Copy {}');
> Object {r: 0, value: "fn sqr(i: i32) { i * i }↵trait Minimum : Copy {}"}
```

> When running docco, I would expect both of these files to get rendered with syntax highlighting. The first file works as expected. The second one lacks any form of syntax highlighting, even for its first line. If I remove the " : Copy", it's all working.

**Comment by Sannis** [comment]
Thanks for reporting this!
