### ISSUE TITLE
Suggestion: html comment as language hint in addition to class definition

### ISSUE THREAD

**Issue by Walther** [isagalaev/highlight.js#870]
In addition to specifying the highlighted language as `class="language"`, it would be useful to have the option to declare language as a HTML comment, either as

- `<!-- language: language -->` for a single codeblock (e.g. the next codeblock after such comment)
- `<!-- language-all: language -->` for specifying the language for the codeblocks of the entire document.

This feature exists in e.g. [Google Prettify](https://github.com/google/code-prettify), and is used on [StackOverflow](http://meta.stackoverflow.com/editing-help#syntax-highlighting).

It would be especially useful when writing Markdown that has codeblocks.

**Comment by isagalaev** [comment]
I'm very reluctant to add any more ways of specifying a language. Both use-cases are pretty much covered in practice:

- A language for a single block can be specified using [fenced code blocks][1] in the modern CommonMark syntax. It's still impossible to do that in pure original Markdown but I believe it's going to be phased out anyway, so I wouldn't want to add a non-trivial code to highlight.js to support this.

- A set of available languages can be configured before the initialization of highlight.js:

        hljs.configure({languages: [...]});
        hljs.initHighlightingOnLoad();

[1]: http://spec.commonmark.org/0.20/#example-94

**Comment by Walther** [comment]
Bravo, the CommonMark way of specifying the language is indeed better than adding further tags, you are absolutely right. Thanks, and sorry for an extra issue

**Comment by isagalaev** [comment]
Don't sweat about an extra issue :-) And don't hesitate raising other suggestion in the future. Thanks!
