### ISSUE TITLE
x86 assembly issues

### ISSUE THREAD

**Issue by kobalicek** [isagalaev/highlight.js#871]
Some registers in x86 assembly like `eax` and `ebx` are highlighted as numbers.

I think this is responsible for it:
```
      // Number in H,X,D,T,Q,O,B,Y suffix
      {
        className: 'number',
        begin: '\\b(?:[0-9A-Fa-f][0-9A-Fa-f_]*[HhXx]|[0-9][0-9_]*[DdTt]?|[0-7][0-7_]*[QqOo]|[0-1][0-1_]*[BbYy])\\b'
      },
```

But don't really know how HLJS works to fix this. I think that registers should have a priority over numbers in such case (don't even know if `x` suffix is used by any assembler).

**Comment by sourrust** [comment]
It seems that there isn't `x` suffixing for hexadecimal numbers in x86 and I ended up just removing that so this issue is fixed.

Thanks for reporting this.

**Comment by kobalicek** [comment]
Thanks!
