### ISSUE TITLE
How to highlight a single character?

### ISSUE THREAD

**Issue by LaKing** [isagalaev/highlight.js#872]
I would like to highlight curly braces, eg. { and } characters in a laguage, eg javascript.
What would be the recommended method?

This worked before ...
```
  // CODEPAD specials - curly braces
  hljs.CODEPAD_CB = {
        className: 'cb',
        begin: '{|}'
    };
```
.. but now, if I add this class to javascript blocks, it seems to mess it up. Is there a better approach? 

Thanks for any advice.

**Comment by isagalaev** [comment]
It looks like a fairly fragile way of doing it, as it depends on particular configuration of modes in a language definition which can change without warning. And frankly, I can't think up any more reliable way. To allow for such deep interference we will have to invent a public API or a set of conventions for language definitions that would bring complexity of the system to a whole another level…

**Comment by LaKing** [comment]
Thank you. I will try to solve the issue on my application level.
