### ISSUE TITLE
escape() method: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by viveleroi** [isagalaev/highlight.js#879]
I'm using the npm highlight.js module with webpack for a project. No matter what content I pass in, I receive the following error (I had to remove file/line info, they don't mean anything since its webpack)

    Uncaught TypeError: Cannot read property 'replace' of undefined
    escape 
    highlightAuto
    highlightBlock 

My code is:

    import Highlight from 'highlight.js';
    // inside a "render" method:
    var highlighted = Highlight.highlightBlock(this.state.body);

I've confirmed that my value is not undefined. The offending code the stack trace points to is:

    function escape(value) {
        return value.replace(/&/gm, '&amp;').replace(/</gm, '&lt;').replace(/>/gm, '&gt;');
    }

**Comment by Sannis** [comment]
Can you please post code example that you try to highlight?

**Comment by viveleroi** [comment]
Anything. I've tried it with a string, with command line snippet, and a full page of javascript.

**Comment by sourrust** [comment]
If you are using `highlightBlock` the argument that needs to be passed in is an HTML element. I'm not sure what `this.state.body` is but if it's a string, that might be the problem and you need to use either `highlight` or `highlightAuto`.

**Comment by viveleroi** [comment]
You're right, I totally mixed those up.
