### ISSUE TITLE
#include statement parses error

### ISSUE THREAD

**Issue by tl3shi** [isagalaev/highlight.js#880]
I used special tag for highlight with following code: 

```javascript
$(document).ready(function() {
            $('pre cc').each(function(i, block) {
                hljs.highlightBlock(block);
            });
        });
```
When the input is: 
```cpp
<pre><cc class="cpp">
#include <iostream>
</cc></pre>
```
the parsed result is:

```html
<pre><cc class="cpp hljs">
<span class="hljs-preprocessor">#include </span><iostream>
</iostream></cc></pre>
```

**Comment by sourrust** [comment]
You need to escape angle brackets or it will be turned into an HTML element. ie:

```html
<pre><cc class="cpp">
#include &lt;iostream&gt;
</cc></pre>
```

**Comment by tl3shi** [comment]
I do **NOT** think that it is a good way to change the original code. 
It is a **regular** and **reasonable** requirement for a highlight plugin  to render the plain code to formatted html.

**Comment by isagalaev** [comment]
@tl3shi this is not something highlight.js imposes on you, it's how HTML works: if you want angle brackets to be displayed as is, you should escape them. A highlighter might do this escaping as an extra service but then it wouldn't be able to distinguish between the tags you want to display and the real tags with `<code>..</code>` that you want to use for some reason, like this:

```html
<pre><code>
... some code ...
<span style="background: red">important line</span>
... some code ...
</code></pre>
```

**Comment by tl3shi** [comment]
Got it. So if I want to use ```hightlight.js``` to hightlight my html code, I have to escape all the tags?

**Comment by Sannis** [comment]
Yes, and this applies not only for highlight.js, this is basic HTML language rule.
