### ISSUE TITLE
Highlight.js on Blogger wraps code lines automatically

### ISSUE THREAD

**Issue by glampert** [isagalaev/highlight.js#881]
At the moment I'm facing an issue integrating highlight.js with Blogger. The syntax highlight works great, but the text lines inside the `pre/code` tags are auto wrapping. Is this the intended behavior? If yes, can we have an option to show a horizontal scroll bar instead? Looking at the [demo page](https://highlightjs.org/static/demo/) I can see that some examples have a scroll bar, so I'm guessing this is a problem with Blogger instead.

I have also opened a [StackOverflow question](http://stackoverflow.com/q/31152421/1198654) about this, so far unanswered.

Following is a screenshot of the problem I'm facing. As you can see, the code gets quite unreadable with the line wrapping:

![sample](https://cloud.githubusercontent.com/assets/2145195/8462261/fa63e23c-2008-11e5-862f-2978de6222a8.png)

**Comment by isagalaev** [comment]
It's not something highlight.js does itself, it depends on how you style your code blocks with CSS on Blogger. Most probably there's somewhere a rule setting `white-space: pre-wrap` (or similar) in your stylesheet.

**Comment by glampert** [comment]
Following your suggestion, I did some more fiddling with the CSS and was able to fix the problem by overriding the `.hljs` style, just after including the highlight.js stylesheet. Probably not the only or best fix, but this was the only one I've been able to get right. My knowledge of the Blogger API or CSS in general is limited, so the reasons it worked are also not quite clear to me.

For future reference, in case you are interested on further investigating the matter to perhaps incorporate that to the library, this is how my highlight.js include is (at the end of `<head>`):

    <link href='//cdnjs.cloudflare.com/ajax/libs/highlight.js/8.6/styles/solarized_dark.min.css' rel='stylesheet'/>
    <style type='text/css'>
		pre, code {
			white-space: pre;
			overflow-x: scroll;
		}
		.hljs {
			display: inline-block;
			overflow-x: scroll;
			padding: 0.5em;
			padding-right: 100%;
			background: #002b36;
			color: #839496;
			-webkit-text-size-adjust: none;
		}
    </style>
    <script src='//cdnjs.cloudflare.com/ajax/libs/highlight.js/8.6/highlight.min.js'></script>
    <script type='text/javascript'>
        hljs.initHighlightingOnLoad();
    </script>

**Comment by isagalaev** [comment]
Glad you had it sorted! Basically, this is how CSS is supposed to work: if a general style sheet doesn't work for you, you override it with a local rule.

**Comment by ElectricRCAircraftGuy** [comment]
Ah-ha-ha! Nice! Thanks guys! I wanted my code blocks to wrap on Google Blogger, *instead* of having the scroll-bar, so looking at these posts here I was able to determine I needed to add the following to force it to wrap my code with highlight.js syntax highlighting!

Add this between the `<head> </head>` tags at the top of the blogger theme to affect the whole website, or just to the top of a given blog post to affect that post only: 

```
<style>
pre, code {
    white-space: pre-wrap;
}
</style>
```

`pre-wrap` forces the lines to wrap. See here: https://www.w3schools.com/cssref/pr_text_white-space.asp.

> pre-wrap  Whitespace is preserved by the browser. Text will wrap when necessary, and on line breaks

**Comment by ElectricRCAircraftGuy** [comment]
> Add this between the `<head> </head>` tags at the top of the blogger theme to affect the whole website, or just to the top of a given blog post to affect that page only

Update: actually, I can't seem to get it to affect the whole website. Adding it between the  `<head> </head>` tags at the top of the blogger theme doesn't seem to work.
