### ISSUE TITLE
Help with inline `code`

### ISSUE THREAD

**Issue by aaaxx** [isagalaev/highlight.js#884]
The documentation says it’s possible to use any tags instead of `<pre><code>`, so could someone show me how to do it for just inline `<code>` element cause I'm not really well-versed in js?

**Comment by isagalaev** [comment]
Look at "[Custom initialization][1]" in the readme. The example uses `'pre code' ` but you can use `'code'` just as easily.

[1]: https://github.com/isagalaev/highlight.js#custom-initialization

**Comment by aaaxx** [comment]
Hmm, doesn't seem to work. Am I using it right?
```html
<link rel="stylesheet"  href="stylesheet.css" />
<link rel="stylesheet"  href="highlight/styles/github.css" />

<script src="highlight/highlight.pack.js"></script>

<script>
hljs.initHighlightingOnLoad();

$(document).ready(function() {
  $('code').each(function(i, block) {
    hljs.highlightBlock(block);
  });
});
</script>
```

**Comment by isagalaev** [comment]
The example requires [jQuery][] to work, you need to include it alongside `<script src="highlight.pack.js">`. Or you can use pure DOM functions instead:


```html
<script>
addEventListener('load', function() {
  var blocks = document.querySelectorAll('code');
  Array.prototype.forEach.call(blocks, highlightBlock);
), false);
</script>
```

Also, you don't need to call automatic initialization with `initHighlightingOnLoad` if you're doing custom initialization.
