### ISSUE TITLE
Support for AutoIt Script language

### ISSUE THREAD

**Issue by J2TeaM** [isagalaev/highlight.js#886]
Currently, Highlight.js has supported AutoHotkey, but I have not seen [AutoIt](https://www.autoitscript.com/) in [CSS classes reference](http://highlightjs.readthedocs.org/en/latest/css-classes-reference.html).

**Comment by isagalaev** [comment]
We'd welcome a pull request with AutoIt, too: http://highlightjs.readthedocs.org/en/latest/language-requests.html
