### ISSUE TITLE
C++ breaks on < (less than sign)

### ISSUE THREAD

**Issue by jambamamba** [isagalaev/highlight.js#890]
At this line:

for (int i = 0 ; i < NUM_THREADS; i++)

on this page http://www.osletek.com/learning-center/2107/Cracking_Encryption

the highlight breaks after <. I tried both &amp;lt; and plain <, it did not make a difference.

This is how I highlight

	$("blockquote").each(function(i, block) {
		hljs.highlightBlock(block);
	});

I am using monokai_sublime.css with custom highlight.pack.js that include c++ and swift among other languages. Version 8.6.

This looks similar to the issue #238, where it says the problem was fixed.

Also want to add that this is a great project, thank you for making this available.

**Comment by sourrust** [comment]
You forgot to configure highlight.js to expect `<br>`s rather than line breaks.

```javascript
hljs.configure({ useBR: true });

$("blockquote").each(function(i, block) {
    hljs.highlightBlock(block);
});
```

**Comment by jambamamba** [comment]
I can't believe that fixed it. Thanks!!!
