### ISSUE TITLE
Doest highlight.js support iOS/Android mobile platform?

### ISSUE THREAD

**Issue by xuguojun** [isagalaev/highlight.js#891]
@lsegal Doest highlight.js support iOS/Android mobile platform? I tried to load a local html page inside an iOS web page(with UIWebView), however the language syntax is not highlighted.

**Comment by sourrust** [comment]
I'm not familiar with working on mobile apps but highlight.js does work fine on both iOS and Android browsers. I guess the real question is if `UIWebView` allow for external javascript. If so, make sure you followed the [getting started][1] section and see if that works for you.

[1]: https://github.com/isagalaev/highlight.js#getting-started

**Comment by xuguojun** [comment]
@sourrust I've tried to highlight objective-c syntax with the following code, it works very well on desktop browsers, however it doesn't work on UIWebView:
```html
<link rel="stylesheet" href="styles/xcode.css">
<script src="highlight.pack.js"></script>
<script>hljs.initHighlightingOnLoad();</script>
```
And if I replace the above code with this code, it will show me the alert:
```html
    <link rel="stylesheet" href="http://code.jquery.com/mobile/1.3.2/jquery.mobile-1.3.2.min.css" />
    <script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
    <script src="http://code.jquery.com/mobile/1.3.2/jquery.mobile-1.3.2.min.js"></script>
    <!--
    <link rel="stylesheet" href="styles/xcode.css">
    <script src="highlight.pack.js"></script>
    <script>hljs.initHighlightingOnLoad();</script>
     -->
    
    <script src="Test.js"></script>
```

int Test.js:
```javascript
$(document).ready(function() {
                  $('pre code').each(function(i, block) {
                                     alert('It is called!!!');
                                     });
                  });
```
So, it is true that UIWebView allows for external javascript, doest it need any tricks?

**Comment by Sannis** [comment]
@xuguojun can you plovide an example of code that you tried to highlight?

**Comment by xuguojun** [comment]
@Sannis here is a code snippet (objective-c):
```objective-c
@interface KSCourseListViewController ()<KSBaseManagerDelegate, UITableViewDataSource, UITableViewDelegate,KSSwitchCategoryViewDelegate, PullTableViewDelegate>{
    
    NSArray *allCourses;
    NSMutableArray *courses;
    int coursesTotalCount;
}

@property (nonatomic, strong) UIView *noCourseView;
@property (nonatomic, strong) UIView *categoryListView;
@property (nonatomic, strong) KSSwitchCategoryView *switchCategoryView;
@property (nonatomic, strong) KSCourseListManager *courseListManager;

@end

@implementation KSCourseListViewController {
    
    BOOL isAnimationListDown;
    UIButton *beforeButton;
}

#pragma mark - initWithNibName
- (id)initWithNibName:(NSString *)nibNameOrNil
               bundle:(NSBundle *)nibBundleOrNil {
    self = [super initWithNibName:nibNameOrNil bundle:nibBundleOrNil];
    if (self) {
        self.viewMode = NavigationBarOnlyMode;
    }
    
    return self;
}
 ```

**Comment by GuessEver** [comment]
Same problem, work very well on desktop, but when I use mobile, it became actually one line.
e.g. http://paste.guessbug.com/1

**Comment by isagalaev** [comment]
@xuguojun could it be that the highlight.js does in fact mark up your code with `<span>`s but the stylesheet is not picked up and hence this markup doesn't get any styling? (I've no idea if it's possible to look into the generated DOM source of the page in UIWebView.)

**Comment by xuguojun** [comment]
@Sannis @isagalaev this bug still exists, not fixed.

**Comment by isagalaev** [comment]
@xuguojun I don't think either of us can fix it, as the bug is only triggered in an environment that we don't have access to. I will be happy to offer some insight as to how highlight.js works to anyone familiar with iPhone development who decides to tackle it. Closing for now as non-actionable.

**Comment by DimonDeveloper** [comment]
My code works on iPad, and on the iPhone, too, should work.
```
NSStringEncoding encoding;
        NSError* error;
        NSString *htmlString = [NSString stringWithFormat:@"<html lang=\"en\">\n<head>\n  <meta charset=\"utf-8\">\n  <link rel=\"stylesheet\" href=\"styles/xcode.css\">\n</head>\n<body>\n\t<script src=\"highlight.pack.js\"></script>\n\t<script>hljs.initHighlightingOnLoad();</script>\n\t<script>hljs.listLanguages()</script>\n\t<pre ><code>\n\t%@\t\n\t</code></pre>\n</body>\n</html>",[NSString stringWithContentsOfFile:FilePath usedEncoding:&encoding error:&error]];
        
[WebFileWebView loadHTMLString:htmlString baseURL:[NSURL fileURLWithPath:
                                                           [NSString stringWithFormat:@"%@/CodeHighlighter/",
                                                            [[NSBundle mainBundle] bundlePath]]]];
```
![screen shot 2015-09-20 at 6 36 42 pm](https://cloud.githubusercontent.com/assets/3527457/9981466/96563b02-5fc6-11e5-9cb1-8ea24472f6d0.png)

**Comment by renmoqiqi** [comment]
> My code works on iPad, and on the iPhone, too, should work.
> 
> ```
> NSStringEncoding encoding;
>         NSError* error;
>         NSString *htmlString = [NSString stringWithFormat:@"<html lang=\"en\">\n<head>\n  <meta charset=\"utf-8\">\n  <link rel=\"stylesheet\" href=\"styles/xcode.css\">\n</head>\n<body>\n\t<script src=\"highlight.pack.js\"></script>\n\t<script>hljs.initHighlightingOnLoad();</script>\n\t<script>hljs.listLanguages()</script>\n\t<pre ><code>\n\t%@\t\n\t</code></pre>\n</body>\n</html>",[NSString stringWithContentsOfFile:FilePath usedEncoding:&encoding error:&error]];
> 
> [WebFileWebView loadHTMLString:htmlString baseURL:[NSURL fileURLWithPath:
>                                                            [NSString stringWithFormat:@"%@/CodeHighlighter/",
>                                                             [[NSBundle mainBundle] bundlePath]]]];
> ```
> 
> ![screen shot 2015-09-20 at 6 36 42 pm](https://cloud.githubusercontent.com/assets/3527457/9981466/96563b02-5fc6-11e5-9cb1-8ea24472f6d0.png)

it work ？

**Comment by jap1968** [comment]
Still experiencing this problem. I have done some tests and it works on every platform except on iPad (iOS)

**Comment by joshgoebel** [comment]
@jap1968 You'll need to provide us more details if you're looking for assistance.  As others have said (and I've just confirmed) Highlight.js works on the iPad just fine.  You can confirm this in Safari or any of the other browsers (which all use Apple's WebKit framework underneath).  I tested Safari, Chrome, and Firefox.

I'd suggest starting over with just a barebones project with nothing but Highlight.js, HTML, CSS, and a tiny sample piece of code.  It's almost certainly an issue with how you're integrating the library or something simple your missing unless your iPad is very old.
