### ISSUE TITLE
Certain SQL locks up my app

### ISSUE THREAD

**Issue by adam-lynch** [isagalaev/highlight.js#896]
(My [NW.js](https://github.com/nwjs/nw.js) app)

I'm finding it hard to build a non-minfied browser version which works so I can't debug it myself, but a customer of mine input some SQL which causes the app to lock up. I've reproduced it myself.

I have the SQL in question but I'd prefer not to share it on GitHub just because it's the customers and senstive. I could share it with a contributor via email maybe?

**Comment by isagalaev** [comment]
There's the `-n` flag for the build tool that prevents minification:

    node tools/build.js -n

Also, you could send a fragment with the problem to info@highlightjs.org (this is me, in fact.)

**Comment by Sannis** [comment]
Or just post it here :+1:

**Comment by adam-lynch** [comment]
Here it is (redacted bits): https://gist.github.com/adam-lynch/1d27c1f168b7af9cf9f1

**Comment by Sannis** [comment]
Works fine for me in master, for bot :all and :common languages bundles.

Which browser are your customer uses?

**Comment by adam-lynch** [comment]
I've personally reproduced it in NW.js@0.12.2 so that's Chrome 43.

**Comment by adam-lynch** [comment]
More info which might not help: We get this module via bower. We've `~8.3.0` in our `bower.json`. Our usage is: `hljs.highlightBlock(element)` where `element` is a `<code>` element

**Comment by adam-lynch** [comment]
Fine with 8.7.0

**Comment by isagalaev** [comment]
Sorry for dropping out of the conversation! Yes, 8.3 indeed has the lock-up problem in one of the languages. Glad you've found this was your case, too.
