### ISSUE TITLE
Inserting characters

### ISSUE THREAD

**Issue by jayseeg** [isagalaev/highlight.js#898]
I'm seeing unexpected output with JSX in a `<pre><code data-trim class="jsx">` block
```
				    <pre><code data-trim class="jsx fragment">
return (
	<MyComponent
		style={{
			minHeight:350,
			color:'red',
			backgroundColor:'black',
			width:'36em',
			position:'relative',
		}}
	>
		<div
			style={{
				position: 'absolute',
				top: 16,
				left: 16,
			}}
		>
			Some stuffs.
		</div>
	</MyComponent>
)
				    </code></pre>
```

is outputting:

```
return (
  <mycomponent style="{{" minheight:350,="" color:'red',="" backgroundcolor:'black',="" width:'36em',="" position:'relative',="" }}="">
    <div style="{{" position:="" 'absolute',="" top:="" 16,="" left:="" }}="">
      Some stuffs.
    </div>
  </mycomponent>
)
```

The line breaks aren't expected, neither are the equals and quotes, and the lowercasing is undesirable. 

I'm using highlight in a reveal.js presentation.
My config looks like:
```
{ src: 'plugin/highlight/highlight.js', async: true, condition: function() { return !!document.querySelector( 'pre code' ); }, callback: function() { hljs.configure({
  tabReplace: '  ', // 2 spaces
}); hljs.initHighlightingOnLoad(); } }
```
Have I missed a configuration setting somewhere?

**Comment by jayseeg** [comment]
Following up, putting quotes around the double curly kinda of resolves the line breaks, equal symbols, and superfluous quotes. However, forcing quotes around the double curly brackets is invalid jsx. The mandatory lowercase is not a good pattern for jsx either.

**Comment by Sannis** [comment]
Are you sure that you want to use not escaped HTML inside <pre><code>?

**Comment by jayseeg** [comment]
I think I may have missed something,... but that's not actually HTML. It's JSX syntax which happens to look a lot like HTML. (https://facebook.github.io/react/docs/jsx-in-depth.html) JSX, in case you're not familiar, is essentially a JS file that can contain JSX syntax templates inside an expression. JSX get's compiled down to JS and the JSX syntax template is converted from that XML like syntax to a series of nested virtual dom function calls.
Highlight seems to be interpreting the attributes as HTML element attributes which it tries to wrap in quotes and remove what would be superfluous line breaks inside the tag. However, one of the distinctions between HTML & JSX is that the attributes are actually called 'props' which only require quotes around strings, but uses unquoted curly brackets to wrap around any inline use of JS. It is also common practice to list the props with line breaks.
This presentation is centered around how to use JSX, and the slides this is a problem for are about alternative code styles. It's important to show this specific style for the following alternative style slides to make sense.
I may be misunderstanding, but are you saying that without the changes Highlight is making, the code inside the `<pre><code>` block would be picked up as DOM elements by the browser? I thought `<pre><code>` allowed for uninterpreted HTML?

**Comment by isagalaev** [comment]
> I may be misunderstanding, but are you saying that without the changes Highlight is making, the code inside the <pre><code> block would be picked up as DOM elements by the browser?

Spot on! The `<code>` tag is not special in HTML, it doesn't change the escaping rules and you can have arbitrary markup within it as if with any other HTML tag. If you want your JSX snipped to be displayed literally (with or without highlighting) you should escape angle brackets with `&lt;` and `&gt;`.

(BTW, `class="jsx"` doesn't mean anything to highlight.js as we don't have a separate "jsx" language, instead we have JavaScript that does recognize JSX/E4X markup.)

**Comment by jayseeg** [comment]
I see now. Can't believe I got caught by such a basic concept! Thanks for taking the time to set me straight!
