### ISSUE TITLE
ES2015 string literals / template string

### ISSUE THREAD

**Issue by sebald** [isagalaev/highlight.js#901]
Hi,

I ran into a problem when `highligh.js` has to parse ES2015 string literals. As soon as inside the code block are grave accents (\`) its seems like `highligh.js` just skipps the content.

E.g.

```javascript
let template = `Hello ${name}!`;
```

Did someone ran into the same problem?

**Comment by Sannis** [comment]
Snippet that you provide detected as nimrod now.
