### ISSUE TITLE
Make listLanguages() include friendly name of language

### ISSUE THREAD

**Issue by azzlack** [isagalaev/highlight.js#904]
I.e. return an array that looks like this:

```
[
    { id: 'cs', name: 'C#' },
    { id: 'js', name: 'Javascript' },
    { id: 'md', name: 'Markdown' },
]
```

**Comment by isagalaev** [comment]
Implementing this would be non-trivial as currently those names are only known to a build tool that treats top comment section of the language definition as meta data. And these names simply aren't present in the final code. It also is going to be a backwards incompatible change (or a completely new API method, which is ugly).

What is the use case for that?
