### ISSUE TITLE
isNotHighlighted has bad rexExp

### ISSUE THREAD

**Issue by serheyShmyg** [isagalaev/highlight.js#905]
Hey.

```javascript
function isNotHighlighted(language) {
    return /no-?highlight|plain|text/.test(language);
}
```

This peace of code has a bug.
When I use such class as "text-toggle__content js-clipboard-text" for PRE or CODE,  highlight.js isn't initialize.
Can you fix this regular expression please, that is detect only "text" class without prefixes(sufixes).
Recommend do the same thing with another words in regular (no-?highlight an plain)!

You can use this regExp
```javascript
/no-?highlight|plain|(?:^|\s)text(?:\s|$)/
```

Thank you.

**Comment by sourrust** [comment]
Alright, I fixed the regular expression to no long match class names containing a no highlight keyword. Thanks for reporting this.
