### ISSUE TITLE
Display block for .hljs class

### ISSUE THREAD

**Issue by serheyShmyg** [isagalaev/highlight.js#906]
Hello.
I think it's not good use display:block style for every "hljs" class, because this element could be hidden by default or inline.

**Comment by Sannis** [comment]
I think this should not be in highlight.js itself: some elements may be hidden because them should be hidden.

**Comment by isagalaev** [comment]
The reason why .hljs has display: block is to make an line `<code>` element to have a scroll bar. This is only a default behaviour and can be overruled with a local style.
