### ISSUE TITLE
JavaScript single line comments.

### ISSUE THREAD

**Issue by gskinner** [isagalaev/highlight.js#907]
Single line comments in Javascript are not terminated at end of line. Everything after `//` is formatted as a comment regardless of subsequent line breaks.  See the attached image showing the incorrect output.
 
![screen shot 2015-08-14 at 2 58 39 pm](https://cloud.githubusercontent.com/assets/157128/9284001/6b1e1b24-4295-11e5-8d6e-05eee7e6b69f.png)

![screen shot 2015-08-14 at 3 02 39 pm](https://cloud.githubusercontent.com/assets/157128/9284020/9a449ef0-4295-11e5-9d2c-fea30503304b.png)

In the off chance it makes a difference, I'm calling hljs manually: `hljs.highlightBlock(codeTag);`

**Comment by gskinner** [comment]
I haven't dug super deeply into this yet, but I did play with changing the end pattern. ex. `hljs.CLCM.e = "a";`, and it still never finds an end for the line comment. I compared against the block comment object CLBM, and can't see any obvious differences that would account for one working but the other not, but can't see anything obvious.

**Comment by sourrust** [comment]
With the screenshots alone, I'm assuming you didn't configure highlight.js to expect `<br>`s rather than line breaks. You need to call `hljs.configure({ useBR: true })` before  `hljs.highlightBlock(codeTag)` and see if that fixes you single line comment issue.

**Comment by gskinner** [comment]
That did it. Apologies for the noise.

**Comment by Tuning-Soft** [comment]
Great, thank you!
