### ISSUE TITLE
Add initHighlight callable multiple times.

### ISSUE THREAD

**Issue by adjohnson916** [isagalaev/highlight.js#909]
Add a variant of `initHighlight` function that can be called multiple times. Useful for single-page applications with lazy-loaded content, that don't wish to specifically target new code blocks and highlight them manually.

Currently this can be accomplished as follows:
```js
hljs.initHighlighting.called = false;
hljs.initHighlighting();
```

But that seems bad practice as it's more complicated than necessary, and encourages manipulation of an internal variable.

We could do:
```js
hljs.initHighlighting(true);
```

But some might not like the [boolean trap](http://ariya.ofilabs.com/2011/08/hall-of-api-shame-boolean-trap.html). In which case, we could do:
```js
hljs.initHighlighting({force: true});
```
or:
```js
hljs.initHighlighting({once: false});
```

Thoughts? I can submit a pull request.

**Comment by isagalaev** [comment]
The purpose of `initHighlighting` (and `initHighlightingOnLoad` for that matter) is to be a simple shortcut for the most common case. Instead of parametrizing those there are other methods that do the job: a DOM-level `highlightBlock` and lower level `highlight` and `highlightAuto`. Anything that you want from `initHighlighting` can be done with `highlightBlock`.

**Comment by adjohnson916** [comment]
@isagalaev Yes, `initHighlighting` is a shortcut for the most common case. In the context of single page applications (SPAs) or AJAX sites, would you not expect the desire to conveniently re-run to be even more common than the run-once behavior?

If you aren't open to it, I will submit a pull request - I was just looking for feedback on the API surface for the implementation.

P.S. I haven't looked at whether `highlight` checks whether it's already been called on an element, and in such cases can skip processing them. But were that supported, if could help performance, especially when used in the way I describe.

**Comment by isagalaev** [comment]
> In the context of single-page applications (SPAs) or AJAX sites, would you not expect the desire to conveniently re-run to be even more common than the run-once behavior?

No, not really. While the desire to highlight new code blocks is pretty straight-forward the details would differ: people use millions of different frameworks with different tools for reacting at new code blocks. Resorting to some global function that does or does not what you want is far less convenient than just calling `highlightBlock` or `highlightAuto` on new content. This also takes care of filtering out already highlighted elements.

And if you do want such a function in your particular case it's a simple two-liner, really:

```
var blocks = document.querySelectorAll('pre code:not(.hljs)');
Array.prototype.forEach.call(blocks, highlightBlock);
```
So I'd say `highlightBlock` is an adequate API and adding wrappers around it is a slippery slope of chasing all the slightly different variants that people would want.

**Comment by adjohnson916** [comment]
@isagalaev That's fine, it's just not very convenient. I'll close for now, and maybe you would reconsider if anyone else asks for it in the future.

**Comment by speige** [comment]
+1
