### ISSUE TITLE
Matching version scheme

### ISSUE THREAD

**Issue by idleberg** [isagalaev/highlight.js#910]
Is there a specific reason why the project uses a different versioning scheme for GitHub releases, while it uses SemVer for npm? In my opinion, these two should match.

I'm asking because I noticed that David DM reports an outdated version of highlight.js when sticking to the GitHub tags in `package.json`:

    "highlight.js": "isagalaev/highlight.js#8.7"

![screen shot 2015-08-17 at 16 41 01](https://cloud.githubusercontent.com/assets/1504938/9307430/c95f3fb8-44fe-11e5-8754-708fb13b63da.png)

Might not be a huge issue, more of an oddity.

**Comment by Sannis** [comment]
We use `X.Y` for historic reasons and `X.Y.Z` for npm package because npm have strict rules for `package.json` fields.

@isagalaev IFAIR you have reasonable answer why we don't use SemVer for build?

**Comment by isagalaev** [comment]
There was a discussion some time ago about semver in general in #182, here's the relevant bit from me:

> The [semver] spec does make perfect sense but not enough for me to care, sorry :-). Though our process is compatible with what semver is proposing, we never distinguished between "fixing bugs" and "adding compatible functionality", as it doesn't add much value. The only thing that downstream usually cares about is whether an update is supposed to break things or not (and they still have to test it in any case).

However by now I'm probably +0 for actually changing our versioning to x.y.z if only for the sole reason of decreasing confusion amongst the JS ecosystem. And it probably won't cost us anything.

@Sannis, @sourrust what's your opinion on that?

**Comment by Sannis** [comment]
I'm also have neitral opinion about this in case of highlight.js, but looking on how many third-party bundles append `.0` to original version (and also we do for `package.json`) I think we can do that.

-----

Maybe we should not break current releases scheme and use patch version to fix critical bugs in major/minor releases. It looks compatible with SemVer.

**Comment by isagalaev** [comment]
> Maybe we should not break current releases scheme and use patch version to fix critical bugs in major/minor releases.

This had already been done in 6.0.1 and 7.0.1. The only difference is that we always omitted the third part instead of using .0.

Anyway, I documented the three-part version for the release process now and I believe everything should go smooth, including both of our CDNs.
