### ISSUE TITLE
Programmatic way of loading CSS?

### ISSUE THREAD

**Issue by drom** [isagalaev/highlight.js#912]
I am using the npm package and browserify it.

```js
var hl = require('highlight.js')

var root = document.createElement('pre')
root.innerHTML = hl.highlightAuto('function foo(a){\n  return a+1\n}').value
document.body.appendChild(root)
```
This way it can be used with http://requirebin.com

http://requirebin.com/?gist=7ac2d019b8ed89419bd5

I am looking for some programmatic way of getting CSS setup without the need to include CSS into HTML.
--Alexey

**Comment by Sannis** [comment]
There are  some variants here:
* http://stackoverflow.com/questions/574944/how-to-load-up-css-files-using-javascript
* http://stackoverflow.com/questions/2685614/load-external-css-file-like-scripts-in-jquery-which-is-compatible-in-ie-also

**Comment by drom** [comment]
My request was rather related to the internal `highlight.js` capability as a tool.
If one can require the tool from npm and browserify i, then having on-board CSS initialization might be a good idea ?

**Comment by isagalaev** [comment]
I don't think it's a good idea for a library to include glue code for every environment it can be used in, to be honest.

**Comment by drom** [comment]
You are right @isagalaev , it is your code, and in the end of the day you are free to decide on it.
But just for a second, consider my :train: of though:
* `node` is my environment.
* `npm` is a `node` package manager of my choice.
* I have discovered great `node` package on the `npm` that somebody @isagalaev published.
* I am installing it, and require it in my code; as any other `npm` package. :trophy: 
```js
var hl = require('highlight.js');
```
* `hl` object exposes bunch of useful functions. I can run it to get HTML I need! :+1: 
```js
var html = hl.highlightAuto('function foo(a){\n  return a+1\n}').value;
```
* naively, I have expected to get relevant CSS the same way I am getting HTML. By running some function! Is it "every environment" ? I don't think so. It is "the environment", the `node`. Is it "glue code", may-be but IMHO, it is convenient.

**Comment by isagalaev** [comment]
> naively, I have expected to get relevant CSS the same way I am getting HTML. By running some function!

This is where you lost me. Presumably you're going to display the formatted code on some web page, and styles are usually linked to to web pages with `<link rel="stylesheet">`. I don't even understand what an API function is supposed to do here. Generate a link tag? Or content of a CSS file?

Highlight.js is widely used on node.js and until this moment nobody asked what you're asking. This is why I assumed your environment being in some way special.

**Comment by drom** [comment]
Sorry for asking something, that nobody asked :smirk: 
Assuming you functions returning HTML as-a-string, it make sense returning CSS as-a-string.
Considering the following code; and function `hljs__css` being part of `highlight.js` package; someOne may use it this way:

```js
var hl = require('highlight.js'),
    insertCss = require('insert-css');

function hljs__css (name) {
  var css = {
    github: '.hljs-keyword { color: #333; font-weight: bold;}'
  };
  return css[name];
}

insertCss(hljs__css('github'));

var root = document.createElement('pre')
root.innerHTML = hl.highlightAuto('function foo(a){\n  return a+1\n}').value
document.body.appendChild(root);
```
https://gist.github.com/drom/d95eb5f6d5f3e30743e6
http://requirebin.com/?gist=d95eb5f6d5f3e30743e6

**Comment by isagalaev** [comment]
To wrap it up…

We're not going to do this after all because:

- An API call returning the contents of a CSS file doesn't provide much value as there's already an established way to do it: linking a file from HTML.
- Implementing it by packing the CSS contents into a the .js module would increase its size, most of which would be a useless load in a browser environment as people tend to use only one theme.
- In a server environment it can already be done by simply reading a file (as the documentation of "insert-css" suggests, by the way)
- Expectation of having a CSS-producing method symmetric to an HTML-producing one is subjective and not at all common, as far as I can see.
