### ISSUE TITLE
Case-sensitive language classes

### ISSUE THREAD

**Issue by mindplay-dk** [isagalaev/highlight.js#913]
Took me a while to figure out why only some of my code blocks were being highlighted.

It turns out, `<code class="language-php">` is being highlighted, but `<code class="language-PHP">` is not, and I'm not very consistent with fencing off my code-blocks, because e.g. GitHub doesn't care.

I am changing all my code-blocks to use lower-case, so not really a problem, but having to sit around and try to figure out why it doesn't work seems unnecessary.

CSS class-names/selectors are case-insensitive.

Can we make the language mapping case-insensitive?

**Comment by isagalaev** [comment]
Seems reasonable and easy to do. Would you care to make a patch? There's [blockLanguage][] function that is responsible for this.

[blockLanguage]: https://github.com/isagalaev/highlight.js/blob/master/src/highlight.js#L46

**Comment by mindplay-dk** [comment]
@Sannis beat me to it ;-)
