### ISSUE TITLE
XML highlighting breaks because of special treatment for style

### ISSUE THREAD

**Issue by damirarh** [isagalaev/highlight.js#914]
XML highlighting breaks on the following XAML snippet:

    <Style TargetType="TextBox">
      <Style.Triggers>
      </Style.Triggers>
    </Style>

As far as I can see the reason is special treatment of `style` because of HTML. I understand this makes sense for HTML but it doesn't for any XML flavor, e.g. XAML as above. Why not have HTML as a separate language and keep XML generic without special cases of any kind?

**Comment by isagalaev** [comment]
They used to be apart long ago but have been merged to reduce maintenance. But the problem you describe is real, so we have to find a way around it. Thanks for reporting it!

Current idea: make HTML a separate language with `subLanguage: 'xml'` at the root mode and define only styles, scripts etc. One problem is that it will have extra `<span class="xml">` within `<code>`.
