### ISSUE TITLE
No language support for CGI data

### ISSUE THREAD

**Issue by wreiske** [isagalaev/highlight.js#915]
I'd like to see support for CGI strings.

Example:
```
?page=My%20Page&zip_code=46800&q=hidden
```

**Comment by Sannis** [comment]
You want to user this as one-line snippets? It can be done if there is "?" mark first, otherwise it may cause many misdetections IMO.

**Comment by isagalaev** [comment]
@Sannis are you going to implement it? If not, then there's no point in just keeping an open issue without an implementation.
