### ISSUE TITLE
Using highlight.js with React.js

### ISSUE THREAD

**Issue by kaushik94** [isagalaev/highlight.js#925]
I am trying to configure highlightjs in a reactjs application to detect and highlight json. But it doesn't work, any workaround ? I need it on the browser side btw.

**Comment by Sannis** [comment]
To suggest any "workaround" we need to know what was the problem :-) Can you provide any example that does not work?

**Comment by kaushik94** [comment]
@Sannis thanks for the quick response, my bad.
In my index.html
```
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/8.4/styles/default.min.css">
<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/8.4/highlight.min.js"></script>
<script>hljs.initHighlightingOnLoad();</script>
```
In my react component
```
var Pretty = React.createClass({
    render: function() {
        return <pre className="custom-json-body"><code className="json">{JSON.stringify(this.props.json, null, 2)}</code></pre>;
    }
});
```
But it isn't highlighting.

**Comment by kaushik94** [comment]
I tried with `class` and `className` as well. No luck.

**Comment by Sannis** [comment]
`hljs.initHighlightingOnLoad();` higlights code on page once after page is loaded.
If you need highlight dinamically loaded content - this is your responsability. We provide `hljs.highlight()` method for that, so you can include it to React.js `render` callback. I also think that React.js should provide some post-render events that you can listen and highlight rendered block there.

**Comment by kaushik94** [comment]
> hljs.initHighlightingOnLoad(); higlights code on page once after page is loaded.

@Sannis thanks a lot. Its solved now. In fact I called `hljs.initHighlightingOnLoad();` when the page has been loaded but I did not wait for that particular component to load. 
> I also think that React.js should provide some post-render events that you can listen and highlight rendered block there.

React provides this, just for future reference
```
var Pretty = React.createClass({
    componentDidMount: function(){
        hljs.initHighlightingOnLoad();
        var current = React.findDOMNode(this);
        hljs.highlightBlock(current);
    },
    render: function() {
        return <pre className="custom-json-body"><code className="json">{JSON.stringify(this.props.json, null, 2)}</code></pre>;
    }
});
```
Let me know if there is a better way to do this. Thanks a lot.

**Comment by Sannis** [comment]
Great! Unfortunately, I'm not familiar with react to suggest something better. But it looks like you do double work in componentDidMount.

**Comment by kaushik94** [comment]
Ohh okay I just realised that for some reason `hljs.initHighlightingOnLoad();` doesn't do anything at all. So finally its
```
componentDidMount: function(){
    var current = React.findDOMNode(this);
    hljs.highlightBlock(current);
 }
```

**Comment by isagalaev** [comment]
> Ohh okay I just realised that for some reason hljs.initHighlightingOnLoad(); doesn't do anything at all.

What it does is binds itself to the onload event of the browser which by that moment has probably already been fired. `highlightBlock()` is the main method anyway.

**Comment by vonkanehoffen** [comment]
For anyone (like me) who finds this issue: https://github.com/akiran/react-highlight
:-)

**Comment by Savinien92** [comment]
/**
 * REACT IMPORT
 */
import React from 'react'

/**
 * HIGHLIGHT IMPORT
 */
import hljs from 'highlight.js'
import javascript from 'highlight.js/lib/languages/javascript'
import '../../node_modules/highlight.js/styles/darcula.css'

/**
 * ENABLE FUNCTION
 */
hljs.registerLanguage('javascript', javascript)

/**
 * COMPONENT
 */
export class Highlighter extends React.PureComponent {

  componentDidMount(){
    hljs.highlightBlock(this.node)
  }

  render() {
    let { children } = this.props
    return (
      <pre
        ref={(node) => this.node = node}
      >
        <code className="javascript">
          {children}
        </code>
      </pre>
    )
  }
}

export default Highlighter

**Comment by Savinien92** [comment]
```
import React from 'react'
import hljs from 'highlight.js'
import javascript from 'highlight.js/lib/languages/javascript'
import '../../node_modules/highlight.js/styles/darcula.css'
hljs.registerLanguage('javascript', javascript)

export class Highlighter extends React.PureComponent {

  componentDidMount(){
    hljs.highlightBlock(this.node)
  }

  render() {
    let { children } = this.props
    return (
      <pre
        ref={(node) => this.node = node}
      >
        <code className="javascript">
          {children}
        </code>
      </pre>
    )
  }
}

export default Highlighter
```

```
<Highlighter>
     {'function(){let test = [\'test\', \'test 2\']}'}
</Highlighter>
```

**Comment by Farhad33** [comment]
> For anyone (like me) who finds this issue: https://github.com/akiran/react-highlight
> :-)

this library has a lot of side effects.

**Comment by CodyFitzpatrick** [comment]
@f

> > For anyone (like me) who finds this issue: https://github.com/akiran/react-highlight
> > :-)
> 
> this library has a lot of side effects.

@Farhad33 Like what? I'm very interested to know being that I just incorporated it into my project.

**Comment by CodyFitzpatrick** [comment]
> > For anyone (like me) who finds this issue: https://github.com/akiran/react-highlight
> > :-)
> 
> this library has a lot of side effects.

@Farhad33 Like what? I'm very interested to know, being that I just incorporated this package into my project.

**Comment by eastrd** [comment]
> > > For anyone (like me) who finds this issue: https://github.com/akiran/react-highlight
> > > :-)
> > 
> > 
> > this library has a lot of side effects.
> 
> @Farhad33 Like what? I'm very interested to know, being that I just incorporated this package into my project.

I have already experienced unstable DOMExceptions with this library and seen these errors posted as issues but unanswered...

**Comment by twistezo** [comment]
For everyone who didn't find any working answer above.

React: 16.8.2 working example:
```javascript
import hljs from "highlight.js";
import "./dracula.css";

class Preview extends Component {
  componentDidMount() {
    this.updateCodeSyntaxHighlighting();
  }

  componentDidUpdate() {
    this.updateCodeSyntaxHighlighting();
  }

  updateCodeSyntaxHighlighting = () => {
    document.querySelectorAll("pre code").forEach(block => {
      hljs.highlightBlock(block);
    });
  };

  render() {
    return (
    <div
        className="content"
        dangerouslySetInnerHTML={{ __html: this.props.parsedText }}
    />
    );
  }
}
```
Note that `updateCodeSyntaxHighlighting` should be in `componentDidMount` and `componentDidUpdate` methods in every component which use `<pre><code>...` tags.

**Comment by vittoriozamboni** [comment]
I have a slightly different solution that registers only the language you actually need by importing them once.

React 16.8.2:

```javascript
import React, { Component } from 'react';
import PropTypes from 'prop-types';
import hljs from 'highlight.js/lib/highlight';   // import hljs library
import 'highlight.js/styles/hopscotch.css';      // import your preferred style

const registeredLanguages = {};   // keep a record of registered languages

export class CodeHighlight extends Component {
    constructor(props) {
        super(props);                
        // do not show anything until language is loaded
        this.state = { loaded: false };
        // create a ref to highlight only the rendered node and not fetch all the DOM
        this.codeNode = React.createRef();
    }

    componentDidMount() {
        const { language } = this.props;
        if (language && !registeredLanguages[language]) {
            try {
                const newLanguage = require(`highlight.js/lib/languages/${language}`);
                hljs.registerLanguage(language, newLanguage);
                registeredLanguages[language] = true;
                this.setState(
                    () => { return { loaded: true }; },
                    () => { this.highlight(); }
                );                
            } catch (e) {
                console.error(e);
                throw Error(`Cannot register and higlight language ${language}`);
                // We can alternatively set loaded to true and show an error message in the
                // code block instead of children, or just show the children without highlight.
                // This would be an improvement or an optional behavior given a special prop.
            }
        } else {
            this.setState({ loaded: true });
        }
    }

    componentDidUpdate() {
        this.highlight();
    }

    highlight = () => {
        this.codeNode && this.codeNode.current && hljs.highlightBlock(this.codeNode.current);
    }

    render() {
        const { language, children } = this.props;
        const { loaded } = this.state;
        if (!loaded) return ''; // or show a loader

        return <pre>
            <code ref={this.codeNode} className={language}>{children}</code>
        </pre>;
    }
}

CodeHighlight.propTypes = {
    children: PropTypes.node.isRequired,
    language: PropTypes.string,
};
// optionally set the language you think will use most as a default value
// if you don't set this, I would encourage to make language prop required, 
// or at least improve the "else" statement in "componentDidMount"
CodeHighlight.defaultProps = {
    language: 'javascript',
};
```

Usage:

```javascript
// Use the default language, if set
<CodeHighlight>
    {JSON.stringify(myObject, null, 4)}
</CodeHighlight>
```

```javascript
// Specify a language
<CodeHighlight language="python">
    {JSON.stringify(myObject, null, 4)}
</CodeHighlight>
```

**Comment by gusbemacbe** [comment]
Witaj @twistezo and ciao @vittoriozamboni 

Do your codes support third-party languages like https://github.com/highlightjs/highlightjs-cypher?

**Comment by yyyc514** [comment]
Sure. Just import and register the 3rd party grammar after you import the main library.

**Comment by gusbemacbe** [comment]
WItaj @twistezo, ciao @vittoriozamboni and hello @yyyc514 !

Thank you, I have just updated the repo's README, adding React instruction.

**Comment by ExtraHash** [comment]
After struggling for some time with these solutions, I stumbled across the `highlightAuto` method, which is designed for generating the highlights server-side, but it worked very nicely in a functional component.

```ts
import React from "react";
import hljs from "highlight.js"; // import hljs library

export function Highlighter(content: string): JSX.Element {
    const highlighted = hljs.highlightAuto(content)

    return (
        <pre className="hljs">
            <code className="hljs" dangerouslySetInnerHTML={{ __html: highlighted.value }} />
        </pre>
    );
}

```

**Comment by joshgoebel** [comment]
Or `highlight` if the component was aware of the language, etc... those are the two API calls for doing slightly more "manual" integrations, like building a component for a framework.

**Comment by ExtraHash** [comment]
Thanks for making me aware of the highlight method, it's much faster. I updated the component.

**Comment by joshgoebel** [comment]
>  it's much faster.

It should be, but most shouldn't notice unless you're highlighting a LOT of code.

**Comment by subwaymatch** [comment]
@ExtraHash Thanks for the brilliant solution! I was looking for a simple hljs component to use with Next.js and your snippet did the trick. 🙏 I removed the `className="hljs"` attribute on `<code>` since the `<pre>` tag already has `hljs` className.

```tsx
import React from "react";
import hljs from "highlight.js";

interface HighlighterProps {
  content: string;
  language?: string;
}

export default function Highlighter({
  content,
  language,
}: HighlighterProps): JSX.Element {
  const highlighted = language
    ? hljs.highlight(language, content)
    : hljs.highlightAuto(content);

  return (
    <pre className="hljs">
      <code dangerouslySetInnerHTML={{ __html: highlighted.value }} />
    </pre>
  );
}

```
