### ISSUE TITLE
.JADE Support

### ISSUE THREAD

**Issue by SusanthCom** [isagalaev/highlight.js#929]
JADE Support
--------------------
It will be nice to see `.jade` in supported language list.

[docco](http://jashkenas.github.io/docco/) depends on highlight.js. If **highlight.js** supports [JADE](http://jade-lang.com), it will be easy and beautiful to follow literate-programming-style and documentation generation for `.jade` source codes using DOCCO !!!

`.jade` support is mentioned in [languages.json](https://github.com/jashkenas/docco/blob/master/resources/languages.json) of docco but it throws error, since no support for `.jade` in **highlight.js**

---

Note :  [prismjs](http://prismjs.com) supports [JADE](http://jade-lang.com)

---

Sample run of dock on jade: highlight.js throwing error : 
```
$ docco foo.jade 
/usr/local/lib/node_modules/docco/node_modules/highlight.js/lib/highlight.js:443
      throw new Error('Unknown language: "' + name + '"');
      ^

Error: Unknown language: "jade"
    at Object.highlight (/usr/local/lib/node_modules/docco/node_modules/highlight.js/lib/highlight.js:443:13)
    at format (/usr/local/lib/node_modules/docco/docco.js:126:26)
    at /usr/local/lib/node_modules/docco/docco.js:47:11
    at /usr/local/lib/node_modules/docco/node_modules/fs-extra/node_modules/graceful-fs/graceful-fs.js:76:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
$ 
```

Thank You

**Comment by Sannis** [comment]
This is not exactly how it works, here's how: http://highlightjs.readthedocs.org/en/latest/language-requests.html

I'm also suggest to open bug for docco - it should not crash in such cases IMO.

**Comment by SusanthCom** [comment]
Ok. Fine;  Will attempt to make HighlightJs definition file for `.jade`

Submitted [issue report to `docco`](https://github.com/jashkenas/docco/issues/347)
Mean while planning to use [PrismJS](http://prismjs.com/). It supports `.jade` out of box.

Thnaks @Sannis

**Comment by isagalaev** [comment]
By the way, there was one attempt at implementing Jade: https://github.com/isagalaev/highlight.js/pull/250. Looks like it failed mainly because of being too complicated.
