### ISSUE TITLE
Perl 6 support

### ISSUE THREAD

**Issue by ambs** [isagalaev/highlight.js#932]
Hey

First, great tool.
Secondly, unfortunately not much time atm for digging out how to implement a new language.
But if someone reads this and has some free time, a new style for the newly and almost released Perl 6 would be just awesome.

Also, the current Perl syntax could get a face lift for recent Perl news, like function signatures.

Best!

**Comment by isagalaev** [comment]
It would've worked if there was a non-zero amount of people watching highlight.js issues list for an opportunity to get themselves busy with implementing a language definition someone's asked about. This is not the reality, however. If someone wants to implement a highlighting definition for a language they don't need a request for that.
