### ISSUE TITLE
Cannot read property 'replace' of undefined(..) when calling highlightBlock() or highlightAuto()

### ISSUE THREAD

**Issue by TheZoker** [isagalaev/highlight.js#933]
When I call `hljs.highlightBlock();` or `hljs.highlightAuto();`
I get this error: `Cannot read property 'replace' of undefined(..)`
![img_2015 09 14_12h40m34s_001_](https://cloud.githubusercontent.com/assets/1368405/9848035/dfc0c228-5add-11e5-80ae-eaa9a7610c5e.png)

**Comment by Sannis** [comment]
Can you please post full backtrace here? It should open if you click on arrow.

**Comment by TheZoker** [comment]
![img_2015 09 14_12h54m00s_002_](https://cloud.githubusercontent.com/assets/1368405/9848266/bfb48eb8-5adf-11e5-915c-f3c8405899c9.png)

**Comment by Sannis** [comment]
You should use `hljs.initHighlighting()` or `hljs.initHighlightingOnLoad()` for automatic highlighting code blocks on page.

**Comment by TheZoker** [comment]
Yes, but I want to call the function, after  the page loaded.
So I use ajax page load and script in pages loaded like that, are not highlighted:
![img_2015 10 28_00h32m20s_002_](https://cloud.githubusercontent.com/assets/1368405/10775753/6d7d0226-7d0b-11e5-8b5b-075f1220308f.png)

When I press ctrl+r (reload page), it works:
![img_2015 10 28_00h32m31s_003_](https://cloud.githubusercontent.com/assets/1368405/10775754/6d9442d8-7d0b-11e5-9382-aec386ef82b8.png)

**Comment by isagalaev** [comment]
Could you post the actual code where you call a highlighting method? Would be really helpful instead of us trying to guess it :-)

**Comment by TheZoker** [comment]
Here it`s the main part of it:
```
function func() {
    hljs.initHighlighting();
}

$(document).on('pjax:end', function() {
	func();
});

$(document).ready(function() {
	func();
});
```
Demopage is here http://zoker.me/go/comboot-demo-preview

**Comment by isagalaev** [comment]
Ah… This doesn't work because `hljs.initHighlighting` only works once. To highlight anything dynamically you call `hljs.highlightBlock` on specific code blocks. It's okay to let `hljs.initHighlighting` work on `$(document).read` but on `pjax:end` you should first figure out which blocks arent' highlighted yet:

```js
$(document).on('pjax:end', function() {
  $('pre code:not(.hljs)').each(function(i, block) {
    hljs.highlightBlock(block);
  });
});
```

I haven't tested the code, it's just to show the idea.

And your original code didn't work because `hljs.highlightAuto` is a lower level function that accepts code as a simple string, not a DOM node.

**Comment by Sannis** [comment]
It looks like you can hljs befor script that contains it loads to page.

**Comment by isagalaev** [comment]
I think it's safe to close by now, as it's obviously not a bug with either of the methods mentioned.
