### ISSUE TITLE
Make listLanguages() include additional bundled languages

### ISSUE THREAD

**Issue by kurttomlinson** [isagalaev/highlight.js#941]
If I download a custom package of hljs with some "other" languages included, listLanguages() does not print those other languages as options available for syntax highlighting.

**Comment by isagalaev** [comment]
listLanguages() has no choice but to list all the languages that are bundled with the file, there's no separate registry or something. And I just checked by downloading a custom file and it lists all the languages I have selected. Could you check again, just to make sure?

**Comment by Sannis** [comment]
Works good for me too.
