### ISSUE TITLE
highlight.js crashes if language name is undefined

### ISSUE THREAD

**Issue by commenthol** [isagalaev/highlight.js#942]
Version v8.8.0 constantly causes a crash if highlight.js is used from [marked](https://github.com/chjj/marked)

PR #913 introduced case insensitive language support. Unfortunately the line https://github.com/isagalaev/highlight.js/commit/63fb207729d881deea45084c15edc9ab8c32f6e3#diff-5d9139cb5fca768116544c986e8c2c8cR653 causes a crash, if `name` is not given.

This e.g. happed from [marked](https://github.com/chjj/marked) if a code block does not specify a language. 

I propose to use this line instead:

````
652 function getLanguage(name) {
653    name = (name || '').toLowerCase();
````

**Comment by isagalaev** [comment]
I've stumbled on it myself but decided to leave it as is and require the caller to make sure that it passes a string. However now I think you're right and we have to fix the function as it breaks the existing API contract.
