### ISSUE TITLE
License

### ISSUE THREAD

**Issue by enrcor01** [isagalaev/highlight.js#948]
Hi,

According to your license:
    * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.

Would it be possible that you would include the legal text in the js library so that it is easier to redistribute?  I am using gulp and requirejs to combine and minimize the libraries I use, but as the legal text is not in the library it does not get included.

**Comment by Sannis** [comment]
Sounds reasonable, but AFAIK it is common practice to remove comments from minified JS.

**Comment by enrcor01** [comment]
Hi. Yes, I completely understand that the license is removed from the minified version. But the non-minified version does not contain the license and that is what I am missing.

What I do is to extract the licenses from the unminified, so that I am able to include those in my code.

**Comment by tenbits** [comment]
@Sannis , a hash-bang comment is also a common practice. In that comment usually the library name, version and the license name _with the link to the full license text_ is included.

**Comment by Sannis** [comment]
@sourrust  thanks!
