### ISSUE TITLE
Windows freeze with a huge code block parsing

### ISSUE THREAD

**Issue by Soullivaneuh** [isagalaev/highlight.js#954]
I set up Highlight.js to load 500 ms after window loading:

```js
jQuery(window).load(function() {
    setTimeout(function() {
        $('pre code').each(function(i, block) {
            hljs.highlightBlock(block);
        });
    }, 500);
});
```

I can scroll on the page, but it freezes when Highlight.js start parsing on a huge code block, like this one: https://gist.github.com/Soullivaneuh/acc9c0ec725f094bcfbd

Do you have a solution to load parsing "in background" and avoid this page freezing?

Using `8.8.0` version.

**Comment by Sannis** [comment]
You can mark this block as no-highlight to avoid freeze.

```html
<pre><code class="nohighlight">...</code></pre>
```

**Comment by Soullivaneuh** [comment]
> You can mark this block as no-highlight to avoid freeze.

Well, that's a workaround... or not, because this will just disable highlighting.

I want this piece of code to be highlighted, but in background with no window freezing.

**Comment by isagalaev** [comment]
Probably the only thing you could try to do is to write your own initialization function that would call `hljs.highlight()` repeatedly on chunks of the input string of some manageable size. This function returns a parsing state that you can [pass back as a 4th parameter][1] to pick up parsing from the previous point.

[1]: http://highlightjs.readthedocs.org/en/latest/api.html#highlight-name-value-ignore-illegals-continuation

**Comment by Soullivaneuh** [comment]
@isagalaev Thanks for the tip.

But I'm not sur to undersand well the way to do.

Could you please provide a code sample based on mine?

**Comment by frigus02** [comment]
Once we have web worker support (https://github.com/isagalaev/highlight.js/pull/963), you can highlight your code blocks in a worker asynchronously without freezing the page.

You will have to create a separate JavaScript file for the worker, which could look like this:

```javascript
importScripts('../libs/highlight.pack.min.js');

self.onmessage = function (event) {
    var result = hljs.highlightAuto(event.data);
    postMessage(result);
};
```

Then you can use it with this modified snippet of yours:

```javascript
jQuery(window).load(function() {
    $('pre code').each(function(i, block) {
        var code = $(block).text(),
            worker = new Worker('js/myworker.js');

        worker.onmessage = function (event) {
            var result = event.data;
            $(block).addClass('language-' + result.language).html(result.value);
            worker.terminate();
        };

        worker.postMessage(code);
    });
});
```

Of course you have to keep browser support in mind: http://caniuse.com/#feat=webworkers

Another thing, which wasn't mentioned here is that highlight.js can be a bit slow if it needs to autodetect the language. So make sure you add the `language-<javascript|xml|...>` class to your code blocks.

**Comment by Sannis** [comment]
Yep, web workers looks like a good solution here.

**Comment by Soullivaneuh** [comment]
@frigus02 Thanks for the tip, will test.

@Sannis Maybe, but the library should implement a native solution like this to avoid this kind of issue.

At least, a special documentation part should be added for this.

**Comment by activation-function-morg** [comment]
@isagalaev https://openjs.space/questions/the-page-comes-to-a-standstill-while-trying-to-read-through-a-hefty-json
