### ISSUE TITLE
Wrong syntax highlighting in Scala case class

### ISSUE THREAD

**Issue by olafleur** [isagalaev/highlight.js#956]
<img width="439" alt="screen shot 2015-10-14 at 7 59 06 pm" src="https://cloud.githubusercontent.com/assets/1068290/10501309/13bd09e6-72ae-11e5-8d72-52bb71f6af28.png">

First thing, the parentheses should be of the same color.
Second thing, the class after extends does not have the same color every time. Maybe it's intended, I'm not sure.

**Comment by Sannis** [comment]
```scala
abstract class Vertical extends CaseJeu
case class Haut(name: String) extends Vertical
case class Bas(name: String) extends Vertical
```

http://www.scala-lang.org/old/node/107

**Comment by olafleur** [comment]
Not sure to understand your comment.

Is it because you cannot reproduce the bug or because it was fixed?

**Comment by Sannis** [comment]
It's because I would not like to type this example every time when testing :-/

**Comment by olafleur** [comment]
Ok. ;)

**Comment by Sannis** [comment]
![screen shot 2015-10-20 at 00 25 39](https://cloud.githubusercontent.com/assets/77367/10591841/20674712-76c1-11e5-85f2-11642fff5369.png)

**Comment by Sannis** [comment]
At least it now looks consistent.

**Comment by olafleur** [comment]
yes. :)

**Comment by olafleur** [comment]
Thanks !
