### ISSUE TITLE
A chrome extension for custom package to check/uncheck 'other' langs

### ISSUE THREAD

**Issue by ozlerhakan** [isagalaev/highlight.js#957]
Hi,

I have made a teeny tiny chrome extension in order to select/deselect all the available langs from the 'other' section on https://highlightjs.org/download/ . 

P.S. You may need to add a 'misc' section to include such derivative projects and tools so that users can make use of them. 

GitHub repo: https://github.com/ozlerhakan/hljs-checker
Chrome Web store: https://chrome.google.com/webstore/detail/highlightjs-auto-checker/dlfmldhfdefdlfjojpkmeipefdablifb

**Comment by Sannis** [comment]
@isagalaev, maybe we should add this switch to download page code?

**Comment by isagalaev** [comment]
This is something that I deliberately don't want to do. It might seem like a good idea at first but what you end up with is a 300K+ file that is slow to load and increases the chance of snippets detected as languages that the user never ever intended to use. In other words, there are simply no good use cases for a full set of languages apart testing, so I don't want to encourage this as one of the recommended options.

**Comment by ozlerhakan** [comment]
we need to provide all the available langs of highlight.js in [AsciidocFX](https://github.com/asciidocfx/AsciidocFX), this is why I created it for our purpose.

**Comment by isagalaev** [comment]
No argument from me if you need it for your project! I'm explaining why it's not on our download page: too easy to mis-use.

A section on web site for extensions and other third-party projects is long overdue, yes. We'll get it eventually.
