### ISSUE TITLE
Wrong syntax highllighting with JS (es6) template string

### ISSUE THREAD

**Issue by MoOx** [isagalaev/highlight.js#958]
Here is a snippet that create a bug (correctly parsed as lang-js)

```js
import path from "path"

module.exports = {
  entry: {
    index: [ `${ src }/index.js` ],
  },
}
```

![screen shot 2015-10-19 at 22 32 31](https://cloud.githubusercontent.com/assets/157534/10590502/51a6aaf8-76b1-11e5-89f2-048a89820d90.png)

![screen shot 2015-10-19 at 22 34 05](https://cloud.githubusercontent.com/assets/157534/10590550/8f73a890-76b1-11e5-81ee-44db357c636c.png)

Note that this snippet is totally ok

```js
module.exports = {
  entry: {
    index: [ `${ src }/index.js` ],
  },
}
```

![screen shot 2015-10-19 at 22 33 23](https://cloud.githubusercontent.com/assets/157534/10590523/6e4bf96a-76b1-11e5-9e58-ec1acc4360b3.png)

![screen shot 2015-10-19 at 22 35 04](https://cloud.githubusercontent.com/assets/157534/10590572/ae71aeb8-76b1-11e5-9757-9be9d772057b.png)

**Comment by Sannis** [comment]
@MoOx it is because fist line is detected as import and did not found `;` that may be skipped in JS.

**Comment by MoOx** [comment]
Rough ETA for 9.0 ?

**Comment by isagalaev** [comment]
@MoOx the change from 8.10 to 9.0 is simply a rename, as the next release is going to break backwards compatibility with existing class names (see #348). The date is remains the same: December, 1.

**Comment by MoOx** [comment]
Oh sorry I didn't check the milestone date. Why in a month (just curious)?

**Comment by isagalaev** [comment]
We're now doing [regular releases on a 6-week cadence][1]. The number seems to be a sort of an industry practice and may change if we see it doesn't work for us. So far it does :-)

[1]: http://softwaremaniacs.org/blog/2015/09/09/highlight-js-cadence/en/

**Comment by MoOx** [comment]
Ok good to know. Thanks !
I guess I can use the master branch directly via npm :)

**Comment by isagalaev** [comment]
The master branch is not on npm, you'll have to get the source and build it, here's our [building docs][].

[building docs]: http://highlightjs.readthedocs.org/en/latest/building-testing.html

**Comment by MoOx** [comment]
npm can grab a git repo, so I can reference the repo and use your build command as a postinstall script ;)
Thanks for the link.
