### ISSUE TITLE
Release 8.9.0

### ISSUE THREAD

**Issue by Sannis** [isagalaev/highlight.js#959]
Lets do it.

**Comment by isagalaev** [comment]
Well, it's Tuesday already in Moscow I guess :-)

**Comment by Sannis** [comment]
I think nobody will merge some other tasks today, so maybe its time, yay.

**Comment by isagalaev** [comment]
Thanks! Almost everything worked fine this time. There's a slight problem with the snippet on highlightjs.org not being highlighted. I'm on it.
