### ISSUE TITLE
Fix minified version of 8.9.0

### ISSUE THREAD

**Issue by Sannis** [isagalaev/highlight.js#960]

**Comment by Sannis** [comment]
It breaks on replaceSkippingStrings

**Comment by isagalaev** [comment]
I wonder when it's started…

**Comment by isagalaev** [comment]
Aha… Looks like it's adding the license in ffbc2c9b558c7

**Comment by isagalaev** [comment]
Let's simply revert this particular commit and release 8.9.1 without it. Can you do that?

**Comment by Sannis** [comment]
Yep, in progress.

But, unfortunately, not only that commit breaks it, will investigate it deeper tomorrow.

**Comment by isagalaev** [comment]
Yeah, I reverted that bit but now it hangs on highlighting.

So, you're going to push the 8.9.1 now, right?

**Comment by isagalaev** [comment]
Oh, it's already up. That was fast :-)
BTW, we need automated tests for the minified build too. @sourrust any ideas?

**Comment by sourrust** [comment]
I added the license to the minified browser build. I'll try to get something for minified build testing tomorrow.

**Comment by Sannis** [comment]
@isagalaev suddenly this is my mistake that confuse highlight.js custom minifier. This patch fixes it:
```
diff --git a/src/languages/scala.js b/src/languages/scala.js
index 9e5dd75..bf143a1 100644
--- a/src/languages/scala.js
+++ b/src/languages/scala.js
@@ -45,9 +45,9 @@ function(hljs) {
         relevance: 10
       },
       {
-        'className': 'params',
-        'begin': /\(/,
-        'end': /\)/,
+        className: 'params',
+        begin: /\(/,
+        end: /\)/,
         relevance: 0
       },
       NAME
```

No thinking what is the best way to test this case.

**Comment by isagalaev** [comment]
We don't need to test the build in details: that's what the rest of the test suite is for. We should only build it and make sure it's not completely broken by, say, simply calling `hljs.highlight` with one snippet. A "smoke test", basically.

**Comment by sourrust** [comment]
Ok, I add a small test for the minified build. After running either the cdn or browser build, you can call `npm run test-minified`.

**Comment by Sannis** [comment]
Finally:
![screen shot 2015-10-21 at 10 31 45](https://cloud.githubusercontent.com/assets/77367/10630413/f5467cdc-77de-11e5-8254-ad4f57ae4fb2.png)
Looking forward for new challenges :-)

**Comment by isagalaev** [comment]
Cool! Thanks guys!
