### ISSUE TITLE
Add src/languages/index.js

### ISSUE THREAD

**Issue by Anahkiasen** [isagalaev/highlight.js#965]
Simple file that would export each language. This would allow people to do:

```js
import {php, css} from 'highlight.js/lib/languages'
```

**Comment by sourrust** [comment]
It is possible to add that file, but do keep in mind that you still need to register each language to the hljs object. Not only that, but there are some languages that rely on other language and those need to be registered before the language that requires them. With that in mind, it isn't as simple any more, which is what the build script is for. So you example is more like this:

```javascript
import hljs       from 'highlight.js/lib/highlight';
import {php, css} from 'highlight.js/lib/languages';

hljs.registerLanguage('php', php);
hljs.registerLanguage('css', css);
```

Luckily, those two languages don't require any other languages to work or there would be more things needed to be accounted for that aren't immediately obvious unless you look at the source.

**Comment by isagalaev** [comment]
Put simply, highlight.js *source* is not intended to be imported and run as is.

It's an old decision and I'm actually entertaining thoughts about re-evaluating it in the near future but currently we don't want to suggest that the code is importable by adding such a file.
