### ISSUE TITLE
Strings and keywords in .meta look ugly

### ISSUE THREAD

**Issue by isagalaev** [isagalaev/highlight.js#967]
After class names unification there's one problem that stands out like a sore eye: keywords and strings within preprocessor directives look ugly because `.meta` usually has a very distinctive color that doesn't play well with `.string` and `.keywords` showing up within it:

![meta-keywords-strings](https://cloud.githubusercontent.com/assets/99931/10775994/c377f6d6-7cca-11e5-8a22-422f75259a92.png)

Two possible solutions:

- Bless and document usage of selector combinations like `.hljs-meta .hljs-string` and `.hljs-meta *` to reset colors. This is hacky and easy to forget.
- Define separate `.hljs-meta-string` and `.hljs-meta-keyword`.

**Comment by Sannis** [comment]
> This is hacky and easy to forget.

We already have selectors for sub-languages in some themes, so it does not look ugly for me.

**Comment by isagalaev** [comment]
> We already have selectors for sub-languages in some themes, so it does not look ugly for me.

No, we don't anymore :-) That was the whole point.

**Comment by isagalaev** [comment]
Fixed in f7f38f7ca. Also related: 
- 8616294df1 for the same problem with built-in names in lisps
- 9f31cd0bd50 for built-ins in templates
