### ISSUE TITLE
JavaScript single line comments containing "def" incorrectly parsed

### ISSUE THREAD

**Issue by JamesThorpe** [isagalaev/highlight.js#968]
If a JavaScript comment contains the character string `def`, the comment highlighting is not applied.  Multiline/block comments are unaffected, as are comments with no leading whitespace before `def`:

![image](https://cloud.githubusercontent.com/assets/8236566/10786987/91b3a44c-7d65-11e5-81e5-64f530010d13.png)

Live demo available on [jsfiddle](http://jsfiddle.net/4gd8wmxe/1/).

**Comment by isagalaev** [comment]
This is language detection failure. It's not guaranteed to work 100% reliably, and the shorter a fragment the harder it gets. So the best way to fix it is to explicitly specify "javascript" (or "js") as a language for the fragment.

**Comment by JamesThorpe** [comment]
Ahh thanks - that makes sense.  I came here via reveal.js, so I hadn't seen any options beyond just adding the `hljs` class.

**Comment by Sannis** [comment]
Yep, this is just project shortened name.
