### ISSUE TITLE
Document backwards incompatible change in CHANGES.md

### ISSUE THREAD

**Issue by isagalaev** [isagalaev/highlight.js#970]

**Comment by Sannis** [comment]
@isagalaev should we also add some tests that newly submitted languages and styles contains only restricted set of classes?

**Comment by isagalaev** [comment]
I had this idea too, but the problem is that you still can't check that the classes are applied correctly, it has to be done by a human as part of the review process anyway. I'm not sure if an automatic test will be useful, and to whom.

**Comment by isagalaev** [comment]
Fixed in bde9e97b8.
