### ISSUE TITLE
Python functions

### ISSUE THREAD

**Issue by badlydrawnrob** [isagalaev/highlight.js#971]
Great plugin, it would be nice to see highlighting for Python 2/3 functions, it doesn't seem to be working out of the box:

```python
print 'Greater'
print('Greater')
print(len(variable))
```

Python 2 `print 'Greater'` works fine, but here's what I'm seeing in the Marked app for the others (which uses highlight.js):

<img width="558" alt="screen shot 2015-10-30 at 02 25 27" src="https://cloud.githubusercontent.com/assets/1176875/10837105/836ee222-7ead-11e5-83e8-86dc6820f9b7.png">

There aren't any wrappers so I can't add in styling (other than manually adding wrappers)

**Comment by isagalaev** [comment]
This is intentional. Since in Python 3 "print" is not a keyword anymore, we don't highlight it as such (using the following open paren as an indicator).

**Comment by isagalaev** [comment]
Let's not close it just yet, may be @badlydrawnrob meant something else…

**Comment by isagalaev** [comment]
Closing again :-) Feel free to reopen if there's something else here to discuss.
