### ISSUE TITLE
Source version for custom package

### ISSUE THREAD

**Issue by Justineo** [isagalaev/highlight.js#972]
Hi,
I'm developing a Firefox add-on which uses a customized `highlight.pack.js`(generated [here](https://highlightjs.org/download/)) as its syntax highlighter. But due to Mozilla's policy, I need to provide source code for any obfuscated code included in my add-on or submissions will be denied. So is there any chance to adding a "Download source" button for custom packages?

**Comment by frigus02** [comment]
As far as I know you don't need to provide the source code if you use a common library. It may be enough to provide a link to this GitHub repository.

I had no problems getting my add-on reviewed without providing the source code for any minified library I used (angular.js, highlight.js, ...).

**Comment by Justineo** [comment]
@frigus02 My last submission to Firefox was rejected so I made a request here. Maybe because I used a customized pack.

**Comment by frigus02** [comment]
@Justineo Right, maybe the customized pack was the reason. So, as long as the website does not support getting a source version, you might want to get a customized pack using the build script. It supports uncompressed builds already:

http://highlightjs.readthedocs.org/en/latest/building-testing.html#building

**Comment by Justineo** [comment]
OK, thanks! I'll try this.

**Comment by Sannis** [comment]
@Justineo is suggested solution works for you?

**Comment by Justineo** [comment]
I built a customized pack without compression using the building script and submmited a new version but the addon is still waiting for review. I think this should work.

**Comment by Sannis** [comment]
Let us know if it will not be accepted and feel free to reopen this issue.
