### ISSUE TITLE
How to resolve error when i use uglify to compress this plugin because of scripts of languages?

### ISSUE THREAD

**Issue by liangzai-cool** [isagalaev/highlight.js#977]
![qq 20151110183134](https://cloud.githubusercontent.com/assets/6807169/11060156/7086dc66-87d9-11e5-9623-33c97663c3f7.png)

i think the reason is uglify distinguish its are wrong syntax...
what can i do?
my task:
```js
gulp.task('build-js', [], function(){
	return gulp.src(['bower_components/**/*.js', 
	                 'static/**/*.js', 
	                 '!static/dist/**/*.js'
	                ])
	.pipe(uglify().on('error', util.log))
	.pipe(rename(function(path){
		if (!path.basename.endsWith('.min')) {
			//path.basename += '.min';
		}
		path.extname = '.js';
	}))
	.pipe(rev())
	.pipe(gulp.dest('static/dist/js'))
	.pipe(rev.manifest())
	.pipe(gulp.dest('static/dist/rev/js'));
})
```

**Comment by isagalaev** [comment]
We recently switched our toolchain to node 4.x, which version are you using?

**Comment by sourrust** [comment]
This looks more like the script is trying to compress unbuilt language files from bower.

@liangzai-cool just to let you know, we don't control the distribution of bower and you need to actually [build the source][build] before use. So if you want it work either use the [third-party bower][bower] shim or build from the repo with the script we provide within this repo.

[build]: https://highlightjs.readthedocs.org/en/latest/building-testing.html
[bower]: https://github.com/components/highlightjs

**Comment by liangzai-cool** [comment]
@isagalaev my node version is 4.2.2

**Comment by liangzai-cool** [comment]
@sourrust thank you, let me try~.

**Comment by liangzai-cool** [comment]
@sourrust  i have tried it, and build success, but i want to use gulp to run this command `node tools/build.js :common`, then i can code it into my task, can you tell me how to code it? thank you!

**Comment by sourrust** [comment]
Using the `child_process` module is what you want. Something like this works, just change the `cwd` path for where ever the highlight.js repo is for you.

```js
var gulp  = require('gulp');
var spawn = require('child_process').spawn;

gulp.task('hljs', function(done) {
  var options = {
    cwd: __dirname + '/highlight.js/'
  };

  var build = spawn('node', ['tools/build.js', ':common'], options);

  build.stdout.pipe(process.stdout);
  build.stderr.pipe(process.stderr);

  build.on('close', function(error) {
    if(error) throw new Error('tools/build.js exited with ' + error);

    done();
  });
});
```

This was inspired by a different issue that [spawned code][1] similar in nature.

[1]: https://github.com/isagalaev/highlight.js/issues/678#issuecomment-106971963

**Comment by Sannis** [comment]
@liangzai-cool is this works for you?

**Comment by liangzai-cool** [comment]
@Sannis yes,now it works well! thanks!
