### ISSUE TITLE
Extra newlines when XML content contains Windows CR characters

### ISSUE THREAD

**Issue by oakesville** [isagalaev/highlight.js#980]
Highlighted output looks different and contains extraneous newlines in certain situations when the input code includes Windows CR characters (at least when highlighting is performed programmatically).

Here's a Plunker that illustrates this behavior for a simple XML document:
http://plnkr.co/edit/W30o3tjKQm4yeLfg8dpu?p=preview

I've observed the same thing with Groovy under some conditions.  Current workaround is to strip out Windows newlines before highlighting:
```input.replace(/\r/g, '');```

**Comment by isagalaev** [comment]
Fixed just now. Thanks for reporting it!
