### ISSUE TITLE
Yaml support

### ISSUE THREAD

**Issue by rstoenescu** [isagalaev/highlight.js#982]
Hello

Yaml support was added a few days ago. Please release a new NPM version as soon as possible. I need it badly.

Thanks!

**Comment by isagalaev** [comment]
This is not how volunteer driven projects work: we aren't here to answer your urgent requests. If you need something badly that's not there already you're welcome to grab the source and package it for your needs.

**Comment by rstoenescu** [comment]
Didn't mean to sound like that. It was a friendly request and thought it wouldn't be a hassle.

The thing is that I want to use your package, not make myself one, so I can benefit from the ongoing work on the original.

Anyway, sorry to bother you.

**Comment by isagalaev** [comment]
Releasing a sizable library with dozens of dependent downstream projects is always a hassle, it's not something you could just go ahead and do at random.

We actually have a release schedule and the next version is due on December 1. Meanwhile, building a node.js package from the source is actually quite easy, here's our building docs: http://highlightjs.readthedocs.org/en/latest/building-testing.html

P.S. If you don't intend to sound pushy, I guess you might consider to leave out words like "as soon as possible" :-)
