### ISSUE TITLE
Multi-line strings in Julia aren't highlighted well.

### ISSUE THREAD

**Issue by bicycle1885** [isagalaev/highlight.js#984]
The following documentation string is not highlighted as a string:

![screen shot 2015-11-15 at 12 35 39](https://cloud.githubusercontent.com/assets/905683/11167059/7a915b36-8b95-11e5-8d6f-856595e87e7d.png)

I wrote support for this language, but I couldn't find a way to make it work well :cry:.

I'm using the latest master branch (i.e. 3c12521bba4ce7614cab2dd0793a91b3a425e42d).

**Comment by isagalaev** [comment]
I believe simply changing the order of string regexps should fully fix that (more specific rules should come before less specific). Could you please check that on your examples as I couldn't reproduce the exact breakage you demonstrated on this screenshot.

**Comment by bicycle1885** [comment]
Thank you, but unfortunately this didn't solve the problem. When I write this multi-line string in a line by removing newlines, highlighting works file. So, I guess this may be related to newline handling.

**Comment by isagalaev** [comment]
Could you create a sample HTML file somewhere on the web showing the problem? I don't see the problem with the current master code built with Julia: 
![julia](https://cloud.githubusercontent.com/assets/99931/11230006/d98dbce0-8d4f-11e5-92c5-a520ffdf359d.png)

**Comment by bicycle1885** [comment]
@isagalaev I've checked that this works in the developer tool. The problem happens only when I inject highlight.js into [remark.js](https://github.com/gnab/remark), so I guess this is not the problem of highlight.js. Thank you for your help!
