### ISSUE TITLE
highlight.pack.js with TypeScript does not support template strings.

### ISSUE THREAD

**Issue by ochrons** [isagalaev/highlight.js#986]
The support is there in 8.9.1 but downloading a pack with TypeScript does not have it. Looking at GitHub source and the downloaded JS file it's clear that the template string part is missing.

**Comment by ochrons** [comment]
Also Scala seems to be really old version in the pack. It is missing commits from May 2015 like https://github.com/isagalaev/highlight.js/commit/5178fe935b03cf7ae4ff0c91912ecd53d7a342d3

**Comment by isagalaev** [comment]
Indeed, TypeScript template strings didn't make it into 8.9.1, they were commited one day after the release. Our next release is scheduled on December, 1.

The Scala problem is trickier, I'll have too look deeper why this commit is not in master any longer.

**Comment by isagalaev** [comment]
About that Scala changes… Despite them being quite old, they were not in master by 8.9.1 since they started their life on a separate long-standing branch that was merged in master only recently. So, no mystery here either, this improved support (#846) will be in the next release as well.
