### ISSUE TITLE
when code include '<' , then show not appear 

### ISSUE THREAD

**Issue by vimer** [isagalaev/highlight.js#990]
when code appear '<' , such as "#include <stdio.h> ...", use highlight.js , '<' not appear .

**Comment by sourrust** [comment]
This actually has nothing to do with highlight.js and everything to do with how HTML works. When you include things like `<` or `>`, you need to escape them so it doesn't get turned into an HTML tags. So to get a `<` literal you need to change it into `&lt;` and `>` escapes to `&gt;`.

**Comment by vimer** [comment]
highlight.js source code : 
function(e){f    unction t(e){return e.replace(/&/gm,"&amp;").replace(/</gm,"&lt;").replace(/>/gm,"&gt;")}

but, it does't works.

**Comment by sourrust** [comment]
By the time the code gets turned into an html tag, there's no way to
distinguish between the original code and html.
