### ISSUE TITLE
haskell highlighting not working

### ISSUE THREAD

**Issue by flip111** [isagalaev/highlight.js#993]
I have page with blocks of php and blocks of haskell. php works, haskell doesn't. Here is a php block

```html
<pre>
  <code class="language-php hljs">
    <span class="hljs-class"><span class="hljs-keyword">class</span> <span class="hljs-title">True</span> </span>{ }  
    <span class="hljs-class"><span class="hljs-keyword">class</span> <span class="hljs-title">False</span> </span>{ }  
  </code>
</pre>
```

and haskell
```html
<pre>
  <code class="language-haskell">data Bool = False | True  
  </code>
</pre>
```

notice that class `hljs` is also not applied.

i cloned this repo https://github.com/highlightjs/cdn-release.git

in `<head>`: `<link rel="stylesheet" href="/highlightjs/build/styles/monokai_sublime.min.css">`

in footer:
```
<script src="/highlightjs/build/highlight.min.js"></script>
<script>hljs.initHighlightingOnLoad();</script>
```

This also goes wrong with elm-lang

**Comment by sourrust** [comment]
The CDN release for for the file `highlight.min.js` only includes common languages to keep the file size down and as a result, you need to add in additional ones that aren't included.

So change the footer should be something like this and it should work:

```html
<script src="/highlightjs/build/highlight.min.js"></script>
<script src="/highlightjs/build/languages/haskell.min.js"></script>
<script src="/highlightjs/build/languages/elm.min.js"></script>
<script>hljs.initHighlightingOnLoad();</script>
```

As a small tip, you can call `hljs.listLanguages()` to see which languages are registered with the hljs object.

**Comment by flip111** [comment]
it works, thanks!

is it also possible to customize hljs to pick my own languages?

**Comment by sourrust** [comment]
You need to clone this repo rather than the cdn version and node.js version 4+ then follow [the build documentation][1].

[1]: https://highlightjs.readthedocs.org/en/latest/building-testing.html

**Comment by isagalaev** [comment]
@flip111 does custom download work for you? https://highlightjs.org/download/

**Comment by flip111** [comment]
ups sorry i didn't see that download.

Should i use `bash` for shell commands?

**Comment by isagalaev** [comment]
> Should i use bash for shell commands?

No, it's not a good fit, actually. I'm not even sure how one would highlight shell commands at all… Syntax is too different and it's not really code anyway.
