### ISSUE TITLE
Can't run npm test

### ISSUE THREAD

**Issue by jf990** [isagalaev/highlight.js#994]
I cannot seem to run the test script. `npm test` fails to load the built library from test/api/ident.js.

 ```
$ npm test

> highlight.js@8.9.1 test /Users/john/Projects/highlight.js
> mocha test/

module.js:339
    throw err;
    ^

Error: Cannot find module '../../build'
```

I do have a build folder but it is at ../build from where I ran npm test. I also tried running from several other folders and I tried moving build folder but always same error.

**Comment by sourrust** [comment]
You need to build the library for node before testing.

```sh
node tools/build.js -t node
npm test
```

**Comment by jf990** [comment]
wow. thanks!
