### ISSUE TITLE
Add Smarty - PHP-Templating-Language

### ISSUE THREAD

**Issue by arnoldstoba** [isagalaev/highlight.js#998]
In my opinion a highlighting for the popular PHP templating language "Smarty" is missing. With Twig being included, Smarty would surely be a nice addition.

http://www.smarty.net/

**Comment by Sannis** [comment]
You can volunteer for it :-)

http://highlightjs.readthedocs.org/en/latest/language-requests.html

**Comment by isagalaev** [comment]
@arnoldstoba what do you mean by "my opinion"? It is a fact: you can look at the source and see there's no Smarty highlighting in there.

**Comment by arnoldstoba** [comment]
@isagalaev I think you misunderstood me here. The "in my opinion" part of my sentence refers to the fact that I think it Smarty should definitely be a part of the Highlight.js core due to its popularity among PHP Developers/Projects. It is surely a fact that it is not included at the moment.

**Comment by isagalaev** [comment]
@arnoldstoba ah, okay. Then the document @Sannis referred to is the answer, yes.
